/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ca.glong.komodo.core.openapi.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import ca.glong.komodo.core.openapi.models.AlertDataOneOf7Data

class AlertDataOneOf7DataTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of AlertDataOneOf7Data
        //val modelInstance = AlertDataOneOf7Data()

        // to test the property `coreVersion` - The core version
        should("test coreVersion") {
            // uncomment below to test the property
            //modelInstance.coreVersion shouldBe ("TODO")
        }

        // to test the property `id` - The id of the server
        should("test id") {
            // uncomment below to test the property
            //modelInstance.id shouldBe ("TODO")
        }

        // to test the property `name` - The name of the server
        should("test name") {
            // uncomment below to test the property
            //modelInstance.name shouldBe ("TODO")
        }

        // to test the property `serverVersion` - The actual server version
        should("test serverVersion") {
            // uncomment below to test the property
            //modelInstance.serverVersion shouldBe ("TODO")
        }

        // to test the property `region` - The region of the server
        should("test region") {
            // uncomment below to test the property
            //modelInstance.region shouldBe ("TODO")
        }

    }
}
