/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ca.glong.komodo.core.openapi.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import ca.glong.komodo.core.openapi.models.CancelRepoBuild

class CancelRepoBuildTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of CancelRepoBuild
        //val modelInstance = CancelRepoBuild()

        // to test the property `repo` - Can be id or name
        should("test repo") {
            // uncomment below to test the property
            //modelInstance.repo shouldBe ("TODO")
        }

    }
}
