/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ca.glong.komodo.core.openapi.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import ca.glong.komodo.core.openapi.models.ClusterVolumeSpecAccessModeAccessibilityRequirements
import ca.glong.komodo.core.openapi.models.HashMapValueInner

class ClusterVolumeSpecAccessModeAccessibilityRequirementsTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ClusterVolumeSpecAccessModeAccessibilityRequirements
        //val modelInstance = ClusterVolumeSpecAccessModeAccessibilityRequirements()

        // to test the property `preferred` - A list of topologies that the volume should attempt to be provisioned in.
        should("test preferred") {
            // uncomment below to test the property
            //modelInstance.preferred shouldBe ("TODO")
        }

        // to test the property `requisite` - A list of required topologies, at least one of which the volume must be accessible from.
        should("test requisite") {
            // uncomment below to test the property
            //modelInstance.requisite shouldBe ("TODO")
        }

    }
}
