/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ca.glong.komodo.core.openapi.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import ca.glong.komodo.core.openapi.models.ClusterVolumeSpecAccessMode
import ca.glong.komodo.core.openapi.models.ClusterVolumeSpecAccessModeAccessibilityRequirements
import ca.glong.komodo.core.openapi.models.ClusterVolumeSpecAccessModeAvailabilityEnum
import ca.glong.komodo.core.openapi.models.ClusterVolumeSpecAccessModeCapacityRange
import ca.glong.komodo.core.openapi.models.ClusterVolumeSpecAccessModeScopeEnum
import ca.glong.komodo.core.openapi.models.ClusterVolumeSpecAccessModeSecrets
import ca.glong.komodo.core.openapi.models.ClusterVolumeSpecAccessModeSharingEnum

class ClusterVolumeSpecAccessModeTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ClusterVolumeSpecAccessMode
        //val modelInstance = ClusterVolumeSpecAccessMode()

        // to test the property `accessibilityRequirements`
        should("test accessibilityRequirements") {
            // uncomment below to test the property
            //modelInstance.accessibilityRequirements shouldBe ("TODO")
        }

        // to test the property `availability` - The availability of the volume for use in tasks. - `active` The volume is fully available for scheduling on the cluster - `pause` No new workloads should use the volume, but existing workloads are not stopped. - `drain` All workloads using this volume should be stopped and rescheduled, and no new ones should be started.
        should("test availability") {
            // uncomment below to test the property
            //modelInstance.availability shouldBe ("TODO")
        }

        // to test the property `capacityRange`
        should("test capacityRange") {
            // uncomment below to test the property
            //modelInstance.capacityRange shouldBe ("TODO")
        }

        // to test the property `scope` - The set of nodes this volume can be used on at one time. - `single` The volume may only be scheduled to one node at a time. - `multi` the volume may be scheduled to any supported number of nodes at a time.
        should("test scope") {
            // uncomment below to test the property
            //modelInstance.scope shouldBe ("TODO")
        }

        // to test the property `secrets` - Swarm Secrets that are passed to the CSI storage plugin when operating on this volume.
        should("test secrets") {
            // uncomment below to test the property
            //modelInstance.secrets shouldBe ("TODO")
        }

        // to test the property `sharing` - The number and way that different tasks can use this volume at one time. - `none` The volume may only be used by one task at a time. - `readonly` The volume may be used by any number of tasks, but they all must mount the volume as readonly - `onewriter` The volume may be used by any number of tasks, but only one may mount it as read/write. - `all` The volume may have any number of readers and writers.
        should("test sharing") {
            // uncomment below to test the property
            //modelInstance.sharing shouldBe ("TODO")
        }

    }
}
