/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ca.glong.komodo.core.openapi.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import ca.glong.komodo.core.openapi.models.CommitSync

class CommitSyncTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of CommitSync
        //val modelInstance = CommitSync()

        // to test the property `sync` - Id or name
        should("test sync") {
            // uncomment below to test the property
            //modelInstance.sync shouldBe ("TODO")
        }

    }
}
