/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ca.glong.komodo.core.openapi.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import ca.glong.komodo.core.openapi.models.CreateGitProviderAccount

class CreateGitProviderAccountTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of CreateGitProviderAccount
        //val modelInstance = CreateGitProviderAccount()

        // to test the property `account` - The initial account config. Anything in the _id field will be ignored, as this is generated on creation.
        should("test account") {
            // uncomment below to test the property
            //modelInstance.account shouldBe ("TODO")
        }

    }
}
