/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ca.glong.komodo.core.openapi.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import ca.glong.komodo.core.openapi.models.CreateSwarmConfig

class CreateSwarmConfigTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of CreateSwarmConfig
        //val modelInstance = CreateSwarmConfig()

        // to test the property ``data`` - The data to store in the config
        should("test `data`") {
            // uncomment below to test the property
            //modelInstance.`data` shouldBe ("TODO")
        }

        // to test the property `name` - The name of the config to create
        should("test name") {
            // uncomment below to test the property
            //modelInstance.name shouldBe ("TODO")
        }

        // to test the property `swarm` - Name or id
        should("test swarm") {
            // uncomment below to test the property
            //modelInstance.swarm shouldBe ("TODO")
        }

        // to test the property `labels` - Docker labels to give the config
        should("test labels") {
            // uncomment below to test the property
            //modelInstance.labels shouldBe ("TODO")
        }

        // to test the property `templateDriver` - Optional custom template driver
        should("test templateDriver") {
            // uncomment below to test the property
            //modelInstance.templateDriver shouldBe ("TODO")
        }

    }
}
