/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ca.glong.komodo.core.openapi.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import ca.glong.komodo.core.openapi.models.CreateApiKeyResponse

class CreateApiKeyResponseTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of CreateApiKeyResponse
        //val modelInstance = CreateApiKeyResponse()

        // to test the property `key` - X-API-KEY
        should("test key") {
            // uncomment below to test the property
            //modelInstance.key shouldBe ("TODO")
        }

        // to test the property `secret` - X-API-SECRET  Note. There is no way to get the secret again after it is distributed in this response
        should("test secret") {
            // uncomment below to test the property
            //modelInstance.secret shouldBe ("TODO")
        }

    }
}
