/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ca.glong.komodo.core.openapi.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import ca.glong.komodo.core.openapi.models.CreateTerminal
import ca.glong.komodo.core.openapi.models.ContainerTerminalMode
import ca.glong.komodo.core.openapi.models.TerminalRecreateMode
import ca.glong.komodo.core.openapi.models.TerminalTarget

class CreateTerminalTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of CreateTerminal
        //val modelInstance = CreateTerminal()

        // to test the property `name` - A name for the Terminal session.
        should("test name") {
            // uncomment below to test the property
            //modelInstance.name shouldBe ("TODO")
        }

        // to test the property `target` - The target to create terminal for
        should("test target") {
            // uncomment below to test the property
            //modelInstance.target shouldBe ("TODO")
        }

        // to test the property `command` - The shell command (eg `bash`) to init the shell.  Default:  - Server: Configured on each Periphery  - ContainerExec: `sh`  - Attach: unused
        should("test command") {
            // uncomment below to test the property
            //modelInstance.command shouldBe ("TODO")
        }

        // to test the property `mode` - For container terminals, choose 'exec' or 'attach'.  Default  - Server: ignored  - Container / Stack / Deployment: `exec`
        should("test mode") {
            // uncomment below to test the property
            //modelInstance.mode shouldBe ("TODO")
        }

        // to test the property `recreate` - Default: `Never`
        should("test recreate") {
            // uncomment below to test the property
            //modelInstance.recreate shouldBe ("TODO")
        }

    }
}
