/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ca.glong.komodo.core.openapi.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import ca.glong.komodo.core.openapi.models.DeleteAllTerminals

class DeleteAllTerminalsTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of DeleteAllTerminals
        //val modelInstance = DeleteAllTerminals()

        // to test the property `server` - Server Id or name
        should("test server") {
            // uncomment below to test the property
            //modelInstance.server shouldBe ("TODO")
        }

    }
}
