/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ca.glong.komodo.core.openapi.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import ca.glong.komodo.core.openapi.models.DeploymentImageOneOf1Params
import ca.glong.komodo.core.openapi.models.Version

class DeploymentImageOneOf1ParamsTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of DeploymentImageOneOf1Params
        //val modelInstance = DeploymentImageOneOf1Params()

        // to test the property `buildId` - The id of the Build
        should("test buildId") {
            // uncomment below to test the property
            //modelInstance.buildId shouldBe ("TODO")
        }

        // to test the property `version` - Use a custom / older version of the image produced by the build. if version is 0.0.0, this means `latest` image.
        should("test version") {
            // uncomment below to test the property
            //modelInstance.version shouldBe ("TODO")
        }

    }
}
