/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ca.glong.komodo.core.openapi.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import ca.glong.komodo.core.openapi.models.DeploymentImageOneOfParams

class DeploymentImageOneOfParamsTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of DeploymentImageOneOfParams
        //val modelInstance = DeploymentImageOneOfParams()

        // to test the property `image` - The docker image, can be from any registry that works with docker and that the host server can reach.
        should("test image") {
            // uncomment below to test the property
            //modelInstance.image shouldBe ("TODO")
        }

    }
}
