/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ca.glong.komodo.core.openapi.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import ca.glong.komodo.core.openapi.models.DestroyContainer
import ca.glong.komodo.core.openapi.models.TerminationSignal

class DestroyContainerTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of DestroyContainer
        //val modelInstance = DestroyContainer()

        // to test the property `container` - The container name
        should("test container") {
            // uncomment below to test the property
            //modelInstance.container shouldBe ("TODO")
        }

        // to test the property `server` - Name or id
        should("test server") {
            // uncomment below to test the property
            //modelInstance.server shouldBe ("TODO")
        }

        // to test the property `signal` - Override the default termination signal.
        should("test signal") {
            // uncomment below to test the property
            //modelInstance.signal shouldBe ("TODO")
        }

        // to test the property `time` - Override the default termination max time.
        should("test time") {
            // uncomment below to test the property
            //modelInstance.time shouldBe ("TODO")
        }

    }
}
