/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ca.glong.komodo.core.openapi.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import ca.glong.komodo.core.openapi.models.DiffDataOneOf2Data

class DiffDataOneOf2DataTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of DiffDataOneOf2Data
        //val modelInstance = DiffDataOneOf2Data()

        // to test the property `current` - The current TOML of the resource to delete
        should("test current") {
            // uncomment below to test the property
            //modelInstance.current shouldBe ("TODO")
        }

    }
}
