/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ca.glong.komodo.core.openapi.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import ca.glong.komodo.core.openapi.models.DockerRegistryAccount

class DockerRegistryAccountTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of DockerRegistryAccount
        //val modelInstance = DockerRegistryAccount()

        // to test the property `id` - The Mongo ID of the docker registry account. This field is de/serialized from/to JSON as `{ \"_id\": { \"$oid\": \"...\" }, ...(rest of DockerRegistryAccount) }`
        should("test id") {
            // uncomment below to test the property
            //modelInstance.id shouldBe ("TODO")
        }

        // to test the property `domain` - The domain of the provider.  For docker registry, this can include 'http://...', however this is not recommended and won't work unless \"insecure registries\" are enabled on your hosts. See <https://docs.docker.com/reference/cli/dockerd/#insecure-registries>.
        should("test domain") {
            // uncomment below to test the property
            //modelInstance.domain shouldBe ("TODO")
        }

        // to test the property `token` - The token in plain text on the db. If the database / host can be accessed this is insecure.
        should("test token") {
            // uncomment below to test the property
            //modelInstance.token shouldBe ("TODO")
        }

        // to test the property `username` - The account username
        should("test username") {
            // uncomment below to test the property
            //modelInstance.username shouldBe ("TODO")
        }

    }
}
