/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ca.glong.komodo.core.openapi.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import ca.glong.komodo.core.openapi.models.EndpointPortConfig
import ca.glong.komodo.core.openapi.models.EndpointPortConfigProtocolEnum
import ca.glong.komodo.core.openapi.models.EndpointPortConfigPublishModeEnum

class EndpointPortConfigTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of EndpointPortConfig
        //val modelInstance = EndpointPortConfig()

        // to test the property `name`
        should("test name") {
            // uncomment below to test the property
            //modelInstance.name shouldBe ("TODO")
        }

        // to test the property `protocol`
        should("test protocol") {
            // uncomment below to test the property
            //modelInstance.protocol shouldBe ("TODO")
        }

        // to test the property `publishMode` - The mode in which port is published.  <p><br /></p>  - \\\"ingress\\\" makes the target port accessible on every node,   regardless of whether there is a task for the service running on   that node or not. - \\\"host\\\" bypasses the routing mesh and publish the port directly on   the swarm node where that service is running.
        should("test publishMode") {
            // uncomment below to test the property
            //modelInstance.publishMode shouldBe ("TODO")
        }

        // to test the property `publishedPort` - The port on the swarm hosts.
        should("test publishedPort") {
            // uncomment below to test the property
            //modelInstance.publishedPort shouldBe ("TODO")
        }

        // to test the property `targetPort` - The port inside the container.
        should("test targetPort") {
            // uncomment below to test the property
            //modelInstance.targetPort shouldBe ("TODO")
        }

    }
}
