/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ca.glong.komodo.core.openapi.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import ca.glong.komodo.core.openapi.models.EndpointSpec
import ca.glong.komodo.core.openapi.models.EndpointPortConfig
import ca.glong.komodo.core.openapi.models.EndpointSpecModeEnum

class EndpointSpecTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of EndpointSpec
        //val modelInstance = EndpointSpec()

        // to test the property `mode` - The mode of resolution to use for internal load balancing between tasks.
        should("test mode") {
            // uncomment below to test the property
            //modelInstance.mode shouldBe ("TODO")
        }

        // to test the property `ports` - List of exposed ports that this service is accessible on from the outside. Ports can only be provided if `vip` resolution mode is used.
        should("test ports") {
            // uncomment below to test the property
            //modelInstance.ports shouldBe ("TODO")
        }

    }
}
