/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ca.glong.komodo.core.openapi.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import ca.glong.komodo.core.openapi.models.ExecutionOneOf74

class ExecutionOneOf74Test : ShouldSpec() {
    init {
        // uncomment below to create an instance of ExecutionOneOf74
        //val modelInstance = ExecutionOneOf74()

        // to test the property `params` - **Admin only.** Backs up the Komodo Core database to compressed jsonl files. Response: [Update]. Aliases: `backup-database`, `backup-db`, `backup`.  Mount a folder to `/backups`, and Core will use it to create timestamped database dumps, which can be restored using the Komodo CLI.  https://komo.do/docs/setup/backup
        should("test params") {
            // uncomment below to test the property
            //modelInstance.params shouldBe ("TODO")
        }

        // to test the property `type`
        should("test type") {
            // uncomment below to test the property
            //modelInstance.type shouldBe ("TODO")
        }

    }
}
