/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ca.glong.komodo.core.openapi.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import ca.glong.komodo.core.openapi.models.ExecutionOneOf59
import ca.glong.komodo.core.openapi.models.DeleteVolume

class ExecutionOneOf59Test : ShouldSpec() {
    init {
        // uncomment below to create an instance of ExecutionOneOf59
        //val modelInstance = ExecutionOneOf59()

        // to test the property `params`
        should("test params") {
            // uncomment below to test the property
            //modelInstance.params shouldBe ("TODO")
        }

        // to test the property `type`
        should("test type") {
            // uncomment below to test the property
            //modelInstance.type shouldBe ("TODO")
        }

    }
}
