/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ca.glong.komodo.core.openapi.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import ca.glong.komodo.core.openapi.models.GetAlerter

class GetAlerterTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of GetAlerter
        //val modelInstance = GetAlerter()

        // to test the property `alerter` - Id or name
        should("test alerter") {
            // uncomment below to test the property
            //modelInstance.alerter shouldBe ("TODO")
        }

    }
}
