/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ca.glong.komodo.core.openapi.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import ca.glong.komodo.core.openapi.models.GetBuildsSummaryResponse

class GetBuildsSummaryResponseTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of GetBuildsSummaryResponse
        //val modelInstance = GetBuildsSummaryResponse()

        // to test the property `building` - The number of builds currently building.
        should("test building") {
            // uncomment below to test the property
            //modelInstance.building shouldBe ("TODO")
        }

        // to test the property `failed` - The number of builds with Failed state.
        should("test failed") {
            // uncomment below to test the property
            //modelInstance.failed shouldBe ("TODO")
        }

        // to test the property `ok` - The number of builds with Ok state.
        should("test ok") {
            // uncomment below to test the property
            //modelInstance.ok shouldBe ("TODO")
        }

        // to test the property `total` - The total number of builds in Komodo.
        should("test total") {
            // uncomment below to test the property
            //modelInstance.total shouldBe ("TODO")
        }

        // to test the property `unknown` - The number of builds with unknown state.
        should("test unknown") {
            // uncomment below to test the property
            //modelInstance.unknown shouldBe ("TODO")
        }

    }
}
