/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ca.glong.komodo.core.openapi.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import ca.glong.komodo.core.openapi.models.GetBuildersSummaryResponse

class GetBuildersSummaryResponseTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of GetBuildersSummaryResponse
        //val modelInstance = GetBuildersSummaryResponse()

        // to test the property `total` - The total number of builders.
        should("test total") {
            // uncomment below to test the property
            //modelInstance.total shouldBe ("TODO")
        }

    }
}
