/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ca.glong.komodo.core.openapi.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import ca.glong.komodo.core.openapi.models.GetBuildMonthlyStatsResponse
import ca.glong.komodo.core.openapi.models.BuildStatsDay

class GetBuildMonthlyStatsResponseTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of GetBuildMonthlyStatsResponse
        //val modelInstance = GetBuildMonthlyStatsResponse()

        // to test the property `days`
        should("test days") {
            // uncomment below to test the property
            //modelInstance.days shouldBe ("TODO")
        }

        // to test the property `totalCount`
        should("test totalCount") {
            // uncomment below to test the property
            //modelInstance.totalCount shouldBe ("TODO")
        }

        // to test the property `totalTime`
        should("test totalTime") {
            // uncomment below to test the property
            //modelInstance.totalTime shouldBe ("TODO")
        }

    }
}
