/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ca.glong.komodo.core.openapi.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import ca.glong.komodo.core.openapi.models.GetDeploymentLog

class GetDeploymentLogTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of GetDeploymentLog
        //val modelInstance = GetDeploymentLog()

        // to test the property `deployment` - Id or name
        should("test deployment") {
            // uncomment below to test the property
            //modelInstance.deployment shouldBe ("TODO")
        }

        // to test the property `tail` - The number of lines of the log tail to include. Default: 100. Max: 5000.
        should("test tail") {
            // uncomment below to test the property
            //modelInstance.tail shouldBe ("TODO")
        }

        // to test the property `timestamps` - Enable `--timestamps`
        should("test timestamps") {
            // uncomment below to test the property
            //modelInstance.timestamps shouldBe ("TODO")
        }

    }
}
