/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ca.glong.komodo.core.openapi.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import ca.glong.komodo.core.openapi.models.GetDeploymentActionState

class GetDeploymentActionStateTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of GetDeploymentActionState
        //val modelInstance = GetDeploymentActionState()

        // to test the property `deployment` - Id or name
        should("test deployment") {
            // uncomment below to test the property
            //modelInstance.deployment shouldBe ("TODO")
        }

    }
}
