/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ca.glong.komodo.core.openapi.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import ca.glong.komodo.core.openapi.models.GetReposSummaryResponse

class GetReposSummaryResponseTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of GetReposSummaryResponse
        //val modelInstance = GetReposSummaryResponse()

        // to test the property `building` - The number of repos currently building.
        should("test building") {
            // uncomment below to test the property
            //modelInstance.building shouldBe ("TODO")
        }

        // to test the property `cloning` - The number of repos currently cloning.
        should("test cloning") {
            // uncomment below to test the property
            //modelInstance.cloning shouldBe ("TODO")
        }

        // to test the property `failed` - The number of repos with failed state.
        should("test failed") {
            // uncomment below to test the property
            //modelInstance.failed shouldBe ("TODO")
        }

        // to test the property `ok` - The number of repos with Ok state.
        should("test ok") {
            // uncomment below to test the property
            //modelInstance.ok shouldBe ("TODO")
        }

        // to test the property `pulling` - The number of repos currently pulling.
        should("test pulling") {
            // uncomment below to test the property
            //modelInstance.pulling shouldBe ("TODO")
        }

        // to test the property `total` - The total number of repos
        should("test total") {
            // uncomment below to test the property
            //modelInstance.total shouldBe ("TODO")
        }

        // to test the property `unknown` - The number of repos with unknown state.
        should("test unknown") {
            // uncomment below to test the property
            //modelInstance.unknown shouldBe ("TODO")
        }

    }
}
