/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ca.glong.komodo.core.openapi.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import ca.glong.komodo.core.openapi.models.GetStackLog

class GetStackLogTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of GetStackLog
        //val modelInstance = GetStackLog()

        // to test the property `services` - Filter the logs to only ones from specific services. If empty, will include logs from all services.
        should("test services") {
            // uncomment below to test the property
            //modelInstance.services shouldBe ("TODO")
        }

        // to test the property `stack` - Id or name
        should("test stack") {
            // uncomment below to test the property
            //modelInstance.stack shouldBe ("TODO")
        }

        // to test the property `tail` - The number of lines of the log tail to include. Default: 100. Max: 5000.
        should("test tail") {
            // uncomment below to test the property
            //modelInstance.tail shouldBe ("TODO")
        }

        // to test the property `timestamps` - Enable `--timestamps`
        should("test timestamps") {
            // uncomment below to test the property
            //modelInstance.timestamps shouldBe ("TODO")
        }

    }
}
