/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ca.glong.komodo.core.openapi.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import ca.glong.komodo.core.openapi.models.ImageManifestSummaryAttestationData

class ImageManifestSummaryAttestationDataTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ImageManifestSummaryAttestationData
        //val modelInstance = ImageManifestSummaryAttestationData()

        // to test the property ``for`` - The digest of the image manifest that this attestation is for.
        should("test `for`") {
            // uncomment below to test the property
            //modelInstance.`for` shouldBe ("TODO")
        }

    }
}
