/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ca.glong.komodo.core.openapi.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import ca.glong.komodo.core.openapi.models.InspectSwarmService

class InspectSwarmServiceTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of InspectSwarmService
        //val modelInstance = InspectSwarmService()

        // to test the property `service` - Service id
        should("test service") {
            // uncomment below to test the property
            //modelInstance.service shouldBe ("TODO")
        }

        // to test the property `swarm` - Id or name
        should("test swarm") {
            // uncomment below to test the property
            //modelInstance.swarm shouldBe ("TODO")
        }

    }
}
