/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ca.glong.komodo.core.openapi.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import ca.glong.komodo.core.openapi.models.ListApiKeysForServiceUser

class ListApiKeysForServiceUserTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ListApiKeysForServiceUser
        //val modelInstance = ListApiKeysForServiceUser()

        // to test the property `user` - Id or username
        should("test user") {
            // uncomment below to test the property
            //modelInstance.user shouldBe ("TODO")
        }

    }
}
