/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ca.glong.komodo.core.openapi.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import ca.glong.komodo.core.openapi.models.Log

class LogTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of Log
        //val modelInstance = Log()

        // to test the property `command` - The command which was executed
        should("test command") {
            // uncomment below to test the property
            //modelInstance.command shouldBe ("TODO")
        }

        // to test the property `endTs` - The end time of the command execution
        should("test endTs") {
            // uncomment below to test the property
            //modelInstance.endTs shouldBe ("TODO")
        }

        // to test the property `stage` - A label for the log
        should("test stage") {
            // uncomment below to test the property
            //modelInstance.stage shouldBe ("TODO")
        }

        // to test the property `startTs` - The start time of the command execution
        should("test startTs") {
            // uncomment below to test the property
            //modelInstance.startTs shouldBe ("TODO")
        }

        // to test the property `stderr` - The output of the command in the error channel
        should("test stderr") {
            // uncomment below to test the property
            //modelInstance.stderr shouldBe ("TODO")
        }

        // to test the property `stdout` - The output of the command in the standard channel
        should("test stdout") {
            // uncomment below to test the property
            //modelInstance.stdout shouldBe ("TODO")
        }

        // to test the property `success` - Whether the command run was successful
        should("test success") {
            // uncomment below to test the property
            //modelInstance.success shouldBe ("TODO")
        }

    }
}
