/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ca.glong.komodo.core.openapi.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import ca.glong.komodo.core.openapi.models.MongoIdObj

class MongoIdObjTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of MongoIdObj
        //val modelInstance = MongoIdObj()

        // to test the property `dollarOid`
        should("test dollarOid") {
            // uncomment below to test the property
            //modelInstance.dollarOid shouldBe ("TODO")
        }

    }
}
