/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ca.glong.komodo.core.openapi.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import ca.glong.komodo.core.openapi.models.MountVolumeOptions
import ca.glong.komodo.core.openapi.models.MountVolumeOptionsDriverConfig

class MountVolumeOptionsTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of MountVolumeOptions
        //val modelInstance = MountVolumeOptions()

        // to test the property `driverConfig`
        should("test driverConfig") {
            // uncomment below to test the property
            //modelInstance.driverConfig shouldBe ("TODO")
        }

        // to test the property `labels` - User-defined key/value metadata.
        should("test labels") {
            // uncomment below to test the property
            //modelInstance.labels shouldBe ("TODO")
        }

        // to test the property `noCopy` - Populate volume with data from the target.
        should("test noCopy") {
            // uncomment below to test the property
            //modelInstance.noCopy shouldBe ("TODO")
        }

        // to test the property `subpath` - Source path inside the volume. Must be relative without any back traversals.
        should("test subpath") {
            // uncomment below to test the property
            //modelInstance.subpath shouldBe ("TODO")
        }

    }
}
