/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ca.glong.komodo.core.openapi.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import ca.glong.komodo.core.openapi.models.MountPoint
import ca.glong.komodo.core.openapi.models.MountTypeEnum

class MountPointTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of MountPoint
        //val modelInstance = MountPoint()

        // to test the property `destination` - Destination is the path relative to the container root (`/`) where the `Source` is mounted inside the container.
        should("test destination") {
            // uncomment below to test the property
            //modelInstance.destination shouldBe ("TODO")
        }

        // to test the property `driver` - Driver is the volume driver used to create the volume (if it is a volume).
        should("test driver") {
            // uncomment below to test the property
            //modelInstance.driver shouldBe ("TODO")
        }

        // to test the property `mode` - Mode is a comma separated list of options supplied by the user when creating the bind/volume mount.  The default is platform-specific (`\\\"z\\\"` on Linux, empty on Windows).
        should("test mode") {
            // uncomment below to test the property
            //modelInstance.mode shouldBe ("TODO")
        }

        // to test the property `name` - Name is the name reference to the underlying data defined by `Source` e.g., the volume name.
        should("test name") {
            // uncomment below to test the property
            //modelInstance.name shouldBe ("TODO")
        }

        // to test the property `propagation` - Propagation describes how mounts are propagated from the host into the mount point, and vice-versa. Refer to the [Linux kernel documentation](https://www.kernel.org/doc/Documentation/filesystems/sharedsubtree.txt) for details. This field is not used on Windows.
        should("test propagation") {
            // uncomment below to test the property
            //modelInstance.propagation shouldBe ("TODO")
        }

        // to test the property `RW` - Whether the mount is mounted writable (read-write).
        should("test RW") {
            // uncomment below to test the property
            //modelInstance.RW shouldBe ("TODO")
        }

        // to test the property `source` - Source location of the mount.  For volumes, this contains the storage location of the volume (within `/var/lib/docker/volumes/`). For bind-mounts, and `npipe`, this contains the source (host) part of the bind-mount. For `tmpfs` mount points, this field is empty.
        should("test source") {
            // uncomment below to test the property
            //modelInstance.source shouldBe ("TODO")
        }

        // to test the property `type` - The mount type:  - `bind` a mount of a file or directory from the host into the container. - `volume` a docker volume with the given `Name`. - `tmpfs` a `tmpfs`. - `npipe` a named pipe from the host into the container. - `cluster` a Swarm cluster volume
        should("test type") {
            // uncomment below to test the property
            //modelInstance.type shouldBe ("TODO")
        }

    }
}
