/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ca.glong.komodo.core.openapi.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import ca.glong.komodo.core.openapi.models.NetworkContainer

class NetworkContainerTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of NetworkContainer
        //val modelInstance = NetworkContainer()

        // to test the property `containerID` - This is the key on the incoming map of NetworkContainer
        should("test containerID") {
            // uncomment below to test the property
            //modelInstance.containerID shouldBe ("TODO")
        }

        // to test the property `endpointID`
        should("test endpointID") {
            // uncomment below to test the property
            //modelInstance.endpointID shouldBe ("TODO")
        }

        // to test the property `ipv4Address`
        should("test ipv4Address") {
            // uncomment below to test the property
            //modelInstance.ipv4Address shouldBe ("TODO")
        }

        // to test the property `ipv6Address`
        should("test ipv6Address") {
            // uncomment below to test the property
            //modelInstance.ipv6Address shouldBe ("TODO")
        }

        // to test the property `macAddress`
        should("test macAddress") {
            // uncomment below to test the property
            //modelInstance.macAddress shouldBe ("TODO")
        }

        // to test the property `name`
        should("test name") {
            // uncomment below to test the property
            //modelInstance.name shouldBe ("TODO")
        }

    }
}
