/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ca.glong.komodo.core.openapi.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import ca.glong.komodo.core.openapi.models.NetworkSettings
import ca.glong.komodo.core.openapi.models.EndpointSettings
import ca.glong.komodo.core.openapi.models.PortBinding

class NetworkSettingsTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of NetworkSettings
        //val modelInstance = NetworkSettings()

        // to test the property `networks` - Information about all networks that the container is connected to.
        should("test networks") {
            // uncomment below to test the property
            //modelInstance.networks shouldBe ("TODO")
        }

        // to test the property `ports`
        should("test ports") {
            // uncomment below to test the property
            //modelInstance.ports shouldBe ("TODO")
        }

        // to test the property `sandboxID` - SandboxID uniquely represents a container's network stack.
        should("test sandboxID") {
            // uncomment below to test the property
            //modelInstance.sandboxID shouldBe ("TODO")
        }

        // to test the property `sandboxKey` - SandboxKey is the full path of the netns handle
        should("test sandboxKey") {
            // uncomment below to test the property
            //modelInstance.sandboxKey shouldBe ("TODO")
        }

    }
}
