/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ca.glong.komodo.core.openapi.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import ca.glong.komodo.core.openapi.models.NodeDescription
import ca.glong.komodo.core.openapi.models.EngineDescription
import ca.glong.komodo.core.openapi.models.Platform
import ca.glong.komodo.core.openapi.models.ResourceObject
import ca.glong.komodo.core.openapi.models.TlsInfo

class NodeDescriptionTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of NodeDescription
        //val modelInstance = NodeDescription()

        // to test the property `engine`
        should("test engine") {
            // uncomment below to test the property
            //modelInstance.engine shouldBe ("TODO")
        }

        // to test the property `hostname`
        should("test hostname") {
            // uncomment below to test the property
            //modelInstance.hostname shouldBe ("TODO")
        }

        // to test the property `platform`
        should("test platform") {
            // uncomment below to test the property
            //modelInstance.platform shouldBe ("TODO")
        }

        // to test the property `resources`
        should("test resources") {
            // uncomment below to test the property
            //modelInstance.resources shouldBe ("TODO")
        }

        // to test the property `tlSInfo`
        should("test tlSInfo") {
            // uncomment below to test the property
            //modelInstance.tlSInfo shouldBe ("TODO")
        }

    }
}
