/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ca.glong.komodo.core.openapi.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import ca.glong.komodo.core.openapi.models.NodeSpec
import ca.glong.komodo.core.openapi.models.NodeSpecAvailabilityEnum
import ca.glong.komodo.core.openapi.models.NodeSpecRoleEnum

class NodeSpecTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of NodeSpec
        //val modelInstance = NodeSpec()

        // to test the property `availability` - Availability of the node.
        should("test availability") {
            // uncomment below to test the property
            //modelInstance.availability shouldBe ("TODO")
        }

        // to test the property `labels` - User-defined key/value metadata.
        should("test labels") {
            // uncomment below to test the property
            //modelInstance.labels shouldBe ("TODO")
        }

        // to test the property `name` - Name for the node.
        should("test name") {
            // uncomment below to test the property
            //modelInstance.name shouldBe ("TODO")
        }

        // to test the property `role` - Role of the node.
        should("test role") {
            // uncomment below to test the property
            //modelInstance.role shouldBe ("TODO")
        }

    }
}
