/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ca.glong.komodo.core.openapi.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import ca.glong.komodo.core.openapi.models.NtfyAlerterEndpoint

class NtfyAlerterEndpointTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of NtfyAlerterEndpoint
        //val modelInstance = NtfyAlerterEndpoint()

        // to test the property `email` - Optional E-Mail Address to enable ntfy email notifications. SMTP must be configured on the ntfy server.
        should("test email") {
            // uncomment below to test the property
            //modelInstance.email shouldBe ("TODO")
        }

        // to test the property `url` - The ntfy topic URL
        should("test url") {
            // uncomment below to test the property
            //modelInstance.url shouldBe ("TODO")
        }

    }
}
