/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ca.glong.komodo.core.openapi.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import ca.glong.komodo.core.openapi.models.ProcedureConfig
import ca.glong.komodo.core.openapi.models.ProcedureStage
import ca.glong.komodo.core.openapi.models.ScheduleFormat

class ProcedureConfigTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ProcedureConfig
        //val modelInstance = ProcedureConfig()

        // to test the property `failureAlert` - Whether to send alerts when this procedure fails.
        should("test failureAlert") {
            // uncomment below to test the property
            //modelInstance.failureAlert shouldBe ("TODO")
        }

        // to test the property `schedule` - Optionally provide a schedule for the procedure to run on.  There are 2 ways to specify a schedule:  1. Regular CRON expression:  (second, minute, hour, day, month, day-of-week) ```text 0 0 0 1,15 * ? ```  2. \"English\" expression via [english-to-cron](https://crates.io/crates/english-to-cron):  ```text at midnight on the 1st and 15th of the month ```
        should("test schedule") {
            // uncomment below to test the property
            //modelInstance.schedule shouldBe ("TODO")
        }

        // to test the property `scheduleAlert` - Whether to send alerts when the schedule was run.
        should("test scheduleAlert") {
            // uncomment below to test the property
            //modelInstance.scheduleAlert shouldBe ("TODO")
        }

        // to test the property `scheduleEnabled` - Whether schedule is enabled if one is provided. Can be used to temporarily disable the schedule.
        should("test scheduleEnabled") {
            // uncomment below to test the property
            //modelInstance.scheduleEnabled shouldBe ("TODO")
        }

        // to test the property `scheduleFormat` - Choose whether to specify schedule as regular CRON, or using the english to CRON parser.
        should("test scheduleFormat") {
            // uncomment below to test the property
            //modelInstance.scheduleFormat shouldBe ("TODO")
        }

        // to test the property `scheduleTimezone` - Optional. A TZ Identifier. If not provided, will use Core local timezone. https://en.wikipedia.org/wiki/List_of_tz_database_time_zones.
        should("test scheduleTimezone") {
            // uncomment below to test the property
            //modelInstance.scheduleTimezone shouldBe ("TODO")
        }

        // to test the property `stages` - The stages to be run by the procedure.
        should("test stages") {
            // uncomment below to test the property
            //modelInstance.stages shouldBe ("TODO")
        }

        // to test the property `webhookEnabled` - Whether incoming webhooks actually trigger action.
        should("test webhookEnabled") {
            // uncomment below to test the property
            //modelInstance.webhookEnabled shouldBe ("TODO")
        }

        // to test the property `webhookSecret` - Optionally provide an alternate webhook secret for this procedure. If its an empty string, use the default secret from the config.
        should("test webhookSecret") {
            // uncomment below to test the property
            //modelInstance.webhookSecret shouldBe ("TODO")
        }

    }
}
