/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ca.glong.komodo.core.openapi.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import ca.glong.komodo.core.openapi.models.RemoveSwarmSecrets

class RemoveSwarmSecretsTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of RemoveSwarmSecrets
        //val modelInstance = RemoveSwarmSecrets()

        // to test the property `secrets` - Secret names or ids
        should("test secrets") {
            // uncomment below to test the property
            //modelInstance.secrets shouldBe ("TODO")
        }

        // to test the property `swarm` - Name or id
        should("test swarm") {
            // uncomment below to test the property
            //modelInstance.swarm shouldBe ("TODO")
        }

    }
}
