/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ca.glong.komodo.core.openapi.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import ca.glong.komodo.core.openapi.models.RepoConfig
import ca.glong.komodo.core.openapi.models.SystemCommand

class RepoConfigTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of RepoConfig
        //val modelInstance = RepoConfig()

        // to test the property `branch` - The repo branch.
        should("test branch") {
            // uncomment below to test the property
            //modelInstance.branch shouldBe ("TODO")
        }

        // to test the property `builderId` - Attach a builder to 'build' the repo.
        should("test builderId") {
            // uncomment below to test the property
            //modelInstance.builderId shouldBe ("TODO")
        }

        // to test the property `commit` - Optionally set a specific commit hash.
        should("test commit") {
            // uncomment below to test the property
            //modelInstance.commit shouldBe ("TODO")
        }

        // to test the property `envFilePath` - The name of the written environment file before `docker compose up`. Relative to the repo root. Default: .env
        should("test envFilePath") {
            // uncomment below to test the property
            //modelInstance.envFilePath shouldBe ("TODO")
        }

        // to test the property `environment` - The environment variables passed to the compose file. They will be written to path defined in env_file_path, which is given relative to the run directory.  If it is empty, no file will be written.
        should("test environment") {
            // uncomment below to test the property
            //modelInstance.environment shouldBe ("TODO")
        }

        // to test the property `gitAccount` - The git account used to access private repos. Passing empty string can only clone public repos.  Note. A token for the account must be available in the core config or the builder server's periphery config for the configured git provider.
        should("test gitAccount") {
            // uncomment below to test the property
            //modelInstance.gitAccount shouldBe ("TODO")
        }

        // to test the property `gitHttps` - Whether to use https to clone the repo (versus http). Default: true  Note. Komodo does not currently support cloning repos via ssh.
        should("test gitHttps") {
            // uncomment below to test the property
            //modelInstance.gitHttps shouldBe ("TODO")
        }

        // to test the property `gitProvider` - The git provider domain. Default: github.com
        should("test gitProvider") {
            // uncomment below to test the property
            //modelInstance.gitProvider shouldBe ("TODO")
        }

        // to test the property `links` - Configure quick links that are displayed in the resource header
        should("test links") {
            // uncomment below to test the property
            //modelInstance.links shouldBe ("TODO")
        }

        // to test the property `onClone` - Command to be run after the repo is cloned. The path is relative to the root of the repo.
        should("test onClone") {
            // uncomment below to test the property
            //modelInstance.onClone shouldBe ("TODO")
        }

        // to test the property `onPull` - Command to be run after the repo is pulled. The path is relative to the root of the repo.
        should("test onPull") {
            // uncomment below to test the property
            //modelInstance.onPull shouldBe ("TODO")
        }

        // to test the property `path` - Explicitly specify the folder to clone the repo in. - If absolute (has leading '/')   - Used directly as the path - If relative   - Taken relative to Periphery `repo_dir` (ie `${root_directory}/repos`)
        should("test path") {
            // uncomment below to test the property
            //modelInstance.path shouldBe ("TODO")
        }

        // to test the property `repo` - The github repo to clone.
        should("test repo") {
            // uncomment below to test the property
            //modelInstance.repo shouldBe ("TODO")
        }

        // to test the property `serverId` - The server to clone the repo on.
        should("test serverId") {
            // uncomment below to test the property
            //modelInstance.serverId shouldBe ("TODO")
        }

        // to test the property `skipSecretInterp` - Whether to skip secret interpolation into the repo environment variable file.
        should("test skipSecretInterp") {
            // uncomment below to test the property
            //modelInstance.skipSecretInterp shouldBe ("TODO")
        }

        // to test the property `webhookEnabled` - Whether incoming webhooks actually trigger action.
        should("test webhookEnabled") {
            // uncomment below to test the property
            //modelInstance.webhookEnabled shouldBe ("TODO")
        }

        // to test the property `webhookSecret` - Optionally provide an alternate webhook secret for this repo. If its an empty string, use the default secret from the config.
        should("test webhookSecret") {
            // uncomment below to test the property
            //modelInstance.webhookSecret shouldBe ("TODO")
        }

    }
}
