/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ca.glong.komodo.core.openapi.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import ca.glong.komodo.core.openapi.models.ResourceObject
import ca.glong.komodo.core.openapi.models.VecInner

class ResourceObjectTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ResourceObject
        //val modelInstance = ResourceObject()

        // to test the property `genericResources`
        should("test genericResources") {
            // uncomment below to test the property
            //modelInstance.genericResources shouldBe ("TODO")
        }

        // to test the property `memoryBytes`
        should("test memoryBytes") {
            // uncomment below to test the property
            //modelInstance.memoryBytes shouldBe ("TODO")
        }

        // to test the property `nanoCPUs`
        should("test nanoCPUs") {
            // uncomment below to test the property
            //modelInstance.nanoCPUs shouldBe ("TODO")
        }

    }
}
