/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ca.glong.komodo.core.openapi.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import ca.glong.komodo.core.openapi.models.ResourceTarget
import ca.glong.komodo.core.openapi.models.ResourceTargetOneOf
import ca.glong.komodo.core.openapi.models.ResourceTargetOneOf1
import ca.glong.komodo.core.openapi.models.ResourceTargetOneOf10
import ca.glong.komodo.core.openapi.models.ResourceTargetOneOf11
import ca.glong.komodo.core.openapi.models.ResourceTargetOneOf2
import ca.glong.komodo.core.openapi.models.ResourceTargetOneOf3
import ca.glong.komodo.core.openapi.models.ResourceTargetOneOf4
import ca.glong.komodo.core.openapi.models.ResourceTargetOneOf5
import ca.glong.komodo.core.openapi.models.ResourceTargetOneOf6
import ca.glong.komodo.core.openapi.models.ResourceTargetOneOf7
import ca.glong.komodo.core.openapi.models.ResourceTargetOneOf8
import ca.glong.komodo.core.openapi.models.ResourceTargetOneOf9

class ResourceTargetTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ResourceTarget
        //val modelInstance = ResourceTarget()

        // to test the property `id`
        should("test id") {
            // uncomment below to test the property
            //modelInstance.id shouldBe ("TODO")
        }

        // to test the property `type`
        should("test type") {
            // uncomment below to test the property
            //modelInstance.type shouldBe ("TODO")
        }

    }
}
