/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ca.glong.komodo.core.openapi.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import ca.glong.komodo.core.openapi.models.SearchDeploymentLog
import ca.glong.komodo.core.openapi.models.SearchCombinator

class SearchDeploymentLogTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of SearchDeploymentLog
        //val modelInstance = SearchDeploymentLog()

        // to test the property `deployment` - Id or name
        should("test deployment") {
            // uncomment below to test the property
            //modelInstance.deployment shouldBe ("TODO")
        }

        // to test the property `terms` - The terms to search for.
        should("test terms") {
            // uncomment below to test the property
            //modelInstance.terms shouldBe ("TODO")
        }

        // to test the property `combinator` - When searching for multiple terms, can use `AND` or `OR` combinator.  - `AND`: Only include lines with **all** terms present in that line. - `OR`: Include lines that have one or more matches in the terms.
        should("test combinator") {
            // uncomment below to test the property
            //modelInstance.combinator shouldBe ("TODO")
        }

        // to test the property `invert` - Invert the results, ie return all lines that DON'T match the terms / combinator.
        should("test invert") {
            // uncomment below to test the property
            //modelInstance.invert shouldBe ("TODO")
        }

        // to test the property `timestamps` - Enable `--timestamps`
        should("test timestamps") {
            // uncomment below to test the property
            //modelInstance.timestamps shouldBe ("TODO")
        }

    }
}
