/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ca.glong.komodo.core.openapi.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import ca.glong.komodo.core.openapi.models.ServiceSpecUpdateConfig
import ca.glong.komodo.core.openapi.models.ServiceSpecUpdateConfigFailureActionEnum
import ca.glong.komodo.core.openapi.models.ServiceSpecUpdateConfigOrderEnum

class ServiceSpecUpdateConfigTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ServiceSpecUpdateConfig
        //val modelInstance = ServiceSpecUpdateConfig()

        // to test the property `delay` - Amount of time between updates, in nanoseconds.
        should("test delay") {
            // uncomment below to test the property
            //modelInstance.delay shouldBe ("TODO")
        }

        // to test the property `failureAction` - Action to take if an updated task fails to run, or stops running during the update.
        should("test failureAction") {
            // uncomment below to test the property
            //modelInstance.failureAction shouldBe ("TODO")
        }

        // to test the property `maxFailureRatio` - The fraction of tasks that may fail during an update before the failure action is invoked, specified as a floating point number between 0 and 1.
        should("test maxFailureRatio") {
            // uncomment below to test the property
            //modelInstance.maxFailureRatio shouldBe ("TODO")
        }

        // to test the property `monitor` - Amount of time to monitor each updated task for failures, in nanoseconds.
        should("test monitor") {
            // uncomment below to test the property
            //modelInstance.monitor shouldBe ("TODO")
        }

        // to test the property `order` - The order of operations when rolling out an updated task. Either the old task is shut down before the new task is started, or the new task is started before the old task is shut down.
        should("test order") {
            // uncomment below to test the property
            //modelInstance.order shouldBe ("TODO")
        }

        // to test the property `parallelism` - Maximum number of tasks to be updated in one iteration (0 means unlimited parallelism).
        should("test parallelism") {
            // uncomment below to test the property
            //modelInstance.parallelism shouldBe ("TODO")
        }

    }
}
