/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ca.glong.komodo.core.openapi.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import ca.glong.komodo.core.openapi.models.ServiceSpecModeReplicatedJob

class ServiceSpecModeReplicatedJobTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ServiceSpecModeReplicatedJob
        //val modelInstance = ServiceSpecModeReplicatedJob()

        // to test the property `maxConcurrent` - The maximum number of replicas to run simultaneously.
        should("test maxConcurrent") {
            // uncomment below to test the property
            //modelInstance.maxConcurrent shouldBe ("TODO")
        }

        // to test the property `totalCompletions` - The total number of replicas desired to reach the Completed state. If unset, will default to the value of `MaxConcurrent`
        should("test totalCompletions") {
            // uncomment below to test the property
            //modelInstance.totalCompletions shouldBe ("TODO")
        }

    }
}
