/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ca.glong.komodo.core.openapi.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import ca.glong.komodo.core.openapi.models.SetEveryoneUserGroup

class SetEveryoneUserGroupTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of SetEveryoneUserGroup
        //val modelInstance = SetEveryoneUserGroup()

        // to test the property `everyone` - Whether this user group applies to everyone.
        should("test everyone") {
            // uncomment below to test the property
            //modelInstance.everyone shouldBe ("TODO")
        }

        // to test the property `userGroup` - Id or name.
        should("test userGroup") {
            // uncomment below to test the property
            //modelInstance.userGroup shouldBe ("TODO")
        }

    }
}
