/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ca.glong.komodo.core.openapi.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import ca.glong.komodo.core.openapi.models.SlackAlerterEndpoint

class SlackAlerterEndpointTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of SlackAlerterEndpoint
        //val modelInstance = SlackAlerterEndpoint()

        // to test the property `url` - The Slack app webhook url
        should("test url") {
            // uncomment below to test the property
            //modelInstance.url shouldBe ("TODO")
        }

    }
}
