/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ca.glong.komodo.core.openapi.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import ca.glong.komodo.core.openapi.models.StackServiceWithUpdate

class StackServiceWithUpdateTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of StackServiceWithUpdate
        //val modelInstance = StackServiceWithUpdate()

        // to test the property `image` - The service's image
        should("test image") {
            // uncomment below to test the property
            //modelInstance.image shouldBe ("TODO")
        }

        // to test the property `service`
        should("test service") {
            // uncomment below to test the property
            //modelInstance.service shouldBe ("TODO")
        }

        // to test the property `updateAvailable` - Whether there is a newer image available for this service
        should("test updateAvailable") {
            // uncomment below to test the property
            //modelInstance.updateAvailable shouldBe ("TODO")
        }

    }
}
