/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ca.glong.komodo.core.openapi.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import ca.glong.komodo.core.openapi.models.StackFileDependency
import ca.glong.komodo.core.openapi.models.StackFileRequires

class StackFileDependencyTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of StackFileDependency
        //val modelInstance = StackFileDependency()

        // to test the property `path` - Specify the file
        should("test path") {
            // uncomment below to test the property
            //modelInstance.path shouldBe ("TODO")
        }

        // to test the property `requires` - Specify
        should("test requires") {
            // uncomment below to test the property
            //modelInstance.requires shouldBe ("TODO")
        }

        // to test the property `services` - Specify specific service/s
        should("test services") {
            // uncomment below to test the property
            //modelInstance.services shouldBe ("TODO")
        }

    }
}
