/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ca.glong.komodo.core.openapi.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import ca.glong.komodo.core.openapi.models.StackInfo
import ca.glong.komodo.core.openapi.models.FileContents
import ca.glong.komodo.core.openapi.models.StackRemoteFileContents
import ca.glong.komodo.core.openapi.models.StackServiceNames

class StackInfoTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of StackInfo
        //val modelInstance = StackInfo()

        // to test the property `deployedConfig` - The output of `docker compose config`. This is updated whenever Komodo successfully deploys the stack.
        should("test deployedConfig") {
            // uncomment below to test the property
            //modelInstance.deployedConfig shouldBe ("TODO")
        }

        // to test the property `deployedContents` - The deployed compose / additional file contents. This is updated whenever Komodo successfully deploys the stack.
        should("test deployedContents") {
            // uncomment below to test the property
            //modelInstance.deployedContents shouldBe ("TODO")
        }

        // to test the property `deployedHash` - Deployed short commit hash, or null. Only for repo based stacks.
        should("test deployedHash") {
            // uncomment below to test the property
            //modelInstance.deployedHash shouldBe ("TODO")
        }

        // to test the property `deployedMessage` - Deployed commit message, or null. Only for repo based stacks
        should("test deployedMessage") {
            // uncomment below to test the property
            //modelInstance.deployedMessage shouldBe ("TODO")
        }

        // to test the property `deployedProjectName` - The deployed project name. This is updated whenever Komodo successfully deploys the stack. If it is present, Komodo will use it for actions over other options, to ensure control is maintained after changing the project name (there is no rename compose project api).
        should("test deployedProjectName") {
            // uncomment below to test the property
            //modelInstance.deployedProjectName shouldBe ("TODO")
        }

        // to test the property `deployedServices` - The deployed service names. This is updated whenever it is empty, or deployed contents is updated.
        should("test deployedServices") {
            // uncomment below to test the property
            //modelInstance.deployedServices shouldBe ("TODO")
        }

        // to test the property `latestHash` - Latest commit hash, or null
        should("test latestHash") {
            // uncomment below to test the property
            //modelInstance.latestHash shouldBe ("TODO")
        }

        // to test the property `latestMessage` - Latest commit message, or null
        should("test latestMessage") {
            // uncomment below to test the property
            //modelInstance.latestMessage shouldBe ("TODO")
        }

        // to test the property `latestServices` - The latest service names. This is updated whenever the stack cache refreshes, using the latest file contents (either db defined or remote).
        should("test latestServices") {
            // uncomment below to test the property
            //modelInstance.latestServices shouldBe ("TODO")
        }

        // to test the property `missingFiles` - If any of the expected compose / additional files are missing in the repo, they will be stored here.
        should("test missingFiles") {
            // uncomment below to test the property
            //modelInstance.missingFiles shouldBe ("TODO")
        }

        // to test the property `remoteContents` - The remote compose / additional file contents, whether on host or in repo. This is updated whenever Komodo refreshes the stack cache. It will be empty if the file is defined directly in the stack config.
        should("test remoteContents") {
            // uncomment below to test the property
            //modelInstance.remoteContents shouldBe ("TODO")
        }

        // to test the property `remoteErrors` - If there was an error in getting the remote contents, it will be here.
        should("test remoteErrors") {
            // uncomment below to test the property
            //modelInstance.remoteErrors shouldBe ("TODO")
        }

    }
}
