/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ca.glong.komodo.core.openapi.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import ca.glong.komodo.core.openapi.models.StopStack

class StopStackTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of StopStack
        //val modelInstance = StopStack()

        // to test the property `stack` - Id or name
        should("test stack") {
            // uncomment below to test the property
            //modelInstance.stack shouldBe ("TODO")
        }

        // to test the property `services` - Filter to only stop specific services. If empty, will stop all services.
        should("test services") {
            // uncomment below to test the property
            //modelInstance.services shouldBe ("TODO")
        }

        // to test the property `stopTime` - Override the default termination max time.
        should("test stopTime") {
            // uncomment below to test the property
            //modelInstance.stopTime shouldBe ("TODO")
        }

    }
}
