/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ca.glong.komodo.core.openapi.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import ca.glong.komodo.core.openapi.models.SwarmServiceListItem
import ca.glong.komodo.core.openapi.models.SwarmServiceMode
import ca.glong.komodo.core.openapi.models.SwarmState
import ca.glong.komodo.core.openapi.models.TaskSpecRestartPolicyConditionEnum

class SwarmServiceListItemTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of SwarmServiceListItem
        //val modelInstance = SwarmServiceListItem()

        // to test the property `configs` - Attached config names
        should("test configs") {
            // uncomment below to test the property
            //modelInstance.configs shouldBe ("TODO")
        }

        // to test the property `secrets` - Attached secret names
        should("test secrets") {
            // uncomment below to test the property
            //modelInstance.secrets shouldBe ("TODO")
        }

        // to test the property `state` - Swarm service state. - Healthy if all associated tasks match their desired state (or report no desired state) - Unhealthy otherwise  Not included in docker cli return, computed by Komodo
        should("test state") {
            // uncomment below to test the property
            //modelInstance.state shouldBe ("TODO")
        }

        // to test the property `completedTasks` - The number of tasks for a job that are in the Completed state. This field must be cross-referenced with the service type, as the value of 0 may mean the service is not in a job mode, or it may mean the job-mode service has no tasks yet Completed.
        should("test completedTasks") {
            // uncomment below to test the property
            //modelInstance.completedTasks shouldBe ("TODO")
        }

        // to test the property `createdAt`
        should("test createdAt") {
            // uncomment below to test the property
            //modelInstance.createdAt shouldBe ("TODO")
        }

        // to test the property `desiredTasks` - The number of tasks for the service desired to be running. - For replicated services, this is the replica count from the service spec. - For global services, this is computed by taking count of all tasks for the   service with a Desired State other than Shutdown.
        should("test desiredTasks") {
            // uncomment below to test the property
            //modelInstance.desiredTasks shouldBe ("TODO")
        }

        // to test the property `ID`
        should("test ID") {
            // uncomment below to test the property
            //modelInstance.ID shouldBe ("TODO")
        }

        // to test the property `image` - The image associated with service
        should("test image") {
            // uncomment below to test the property
            //modelInstance.image shouldBe ("TODO")
        }

        // to test the property `maxConcurrent` - Max concurrent tasks (in a replicated job mode)
        should("test maxConcurrent") {
            // uncomment below to test the property
            //modelInstance.maxConcurrent shouldBe ("TODO")
        }

        // to test the property `mode` - The service mode.
        should("test mode") {
            // uncomment below to test the property
            //modelInstance.mode shouldBe ("TODO")
        }

        // to test the property `name` - Name of the service.
        should("test name") {
            // uncomment below to test the property
            //modelInstance.name shouldBe ("TODO")
        }

        // to test the property `replicas` - Number of replicas (in a replicated mode)
        should("test replicas") {
            // uncomment below to test the property
            //modelInstance.replicas shouldBe ("TODO")
        }

        // to test the property `restart` - Condition for restart.
        should("test restart") {
            // uncomment below to test the property
            //modelInstance.restart shouldBe ("TODO")
        }

        // to test the property `runningTasks` - The number of tasks for the service currently in the Running state.
        should("test runningTasks") {
            // uncomment below to test the property
            //modelInstance.runningTasks shouldBe ("TODO")
        }

        // to test the property `runtime` - Runtime is the type of runtime specified for the task executor.
        should("test runtime") {
            // uncomment below to test the property
            //modelInstance.runtime shouldBe ("TODO")
        }

        // to test the property `updatedAt`
        should("test updatedAt") {
            // uncomment below to test the property
            //modelInstance.updatedAt shouldBe ("TODO")
        }

    }
}
