/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ca.glong.komodo.core.openapi.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import ca.glong.komodo.core.openapi.models.SwarmConfig
import ca.glong.komodo.core.openapi.models.MaintenanceWindow

class SwarmConfigTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of SwarmConfig
        //val modelInstance = SwarmConfig()

        // to test the property `links` - Configure quick links that are displayed in the resource header
        should("test links") {
            // uncomment below to test the property
            //modelInstance.links shouldBe ("TODO")
        }

        // to test the property `maintenanceWindows` - Scheduled maintenance windows during which alerts will be suppressed.
        should("test maintenanceWindows") {
            // uncomment below to test the property
            //modelInstance.maintenanceWindows shouldBe ("TODO")
        }

        // to test the property `sendUnhealthyAlerts` - Whether to send alerts about the swarm health.
        should("test sendUnhealthyAlerts") {
            // uncomment below to test the property
            //modelInstance.sendUnhealthyAlerts shouldBe ("TODO")
        }

        // to test the property `serverIds` - The Servers which are swarm manager nodes. If a Server is not reachable or gives error, tries the next Server.
        should("test serverIds") {
            // uncomment below to test the property
            //modelInstance.serverIds shouldBe ("TODO")
        }

    }
}
