/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ca.glong.komodo.core.openapi.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import ca.glong.komodo.core.openapi.models.SystemInformation

class SystemInformationTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of SystemInformation
        //val modelInstance = SystemInformation()

        // to test the property `cpuBrand` - The CPU's brand
        should("test cpuBrand") {
            // uncomment below to test the property
            //modelInstance.cpuBrand shouldBe ("TODO")
        }

        // to test the property `coreCount` - Physical core count
        should("test coreCount") {
            // uncomment below to test the property
            //modelInstance.coreCount shouldBe ("TODO")
        }

        // to test the property `hostName` - System hostname based off DNS
        should("test hostName") {
            // uncomment below to test the property
            //modelInstance.hostName shouldBe ("TODO")
        }

        // to test the property `kernel` - System's kernel version
        should("test kernel") {
            // uncomment below to test the property
            //modelInstance.kernel shouldBe ("TODO")
        }

        // to test the property `name` - The system name
        should("test name") {
            // uncomment below to test the property
            //modelInstance.name shouldBe ("TODO")
        }

        // to test the property `os` - The system long os version
        should("test os") {
            // uncomment below to test the property
            //modelInstance.os shouldBe ("TODO")
        }

    }
}
