/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ca.glong.komodo.core.openapi.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import ca.glong.komodo.core.openapi.models.SystemLoadAverage

class SystemLoadAverageTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of SystemLoadAverage
        //val modelInstance = SystemLoadAverage()

        // to test the property `fifteen` - 15m load average
        should("test fifteen") {
            // uncomment below to test the property
            //modelInstance.fifteen shouldBe ("TODO")
        }

        // to test the property `five` - 5m load average
        should("test five") {
            // uncomment below to test the property
            //modelInstance.five shouldBe ("TODO")
        }

        // to test the property `one` - 1m load average
        should("test one") {
            // uncomment below to test the property
            //modelInstance.one shouldBe ("TODO")
        }

    }
}
