/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ca.glong.komodo.core.openapi.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import ca.glong.komodo.core.openapi.models.TaskSpecContainerSpecPrivilegesCredentialSpec

class TaskSpecContainerSpecPrivilegesCredentialSpecTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of TaskSpecContainerSpecPrivilegesCredentialSpec
        //val modelInstance = TaskSpecContainerSpecPrivilegesCredentialSpec()

        // to test the property `config` - Load credential spec from a Swarm Config with the given ID. The specified config must also be present in the Configs field with the Runtime property set.  <p><br /></p>   > **Note**: `CredentialSpec.File`, `CredentialSpec.Registry`, > and `CredentialSpec.Config` are mutually exclusive.
        should("test config") {
            // uncomment below to test the property
            //modelInstance.config shouldBe ("TODO")
        }

        // to test the property `file` - Load credential spec from this file. The file is read by the daemon, and must be present in the `CredentialSpecs` subdirectory in the docker data directory, which defaults to `C:\\\\ProgramData\\\\Docker\\\\` on Windows.  For example, specifying `spec.json` loads `C:\\\\ProgramData\\\\Docker\\\\CredentialSpecs\\\\spec.json`.  <p><br /></p>  > **Note**: `CredentialSpec.File`, `CredentialSpec.Registry`, > and `CredentialSpec.Config` are mutually exclusive.
        should("test file") {
            // uncomment below to test the property
            //modelInstance.file shouldBe ("TODO")
        }

        // to test the property `registry` - Load credential spec from this value in the Windows registry. The specified registry value must be located in:  `HKLM\\\\SOFTWARE\\\\Microsoft\\\\Windows NT\\\\CurrentVersion\\\\Virtualization\\\\Containers\\\\CredentialSpecs`  <p><br /></p>   > **Note**: `CredentialSpec.File`, `CredentialSpec.Registry`, > and `CredentialSpec.Config` are mutually exclusive.
        should("test registry") {
            // uncomment below to test the property
            //modelInstance.registry shouldBe ("TODO")
        }

    }
}
