/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ca.glong.komodo.core.openapi.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import ca.glong.komodo.core.openapi.models.TaskSpecContainerSpecDnsConfig

class TaskSpecContainerSpecDnsConfigTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of TaskSpecContainerSpecDnsConfig
        //val modelInstance = TaskSpecContainerSpecDnsConfig()

        // to test the property `nameservers` - The IP addresses of the name servers.
        should("test nameservers") {
            // uncomment below to test the property
            //modelInstance.nameservers shouldBe ("TODO")
        }

        // to test the property `options` - A list of internal resolver variables to be modified (e.g., `debug`, `ndots:3`, etc.).
        should("test options") {
            // uncomment below to test the property
            //modelInstance.options shouldBe ("TODO")
        }

        // to test the property `search` - A search list for host-name lookup.
        should("test search") {
            // uncomment below to test the property
            //modelInstance.search shouldBe ("TODO")
        }

    }
}
