/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ca.glong.komodo.core.openapi.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import ca.glong.komodo.core.openapi.models.TaskSpecNetworkAttachmentSpec

class TaskSpecNetworkAttachmentSpecTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of TaskSpecNetworkAttachmentSpec
        //val modelInstance = TaskSpecNetworkAttachmentSpec()

        // to test the property `containerID` - ID of the container represented by this task
        should("test containerID") {
            // uncomment below to test the property
            //modelInstance.containerID shouldBe ("TODO")
        }

    }
}
