/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ca.glong.komodo.core.openapi.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import ca.glong.komodo.core.openapi.models.TerminalTargetOneOf2Params

class TerminalTargetOneOf2ParamsTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of TerminalTargetOneOf2Params
        //val modelInstance = TerminalTargetOneOf2Params()

        // to test the property `stack`
        should("test stack") {
            // uncomment below to test the property
            //modelInstance.stack shouldBe ("TODO")
        }

        // to test the property `service`
        should("test service") {
            // uncomment below to test the property
            //modelInstance.service shouldBe ("TODO")
        }

    }
}
