/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ca.glong.komodo.core.openapi.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import ca.glong.komodo.core.openapi.models.ThrottleDevice

class ThrottleDeviceTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ThrottleDevice
        //val modelInstance = ThrottleDevice()

        // to test the property `path` - Device path
        should("test path") {
            // uncomment below to test the property
            //modelInstance.path shouldBe ("TODO")
        }

        // to test the property `rate` - Rate
        should("test rate") {
            // uncomment below to test the property
            //modelInstance.rate shouldBe ("TODO")
        }

    }
}
