/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ca.glong.komodo.core.openapi.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import ca.glong.komodo.core.openapi.models.TlsInfo

class TlsInfoTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of TlsInfo
        //val modelInstance = TlsInfo()

        // to test the property `certIssuerPublicKey` - The base64-url-safe-encoded raw public key bytes of the issuer.
        should("test certIssuerPublicKey") {
            // uncomment below to test the property
            //modelInstance.certIssuerPublicKey shouldBe ("TODO")
        }

        // to test the property `certIssuerSubject` - The base64-url-safe-encoded raw subject bytes of the issuer.
        should("test certIssuerSubject") {
            // uncomment below to test the property
            //modelInstance.certIssuerSubject shouldBe ("TODO")
        }

        // to test the property `trustRoot` - The root CA certificate(s) that are used to validate leaf TLS certificates.
        should("test trustRoot") {
            // uncomment below to test the property
            //modelInstance.trustRoot shouldBe ("TODO")
        }

    }
}
