/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ca.glong.komodo.core.openapi.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import ca.glong.komodo.core.openapi.models.UpdateExternalSkip2fa

class UpdateExternalSkip2faTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of UpdateExternalSkip2fa
        //val modelInstance = UpdateExternalSkip2fa()

        // to test the property `externalSkip2fa` - Whether user skips 2fa when using external login method.
        should("test externalSkip2fa") {
            // uncomment below to test the property
            //modelInstance.externalSkip2fa shouldBe ("TODO")
        }

    }
}
