/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ca.glong.komodo.core.openapi.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import ca.glong.komodo.core.openapi.models.UserPasskeyConfig
import ca.glong.komodo.core.openapi.models.OneOfLessThanGreaterThan

class UserPasskeyConfigTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of UserPasskeyConfig
        //val modelInstance = UserPasskeyConfig()

        // to test the property `createdAt` - Unix timestamp in milliseconds when key created
        should("test createdAt") {
            // uncomment below to test the property
            //modelInstance.createdAt shouldBe ("TODO")
        }

        // to test the property `passkey`
        should("test passkey") {
            // uncomment below to test the property
            //modelInstance.passkey shouldBe ("TODO")
        }

    }
}
