/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ca.glong.komodo.core.openapi.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import ca.glong.komodo.core.openapi.models.UserConfigOneOf1Data

class UserConfigOneOf1DataTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of UserConfigOneOf1Data
        //val modelInstance = UserConfigOneOf1Data()

        // to test the property `avatar`
        should("test avatar") {
            // uncomment below to test the property
            //modelInstance.avatar shouldBe ("TODO")
        }

        // to test the property `googleId`
        should("test googleId") {
            // uncomment below to test the property
            //modelInstance.googleId shouldBe ("TODO")
        }

    }
}
