/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ca.glong.komodo.core.openapi.models

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import ca.glong.komodo.core.openapi.models.WriteSyncFileContents

class WriteSyncFileContentsTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of WriteSyncFileContents
        //val modelInstance = WriteSyncFileContents()

        // to test the property `contents` - The contents to write.
        should("test contents") {
            // uncomment below to test the property
            //modelInstance.contents shouldBe ("TODO")
        }

        // to test the property `filePath` - The file path relative to the resource path.
        should("test filePath") {
            // uncomment below to test the property
            //modelInstance.filePath shouldBe ("TODO")
        }

        // to test the property `resourcePath` - If this file was under a resource folder, this will be the folder. Otherwise, it should be empty string.
        should("test resourcePath") {
            // uncomment below to test the property
            //modelInstance.resourcePath shouldBe ("TODO")
        }

        // to test the property `sync` - The name or id of the target Sync.
        should("test sync") {
            // uncomment below to test the property
            //modelInstance.sync shouldBe ("TODO")
        }

    }
}
