/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ca.glong.komodo.core.openapi.apis

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import ca.glong.komodo.core.openapi.apis.ExecuteApi
import ca.glong.komodo.core.openapi.models.BatchBuildRepo
import ca.glong.komodo.core.openapi.models.BatchCloneRepo
import ca.glong.komodo.core.openapi.models.BatchDeploy
import ca.glong.komodo.core.openapi.models.BatchDeployStack
import ca.glong.komodo.core.openapi.models.BatchDeployStackIfChanged
import ca.glong.komodo.core.openapi.models.BatchDestroyDeployment
import ca.glong.komodo.core.openapi.models.BatchDestroyStack
import ca.glong.komodo.core.openapi.models.BatchPullRepo
import ca.glong.komodo.core.openapi.models.BatchPullStack
import ca.glong.komodo.core.openapi.models.BatchRunAction
import ca.glong.komodo.core.openapi.models.BatchRunBuild
import ca.glong.komodo.core.openapi.models.BatchRunProcedure
import ca.glong.komodo.core.openapi.models.BuildRepo
import ca.glong.komodo.core.openapi.models.CancelBuild
import ca.glong.komodo.core.openapi.models.CancelRepoBuild
import ca.glong.komodo.core.openapi.models.CloneRepo
import ca.glong.komodo.core.openapi.models.CreateSwarmConfig
import ca.glong.komodo.core.openapi.models.CreateSwarmSecret
import ca.glong.komodo.core.openapi.models.DeleteImage
import ca.glong.komodo.core.openapi.models.DeleteNetwork
import ca.glong.komodo.core.openapi.models.DeleteVolume
import ca.glong.komodo.core.openapi.models.Deploy
import ca.glong.komodo.core.openapi.models.DeployStack
import ca.glong.komodo.core.openapi.models.DeployStackIfChanged
import ca.glong.komodo.core.openapi.models.DestroyContainer
import ca.glong.komodo.core.openapi.models.DestroyDeployment
import ca.glong.komodo.core.openapi.models.DestroyStack
import ca.glong.komodo.core.openapi.models.GlobalAutoUpdate
import ca.glong.komodo.core.openapi.models.PauseAllContainers
import ca.glong.komodo.core.openapi.models.PauseContainer
import ca.glong.komodo.core.openapi.models.PauseDeployment
import ca.glong.komodo.core.openapi.models.PauseStack
import ca.glong.komodo.core.openapi.models.PruneBuildx
import ca.glong.komodo.core.openapi.models.PruneContainers
import ca.glong.komodo.core.openapi.models.PruneDockerBuilders
import ca.glong.komodo.core.openapi.models.PruneImages
import ca.glong.komodo.core.openapi.models.PruneNetworks
import ca.glong.komodo.core.openapi.models.PruneSystem
import ca.glong.komodo.core.openapi.models.PruneVolumes
import ca.glong.komodo.core.openapi.models.PullDeployment
import ca.glong.komodo.core.openapi.models.PullRepo
import ca.glong.komodo.core.openapi.models.PullStack
import ca.glong.komodo.core.openapi.models.RemoveSwarmConfigs
import ca.glong.komodo.core.openapi.models.RemoveSwarmNodes
import ca.glong.komodo.core.openapi.models.RemoveSwarmSecrets
import ca.glong.komodo.core.openapi.models.RemoveSwarmServices
import ca.glong.komodo.core.openapi.models.RemoveSwarmStacks
import ca.glong.komodo.core.openapi.models.RestartAllContainers
import ca.glong.komodo.core.openapi.models.RestartContainer
import ca.glong.komodo.core.openapi.models.RestartDeployment
import ca.glong.komodo.core.openapi.models.RestartStack
import ca.glong.komodo.core.openapi.models.RotateCoreKeys
import ca.glong.komodo.core.openapi.models.RotateSwarmConfig
import ca.glong.komodo.core.openapi.models.RotateSwarmSecret
import ca.glong.komodo.core.openapi.models.RunAction
import ca.glong.komodo.core.openapi.models.RunBuild
import ca.glong.komodo.core.openapi.models.RunProcedure
import ca.glong.komodo.core.openapi.models.RunStackService
import ca.glong.komodo.core.openapi.models.RunSync
import ca.glong.komodo.core.openapi.models.SendAlert
import ca.glong.komodo.core.openapi.models.StartAllContainers
import ca.glong.komodo.core.openapi.models.StartContainer
import ca.glong.komodo.core.openapi.models.StartDeployment
import ca.glong.komodo.core.openapi.models.StartStack
import ca.glong.komodo.core.openapi.models.StopAllContainers
import ca.glong.komodo.core.openapi.models.StopContainer
import ca.glong.komodo.core.openapi.models.StopDeployment
import ca.glong.komodo.core.openapi.models.StopStack
import ca.glong.komodo.core.openapi.models.TestAlerter
import ca.glong.komodo.core.openapi.models.UnpauseAllContainers
import ca.glong.komodo.core.openapi.models.UnpauseContainer
import ca.glong.komodo.core.openapi.models.UnpauseDeployment
import ca.glong.komodo.core.openapi.models.UnpauseStack
import ca.glong.komodo.core.openapi.models.Update
import ca.glong.komodo.core.openapi.models.VecInner

class ExecuteApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of ExecuteApi
        //val apiInstance = ExecuteApi()

        // to test backupCoreDatabase
        should("test backupCoreDatabase") {
            // uncomment below to test backupCoreDatabase
            //val body : kotlin.String = Object // kotlin.String | 
            //val result : Update = apiInstance.backupCoreDatabase(body)
            //result shouldBe ("TODO")
        }

        // to test batchBuildRepo
        should("test batchBuildRepo") {
            // uncomment below to test batchBuildRepo
            //val batchBuildRepo : BatchBuildRepo =  // BatchBuildRepo | 
            //val result : kotlin.collections.List<VecInner> = apiInstance.batchBuildRepo(batchBuildRepo)
            //result shouldBe ("TODO")
        }

        // to test batchCloneRepo
        should("test batchCloneRepo") {
            // uncomment below to test batchCloneRepo
            //val batchCloneRepo : BatchCloneRepo =  // BatchCloneRepo | 
            //val result : kotlin.collections.List<VecInner> = apiInstance.batchCloneRepo(batchCloneRepo)
            //result shouldBe ("TODO")
        }

        // to test batchDeploy
        should("test batchDeploy") {
            // uncomment below to test batchDeploy
            //val batchDeploy : BatchDeploy =  // BatchDeploy | 
            //val result : kotlin.collections.List<VecInner> = apiInstance.batchDeploy(batchDeploy)
            //result shouldBe ("TODO")
        }

        // to test batchDeployStack
        should("test batchDeployStack") {
            // uncomment below to test batchDeployStack
            //val batchDeployStack : BatchDeployStack =  // BatchDeployStack | 
            //val result : kotlin.collections.List<VecInner> = apiInstance.batchDeployStack(batchDeployStack)
            //result shouldBe ("TODO")
        }

        // to test batchDeployStackIfChanged
        should("test batchDeployStackIfChanged") {
            // uncomment below to test batchDeployStackIfChanged
            //val batchDeployStackIfChanged : BatchDeployStackIfChanged =  // BatchDeployStackIfChanged | 
            //val result : kotlin.collections.List<VecInner> = apiInstance.batchDeployStackIfChanged(batchDeployStackIfChanged)
            //result shouldBe ("TODO")
        }

        // to test batchDestroyDeployment
        should("test batchDestroyDeployment") {
            // uncomment below to test batchDestroyDeployment
            //val batchDestroyDeployment : BatchDestroyDeployment =  // BatchDestroyDeployment | 
            //val result : kotlin.collections.List<VecInner> = apiInstance.batchDestroyDeployment(batchDestroyDeployment)
            //result shouldBe ("TODO")
        }

        // to test batchDestroyStack
        should("test batchDestroyStack") {
            // uncomment below to test batchDestroyStack
            //val batchDestroyStack : BatchDestroyStack =  // BatchDestroyStack | 
            //val result : kotlin.collections.List<VecInner> = apiInstance.batchDestroyStack(batchDestroyStack)
            //result shouldBe ("TODO")
        }

        // to test batchPullRepo
        should("test batchPullRepo") {
            // uncomment below to test batchPullRepo
            //val batchPullRepo : BatchPullRepo =  // BatchPullRepo | 
            //val result : kotlin.collections.List<VecInner> = apiInstance.batchPullRepo(batchPullRepo)
            //result shouldBe ("TODO")
        }

        // to test batchPullStack
        should("test batchPullStack") {
            // uncomment below to test batchPullStack
            //val batchPullStack : BatchPullStack =  // BatchPullStack | 
            //val result : kotlin.collections.List<VecInner> = apiInstance.batchPullStack(batchPullStack)
            //result shouldBe ("TODO")
        }

        // to test batchRunAction
        should("test batchRunAction") {
            // uncomment below to test batchRunAction
            //val batchRunAction : BatchRunAction =  // BatchRunAction | 
            //val result : kotlin.collections.List<VecInner> = apiInstance.batchRunAction(batchRunAction)
            //result shouldBe ("TODO")
        }

        // to test batchRunBuild
        should("test batchRunBuild") {
            // uncomment below to test batchRunBuild
            //val batchRunBuild : BatchRunBuild =  // BatchRunBuild | 
            //val result : kotlin.collections.List<VecInner> = apiInstance.batchRunBuild(batchRunBuild)
            //result shouldBe ("TODO")
        }

        // to test batchRunProcedure
        should("test batchRunProcedure") {
            // uncomment below to test batchRunProcedure
            //val batchRunProcedure : BatchRunProcedure =  // BatchRunProcedure | 
            //val result : kotlin.collections.List<VecInner> = apiInstance.batchRunProcedure(batchRunProcedure)
            //result shouldBe ("TODO")
        }

        // to test buildRepo
        should("test buildRepo") {
            // uncomment below to test buildRepo
            //val buildRepo : BuildRepo =  // BuildRepo | 
            //val result : Update = apiInstance.buildRepo(buildRepo)
            //result shouldBe ("TODO")
        }

        // to test cancelBuild
        should("test cancelBuild") {
            // uncomment below to test cancelBuild
            //val cancelBuild : CancelBuild =  // CancelBuild | 
            //val result : Update = apiInstance.cancelBuild(cancelBuild)
            //result shouldBe ("TODO")
        }

        // to test cancelRepoBuild
        should("test cancelRepoBuild") {
            // uncomment below to test cancelRepoBuild
            //val cancelRepoBuild : CancelRepoBuild =  // CancelRepoBuild | 
            //val result : Update = apiInstance.cancelRepoBuild(cancelRepoBuild)
            //result shouldBe ("TODO")
        }

        // to test clearRepoCache
        should("test clearRepoCache") {
            // uncomment below to test clearRepoCache
            //val body : kotlin.String = Object // kotlin.String | 
            //val result : Update = apiInstance.clearRepoCache(body)
            //result shouldBe ("TODO")
        }

        // to test cloneRepo
        should("test cloneRepo") {
            // uncomment below to test cloneRepo
            //val cloneRepo : CloneRepo =  // CloneRepo | 
            //val result : Update = apiInstance.cloneRepo(cloneRepo)
            //result shouldBe ("TODO")
        }

        // to test createSwarmConfig
        should("test createSwarmConfig") {
            // uncomment below to test createSwarmConfig
            //val createSwarmConfig : CreateSwarmConfig =  // CreateSwarmConfig | 
            //val result : Update = apiInstance.createSwarmConfig(createSwarmConfig)
            //result shouldBe ("TODO")
        }

        // to test createSwarmSecret
        should("test createSwarmSecret") {
            // uncomment below to test createSwarmSecret
            //val createSwarmSecret : CreateSwarmSecret =  // CreateSwarmSecret | 
            //val result : Update = apiInstance.createSwarmSecret(createSwarmSecret)
            //result shouldBe ("TODO")
        }

        // to test deleteImage
        should("test deleteImage") {
            // uncomment below to test deleteImage
            //val deleteImage : DeleteImage =  // DeleteImage | 
            //val result : Update = apiInstance.deleteImage(deleteImage)
            //result shouldBe ("TODO")
        }

        // to test deleteNetwork
        should("test deleteNetwork") {
            // uncomment below to test deleteNetwork
            //val deleteNetwork : DeleteNetwork =  // DeleteNetwork | 
            //val result : Update = apiInstance.deleteNetwork(deleteNetwork)
            //result shouldBe ("TODO")
        }

        // to test deleteVolume
        should("test deleteVolume") {
            // uncomment below to test deleteVolume
            //val deleteVolume : DeleteVolume =  // DeleteVolume | 
            //val result : Update = apiInstance.deleteVolume(deleteVolume)
            //result shouldBe ("TODO")
        }

        // to test deploy
        should("test deploy") {
            // uncomment below to test deploy
            //val deploy : Deploy =  // Deploy | 
            //val result : Update = apiInstance.deploy(deploy)
            //result shouldBe ("TODO")
        }

        // to test deployStack
        should("test deployStack") {
            // uncomment below to test deployStack
            //val deployStack : DeployStack =  // DeployStack | 
            //val result : Update = apiInstance.deployStack(deployStack)
            //result shouldBe ("TODO")
        }

        // to test deployStackIfChanged
        should("test deployStackIfChanged") {
            // uncomment below to test deployStackIfChanged
            //val deployStackIfChanged : DeployStackIfChanged =  // DeployStackIfChanged | 
            //val result : Update = apiInstance.deployStackIfChanged(deployStackIfChanged)
            //result shouldBe ("TODO")
        }

        // to test destroyContainer
        should("test destroyContainer") {
            // uncomment below to test destroyContainer
            //val destroyContainer : DestroyContainer =  // DestroyContainer | 
            //val result : Update = apiInstance.destroyContainer(destroyContainer)
            //result shouldBe ("TODO")
        }

        // to test destroyDeployment
        should("test destroyDeployment") {
            // uncomment below to test destroyDeployment
            //val destroyDeployment : DestroyDeployment =  // DestroyDeployment | 
            //val result : Update = apiInstance.destroyDeployment(destroyDeployment)
            //result shouldBe ("TODO")
        }

        // to test destroyStack
        should("test destroyStack") {
            // uncomment below to test destroyStack
            //val destroyStack : DestroyStack =  // DestroyStack | 
            //val result : Update = apiInstance.destroyStack(destroyStack)
            //result shouldBe ("TODO")
        }

        // to test globalAutoUpdate
        should("test globalAutoUpdate") {
            // uncomment below to test globalAutoUpdate
            //val globalAutoUpdate : GlobalAutoUpdate =  // GlobalAutoUpdate | 
            //val result : Update = apiInstance.globalAutoUpdate(globalAutoUpdate)
            //result shouldBe ("TODO")
        }

        // to test pauseAllContainers
        should("test pauseAllContainers") {
            // uncomment below to test pauseAllContainers
            //val pauseAllContainers : PauseAllContainers =  // PauseAllContainers | 
            //val result : Update = apiInstance.pauseAllContainers(pauseAllContainers)
            //result shouldBe ("TODO")
        }

        // to test pauseContainer
        should("test pauseContainer") {
            // uncomment below to test pauseContainer
            //val pauseContainer : PauseContainer =  // PauseContainer | 
            //val result : Update = apiInstance.pauseContainer(pauseContainer)
            //result shouldBe ("TODO")
        }

        // to test pauseDeployment
        should("test pauseDeployment") {
            // uncomment below to test pauseDeployment
            //val pauseDeployment : PauseDeployment =  // PauseDeployment | 
            //val result : Update = apiInstance.pauseDeployment(pauseDeployment)
            //result shouldBe ("TODO")
        }

        // to test pauseStack
        should("test pauseStack") {
            // uncomment below to test pauseStack
            //val pauseStack : PauseStack =  // PauseStack | 
            //val result : Update = apiInstance.pauseStack(pauseStack)
            //result shouldBe ("TODO")
        }

        // to test pruneBuildx
        should("test pruneBuildx") {
            // uncomment below to test pruneBuildx
            //val pruneBuildx : PruneBuildx =  // PruneBuildx | 
            //val result : Update = apiInstance.pruneBuildx(pruneBuildx)
            //result shouldBe ("TODO")
        }

        // to test pruneContainers
        should("test pruneContainers") {
            // uncomment below to test pruneContainers
            //val pruneContainers : PruneContainers =  // PruneContainers | 
            //val result : Update = apiInstance.pruneContainers(pruneContainers)
            //result shouldBe ("TODO")
        }

        // to test pruneDockerBuilders
        should("test pruneDockerBuilders") {
            // uncomment below to test pruneDockerBuilders
            //val pruneDockerBuilders : PruneDockerBuilders =  // PruneDockerBuilders | 
            //val result : Update = apiInstance.pruneDockerBuilders(pruneDockerBuilders)
            //result shouldBe ("TODO")
        }

        // to test pruneImages
        should("test pruneImages") {
            // uncomment below to test pruneImages
            //val pruneImages : PruneImages =  // PruneImages | 
            //val result : Update = apiInstance.pruneImages(pruneImages)
            //result shouldBe ("TODO")
        }

        // to test pruneNetworks
        should("test pruneNetworks") {
            // uncomment below to test pruneNetworks
            //val pruneNetworks : PruneNetworks =  // PruneNetworks | 
            //val result : Update = apiInstance.pruneNetworks(pruneNetworks)
            //result shouldBe ("TODO")
        }

        // to test pruneSystem
        should("test pruneSystem") {
            // uncomment below to test pruneSystem
            //val pruneSystem : PruneSystem =  // PruneSystem | 
            //val result : Update = apiInstance.pruneSystem(pruneSystem)
            //result shouldBe ("TODO")
        }

        // to test pruneVolumes
        should("test pruneVolumes") {
            // uncomment below to test pruneVolumes
            //val pruneVolumes : PruneVolumes =  // PruneVolumes | 
            //val result : Update = apiInstance.pruneVolumes(pruneVolumes)
            //result shouldBe ("TODO")
        }

        // to test pullDeployment
        should("test pullDeployment") {
            // uncomment below to test pullDeployment
            //val pullDeployment : PullDeployment =  // PullDeployment | 
            //val result : Update = apiInstance.pullDeployment(pullDeployment)
            //result shouldBe ("TODO")
        }

        // to test pullRepo
        should("test pullRepo") {
            // uncomment below to test pullRepo
            //val pullRepo : PullRepo =  // PullRepo | 
            //val result : Update = apiInstance.pullRepo(pullRepo)
            //result shouldBe ("TODO")
        }

        // to test pullStack
        should("test pullStack") {
            // uncomment below to test pullStack
            //val pullStack : PullStack =  // PullStack | 
            //val result : Update = apiInstance.pullStack(pullStack)
            //result shouldBe ("TODO")
        }

        // to test removeSwarmConfigs
        should("test removeSwarmConfigs") {
            // uncomment below to test removeSwarmConfigs
            //val removeSwarmConfigs : RemoveSwarmConfigs =  // RemoveSwarmConfigs | 
            //val result : Update = apiInstance.removeSwarmConfigs(removeSwarmConfigs)
            //result shouldBe ("TODO")
        }

        // to test removeSwarmNodes
        should("test removeSwarmNodes") {
            // uncomment below to test removeSwarmNodes
            //val removeSwarmNodes : RemoveSwarmNodes =  // RemoveSwarmNodes | 
            //val result : Update = apiInstance.removeSwarmNodes(removeSwarmNodes)
            //result shouldBe ("TODO")
        }

        // to test removeSwarmSecrets
        should("test removeSwarmSecrets") {
            // uncomment below to test removeSwarmSecrets
            //val removeSwarmSecrets : RemoveSwarmSecrets =  // RemoveSwarmSecrets | 
            //val result : Update = apiInstance.removeSwarmSecrets(removeSwarmSecrets)
            //result shouldBe ("TODO")
        }

        // to test removeSwarmServices
        should("test removeSwarmServices") {
            // uncomment below to test removeSwarmServices
            //val removeSwarmServices : RemoveSwarmServices =  // RemoveSwarmServices | 
            //val result : Update = apiInstance.removeSwarmServices(removeSwarmServices)
            //result shouldBe ("TODO")
        }

        // to test removeSwarmStacks
        should("test removeSwarmStacks") {
            // uncomment below to test removeSwarmStacks
            //val removeSwarmStacks : RemoveSwarmStacks =  // RemoveSwarmStacks | 
            //val result : Update = apiInstance.removeSwarmStacks(removeSwarmStacks)
            //result shouldBe ("TODO")
        }

        // to test restartAllContainers
        should("test restartAllContainers") {
            // uncomment below to test restartAllContainers
            //val restartAllContainers : RestartAllContainers =  // RestartAllContainers | 
            //val result : Update = apiInstance.restartAllContainers(restartAllContainers)
            //result shouldBe ("TODO")
        }

        // to test restartContainer
        should("test restartContainer") {
            // uncomment below to test restartContainer
            //val restartContainer : RestartContainer =  // RestartContainer | 
            //val result : Update = apiInstance.restartContainer(restartContainer)
            //result shouldBe ("TODO")
        }

        // to test restartDeployment
        should("test restartDeployment") {
            // uncomment below to test restartDeployment
            //val restartDeployment : RestartDeployment =  // RestartDeployment | 
            //val result : Update = apiInstance.restartDeployment(restartDeployment)
            //result shouldBe ("TODO")
        }

        // to test restartStack
        should("test restartStack") {
            // uncomment below to test restartStack
            //val restartStack : RestartStack =  // RestartStack | 
            //val result : Update = apiInstance.restartStack(restartStack)
            //result shouldBe ("TODO")
        }

        // to test rotateAllServerKeys
        should("test rotateAllServerKeys") {
            // uncomment below to test rotateAllServerKeys
            //val body : kotlin.String = Object // kotlin.String | 
            //val result : Update = apiInstance.rotateAllServerKeys(body)
            //result shouldBe ("TODO")
        }

        // to test rotateCoreKeys
        should("test rotateCoreKeys") {
            // uncomment below to test rotateCoreKeys
            //val rotateCoreKeys : RotateCoreKeys =  // RotateCoreKeys | 
            //val result : Update = apiInstance.rotateCoreKeys(rotateCoreKeys)
            //result shouldBe ("TODO")
        }

        // to test rotateSwarmConfig
        should("test rotateSwarmConfig") {
            // uncomment below to test rotateSwarmConfig
            //val rotateSwarmConfig : RotateSwarmConfig =  // RotateSwarmConfig | 
            //val result : Update = apiInstance.rotateSwarmConfig(rotateSwarmConfig)
            //result shouldBe ("TODO")
        }

        // to test rotateSwarmSecret
        should("test rotateSwarmSecret") {
            // uncomment below to test rotateSwarmSecret
            //val rotateSwarmSecret : RotateSwarmSecret =  // RotateSwarmSecret | 
            //val result : Update = apiInstance.rotateSwarmSecret(rotateSwarmSecret)
            //result shouldBe ("TODO")
        }

        // to test runAction
        should("test runAction") {
            // uncomment below to test runAction
            //val runAction : RunAction =  // RunAction | 
            //val result : Update = apiInstance.runAction(runAction)
            //result shouldBe ("TODO")
        }

        // to test runBuild
        should("test runBuild") {
            // uncomment below to test runBuild
            //val runBuild : RunBuild =  // RunBuild | 
            //val result : Update = apiInstance.runBuild(runBuild)
            //result shouldBe ("TODO")
        }

        // to test runProcedure
        should("test runProcedure") {
            // uncomment below to test runProcedure
            //val runProcedure : RunProcedure =  // RunProcedure | 
            //val result : Update = apiInstance.runProcedure(runProcedure)
            //result shouldBe ("TODO")
        }

        // to test runStackService
        should("test runStackService") {
            // uncomment below to test runStackService
            //val runStackService : RunStackService =  // RunStackService | 
            //val result : Update = apiInstance.runStackService(runStackService)
            //result shouldBe ("TODO")
        }

        // to test runSync
        should("test runSync") {
            // uncomment below to test runSync
            //val runSync : RunSync =  // RunSync | 
            //val result : Update = apiInstance.runSync(runSync)
            //result shouldBe ("TODO")
        }

        // to test sendAlert
        should("test sendAlert") {
            // uncomment below to test sendAlert
            //val sendAlert : SendAlert =  // SendAlert | 
            //val result : Update = apiInstance.sendAlert(sendAlert)
            //result shouldBe ("TODO")
        }

        // to test startAllContainers
        should("test startAllContainers") {
            // uncomment below to test startAllContainers
            //val startAllContainers : StartAllContainers =  // StartAllContainers | 
            //val result : Update = apiInstance.startAllContainers(startAllContainers)
            //result shouldBe ("TODO")
        }

        // to test startContainer
        should("test startContainer") {
            // uncomment below to test startContainer
            //val startContainer : StartContainer =  // StartContainer | 
            //val result : Update = apiInstance.startContainer(startContainer)
            //result shouldBe ("TODO")
        }

        // to test startDeployment
        should("test startDeployment") {
            // uncomment below to test startDeployment
            //val startDeployment : StartDeployment =  // StartDeployment | 
            //val result : Update = apiInstance.startDeployment(startDeployment)
            //result shouldBe ("TODO")
        }

        // to test startStack
        should("test startStack") {
            // uncomment below to test startStack
            //val startStack : StartStack =  // StartStack | 
            //val result : Update = apiInstance.startStack(startStack)
            //result shouldBe ("TODO")
        }

        // to test stopAllContainers
        should("test stopAllContainers") {
            // uncomment below to test stopAllContainers
            //val stopAllContainers : StopAllContainers =  // StopAllContainers | 
            //val result : Update = apiInstance.stopAllContainers(stopAllContainers)
            //result shouldBe ("TODO")
        }

        // to test stopContainer
        should("test stopContainer") {
            // uncomment below to test stopContainer
            //val stopContainer : StopContainer =  // StopContainer | 
            //val result : Update = apiInstance.stopContainer(stopContainer)
            //result shouldBe ("TODO")
        }

        // to test stopDeployment
        should("test stopDeployment") {
            // uncomment below to test stopDeployment
            //val stopDeployment : StopDeployment =  // StopDeployment | 
            //val result : Update = apiInstance.stopDeployment(stopDeployment)
            //result shouldBe ("TODO")
        }

        // to test stopStack
        should("test stopStack") {
            // uncomment below to test stopStack
            //val stopStack : StopStack =  // StopStack | 
            //val result : Update = apiInstance.stopStack(stopStack)
            //result shouldBe ("TODO")
        }

        // to test testAlerter
        should("test testAlerter") {
            // uncomment below to test testAlerter
            //val testAlerter : TestAlerter =  // TestAlerter | 
            //val result : Update = apiInstance.testAlerter(testAlerter)
            //result shouldBe ("TODO")
        }

        // to test unpauseAllContainers
        should("test unpauseAllContainers") {
            // uncomment below to test unpauseAllContainers
            //val unpauseAllContainers : UnpauseAllContainers =  // UnpauseAllContainers | 
            //val result : Update = apiInstance.unpauseAllContainers(unpauseAllContainers)
            //result shouldBe ("TODO")
        }

        // to test unpauseContainer
        should("test unpauseContainer") {
            // uncomment below to test unpauseContainer
            //val unpauseContainer : UnpauseContainer =  // UnpauseContainer | 
            //val result : Update = apiInstance.unpauseContainer(unpauseContainer)
            //result shouldBe ("TODO")
        }

        // to test unpauseDeployment
        should("test unpauseDeployment") {
            // uncomment below to test unpauseDeployment
            //val unpauseDeployment : UnpauseDeployment =  // UnpauseDeployment | 
            //val result : Update = apiInstance.unpauseDeployment(unpauseDeployment)
            //result shouldBe ("TODO")
        }

        // to test unpauseStack
        should("test unpauseStack") {
            // uncomment below to test unpauseStack
            //val unpauseStack : UnpauseStack =  // UnpauseStack | 
            //val result : Update = apiInstance.unpauseStack(unpauseStack)
            //result shouldBe ("TODO")
        }

    }
}
