/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ca.glong.komodo.core.openapi.apis

import io.kotlintest.shouldBe
import io.kotlintest.specs.ShouldSpec

import ca.glong.komodo.core.openapi.apis.WriteApi
import ca.glong.komodo.core.openapi.models.Action
import ca.glong.komodo.core.openapi.models.AddUserToUserGroup
import ca.glong.komodo.core.openapi.models.Alerter
import ca.glong.komodo.core.openapi.models.BatchDeleteAllTerminals
import ca.glong.komodo.core.openapi.models.Build
import ca.glong.komodo.core.openapi.models.Builder
import ca.glong.komodo.core.openapi.models.CheckDeploymentForUpdate
import ca.glong.komodo.core.openapi.models.CheckStackForUpdate
import ca.glong.komodo.core.openapi.models.CloseAlert
import ca.glong.komodo.core.openapi.models.CommitSync
import ca.glong.komodo.core.openapi.models.CopyAction
import ca.glong.komodo.core.openapi.models.CopyAlerter
import ca.glong.komodo.core.openapi.models.CopyBuild
import ca.glong.komodo.core.openapi.models.CopyBuilder
import ca.glong.komodo.core.openapi.models.CopyDeployment
import ca.glong.komodo.core.openapi.models.CopyProcedure
import ca.glong.komodo.core.openapi.models.CopyRepo
import ca.glong.komodo.core.openapi.models.CopyResourceSync
import ca.glong.komodo.core.openapi.models.CopyServer
import ca.glong.komodo.core.openapi.models.CopyStack
import ca.glong.komodo.core.openapi.models.CopySwarm
import ca.glong.komodo.core.openapi.models.CreateAction
import ca.glong.komodo.core.openapi.models.CreateAlerter
import ca.glong.komodo.core.openapi.models.CreateApiKeyForServiceUser
import ca.glong.komodo.core.openapi.models.CreateBuild
import ca.glong.komodo.core.openapi.models.CreateBuilder
import ca.glong.komodo.core.openapi.models.CreateDeployment
import ca.glong.komodo.core.openapi.models.CreateDeploymentFromContainer
import ca.glong.komodo.core.openapi.models.CreateDockerRegistryAccount
import ca.glong.komodo.core.openapi.models.CreateGitProviderAccount
import ca.glong.komodo.core.openapi.models.CreateLocalUser
import ca.glong.komodo.core.openapi.models.CreateNetwork
import ca.glong.komodo.core.openapi.models.CreateOnboardingKey
import ca.glong.komodo.core.openapi.models.CreateOnboardingKeyResponse
import ca.glong.komodo.core.openapi.models.CreateProcedure
import ca.glong.komodo.core.openapi.models.CreateRepo
import ca.glong.komodo.core.openapi.models.CreateResourceSync
import ca.glong.komodo.core.openapi.models.CreateServer
import ca.glong.komodo.core.openapi.models.CreateServiceUser
import ca.glong.komodo.core.openapi.models.CreateStack
import ca.glong.komodo.core.openapi.models.CreateSwarm
import ca.glong.komodo.core.openapi.models.CreateTag
import ca.glong.komodo.core.openapi.models.CreateTerminal
import ca.glong.komodo.core.openapi.models.CreateUserGroup
import ca.glong.komodo.core.openapi.models.CreateVariable
import ca.glong.komodo.core.openapi.models.DeleteAction
import ca.glong.komodo.core.openapi.models.DeleteAlerter
import ca.glong.komodo.core.openapi.models.DeleteAllTerminals
import ca.glong.komodo.core.openapi.models.DeleteApiKeyForServiceUser
import ca.glong.komodo.core.openapi.models.DeleteBuild
import ca.glong.komodo.core.openapi.models.DeleteBuilder
import ca.glong.komodo.core.openapi.models.DeleteDeployment
import ca.glong.komodo.core.openapi.models.DeleteDockerRegistryAccount
import ca.glong.komodo.core.openapi.models.DeleteGitProviderAccount
import ca.glong.komodo.core.openapi.models.DeleteOnboardingKey
import ca.glong.komodo.core.openapi.models.DeleteProcedure
import ca.glong.komodo.core.openapi.models.DeleteRepo
import ca.glong.komodo.core.openapi.models.DeleteResourceSync
import ca.glong.komodo.core.openapi.models.DeleteServer
import ca.glong.komodo.core.openapi.models.DeleteStack
import ca.glong.komodo.core.openapi.models.DeleteSwarm
import ca.glong.komodo.core.openapi.models.DeleteTag
import ca.glong.komodo.core.openapi.models.DeleteTerminal
import ca.glong.komodo.core.openapi.models.DeleteUser
import ca.glong.komodo.core.openapi.models.DeleteUserGroup
import ca.glong.komodo.core.openapi.models.DeleteVariable
import ca.glong.komodo.core.openapi.models.Deployment
import ca.glong.komodo.core.openapi.models.DockerRegistryAccount
import ca.glong.komodo.core.openapi.models.GitProviderAccount
import ca.glong.komodo.core.openapi.models.OnboardingKey
import ca.glong.komodo.core.openapi.models.Procedure
import ca.glong.komodo.core.openapi.models.PushRecentlyViewed
import ca.glong.komodo.core.openapi.models.RefreshBuildCache
import ca.glong.komodo.core.openapi.models.RefreshRepoCache
import ca.glong.komodo.core.openapi.models.RefreshResourceSyncPending
import ca.glong.komodo.core.openapi.models.RefreshStackCache
import ca.glong.komodo.core.openapi.models.RemoveUserFromUserGroup
import ca.glong.komodo.core.openapi.models.RenameAction
import ca.glong.komodo.core.openapi.models.RenameAlerter
import ca.glong.komodo.core.openapi.models.RenameBuild
import ca.glong.komodo.core.openapi.models.RenameBuilder
import ca.glong.komodo.core.openapi.models.RenameDeployment
import ca.glong.komodo.core.openapi.models.RenameProcedure
import ca.glong.komodo.core.openapi.models.RenameRepo
import ca.glong.komodo.core.openapi.models.RenameResourceSync
import ca.glong.komodo.core.openapi.models.RenameServer
import ca.glong.komodo.core.openapi.models.RenameStack
import ca.glong.komodo.core.openapi.models.RenameSwarm
import ca.glong.komodo.core.openapi.models.RenameTag
import ca.glong.komodo.core.openapi.models.RenameUserGroup
import ca.glong.komodo.core.openapi.models.Repo
import ca.glong.komodo.core.openapi.models.ResourceSync
import ca.glong.komodo.core.openapi.models.RotateServerKeys
import ca.glong.komodo.core.openapi.models.Serror
import ca.glong.komodo.core.openapi.models.Server
import ca.glong.komodo.core.openapi.models.SetEveryoneUserGroup
import ca.glong.komodo.core.openapi.models.SetUsersInUserGroup
import ca.glong.komodo.core.openapi.models.Stack
import ca.glong.komodo.core.openapi.models.Swarm
import ca.glong.komodo.core.openapi.models.Tag
import ca.glong.komodo.core.openapi.models.Update
import ca.glong.komodo.core.openapi.models.UpdateAction
import ca.glong.komodo.core.openapi.models.UpdateAlerter
import ca.glong.komodo.core.openapi.models.UpdateBuild
import ca.glong.komodo.core.openapi.models.UpdateBuilder
import ca.glong.komodo.core.openapi.models.UpdateDeployment
import ca.glong.komodo.core.openapi.models.UpdateDockerRegistryAccount
import ca.glong.komodo.core.openapi.models.UpdateGitProviderAccount
import ca.glong.komodo.core.openapi.models.UpdateOnboardingKey
import ca.glong.komodo.core.openapi.models.UpdatePermissionOnResourceType
import ca.glong.komodo.core.openapi.models.UpdatePermissionOnTarget
import ca.glong.komodo.core.openapi.models.UpdateProcedure
import ca.glong.komodo.core.openapi.models.UpdateRepo
import ca.glong.komodo.core.openapi.models.UpdateResourceMeta
import ca.glong.komodo.core.openapi.models.UpdateResourceSync
import ca.glong.komodo.core.openapi.models.UpdateServer
import ca.glong.komodo.core.openapi.models.UpdateServerPublicKey
import ca.glong.komodo.core.openapi.models.UpdateServiceUserDescription
import ca.glong.komodo.core.openapi.models.UpdateStack
import ca.glong.komodo.core.openapi.models.UpdateSwarm
import ca.glong.komodo.core.openapi.models.UpdateTagColor
import ca.glong.komodo.core.openapi.models.UpdateUserAdmin
import ca.glong.komodo.core.openapi.models.UpdateUserBasePermissions
import ca.glong.komodo.core.openapi.models.UpdateVariableDescription
import ca.glong.komodo.core.openapi.models.UpdateVariableIsSecret
import ca.glong.komodo.core.openapi.models.UpdateVariableValue
import ca.glong.komodo.core.openapi.models.User
import ca.glong.komodo.core.openapi.models.UserGroup
import ca.glong.komodo.core.openapi.models.Variable
import ca.glong.komodo.core.openapi.models.WriteBuildFileContents
import ca.glong.komodo.core.openapi.models.WriteStackFileContents
import ca.glong.komodo.core.openapi.models.WriteSyncFileContents

class WriteApiTest : ShouldSpec() {
    init {
        // uncomment below to create an instance of WriteApi
        //val apiInstance = WriteApi()

        // to test addUserToUserGroup
        should("test addUserToUserGroup") {
            // uncomment below to test addUserToUserGroup
            //val addUserToUserGroup : AddUserToUserGroup =  // AddUserToUserGroup | 
            //val result : UserGroup = apiInstance.addUserToUserGroup(addUserToUserGroup)
            //result shouldBe ("TODO")
        }

        // to test batchDeleteAllTerminals
        should("test batchDeleteAllTerminals") {
            // uncomment below to test batchDeleteAllTerminals
            //val batchDeleteAllTerminals : BatchDeleteAllTerminals =  // BatchDeleteAllTerminals | 
            //val result : kotlin.String = apiInstance.batchDeleteAllTerminals(batchDeleteAllTerminals)
            //result shouldBe ("TODO")
        }

        // to test checkDeploymentForUpdate
        should("test checkDeploymentForUpdate") {
            // uncomment below to test checkDeploymentForUpdate
            //val checkDeploymentForUpdate : CheckDeploymentForUpdate =  // CheckDeploymentForUpdate | 
            //val result : kotlin.String = apiInstance.checkDeploymentForUpdate(checkDeploymentForUpdate)
            //result shouldBe ("TODO")
        }

        // to test checkStackForUpdate
        should("test checkStackForUpdate") {
            // uncomment below to test checkStackForUpdate
            //val checkStackForUpdate : CheckStackForUpdate =  // CheckStackForUpdate | 
            //val result : kotlin.String = apiInstance.checkStackForUpdate(checkStackForUpdate)
            //result shouldBe ("TODO")
        }

        // to test closeAlert
        should("test closeAlert") {
            // uncomment below to test closeAlert
            //val closeAlert : CloseAlert =  // CloseAlert | 
            //val result : kotlin.String = apiInstance.closeAlert(closeAlert)
            //result shouldBe ("TODO")
        }

        // to test commitSync
        should("test commitSync") {
            // uncomment below to test commitSync
            //val commitSync : CommitSync =  // CommitSync | 
            //val result : Update = apiInstance.commitSync(commitSync)
            //result shouldBe ("TODO")
        }

        // to test copyAction
        should("test copyAction") {
            // uncomment below to test copyAction
            //val copyAction : CopyAction =  // CopyAction | 
            //val result : Action = apiInstance.copyAction(copyAction)
            //result shouldBe ("TODO")
        }

        // to test copyAlerter
        should("test copyAlerter") {
            // uncomment below to test copyAlerter
            //val copyAlerter : CopyAlerter =  // CopyAlerter | 
            //val result : Alerter = apiInstance.copyAlerter(copyAlerter)
            //result shouldBe ("TODO")
        }

        // to test copyBuild
        should("test copyBuild") {
            // uncomment below to test copyBuild
            //val copyBuild : CopyBuild =  // CopyBuild | 
            //val result : Build = apiInstance.copyBuild(copyBuild)
            //result shouldBe ("TODO")
        }

        // to test copyBuilder
        should("test copyBuilder") {
            // uncomment below to test copyBuilder
            //val copyBuilder : CopyBuilder =  // CopyBuilder | 
            //val result : Builder = apiInstance.copyBuilder(copyBuilder)
            //result shouldBe ("TODO")
        }

        // to test copyDeployment
        should("test copyDeployment") {
            // uncomment below to test copyDeployment
            //val copyDeployment : CopyDeployment =  // CopyDeployment | 
            //val result : Deployment = apiInstance.copyDeployment(copyDeployment)
            //result shouldBe ("TODO")
        }

        // to test copyProcedure
        should("test copyProcedure") {
            // uncomment below to test copyProcedure
            //val copyProcedure : CopyProcedure =  // CopyProcedure | 
            //val result : Procedure = apiInstance.copyProcedure(copyProcedure)
            //result shouldBe ("TODO")
        }

        // to test copyRepo
        should("test copyRepo") {
            // uncomment below to test copyRepo
            //val copyRepo : CopyRepo =  // CopyRepo | 
            //val result : Repo = apiInstance.copyRepo(copyRepo)
            //result shouldBe ("TODO")
        }

        // to test copyResourceSync
        should("test copyResourceSync") {
            // uncomment below to test copyResourceSync
            //val copyResourceSync : CopyResourceSync =  // CopyResourceSync | 
            //val result : ResourceSync = apiInstance.copyResourceSync(copyResourceSync)
            //result shouldBe ("TODO")
        }

        // to test copyServer
        should("test copyServer") {
            // uncomment below to test copyServer
            //val copyServer : CopyServer =  // CopyServer | 
            //val result : Server = apiInstance.copyServer(copyServer)
            //result shouldBe ("TODO")
        }

        // to test copyStack
        should("test copyStack") {
            // uncomment below to test copyStack
            //val copyStack : CopyStack =  // CopyStack | 
            //val result : Stack = apiInstance.copyStack(copyStack)
            //result shouldBe ("TODO")
        }

        // to test copySwarm
        should("test copySwarm") {
            // uncomment below to test copySwarm
            //val copySwarm : CopySwarm =  // CopySwarm | 
            //val result : Swarm = apiInstance.copySwarm(copySwarm)
            //result shouldBe ("TODO")
        }

        // to test createAction
        should("test createAction") {
            // uncomment below to test createAction
            //val createAction : CreateAction =  // CreateAction | 
            //val result : Action = apiInstance.createAction(createAction)
            //result shouldBe ("TODO")
        }

        // to test createAlerter
        should("test createAlerter") {
            // uncomment below to test createAlerter
            //val createAlerter : CreateAlerter =  // CreateAlerter | 
            //val result : Alerter = apiInstance.createAlerter(createAlerter)
            //result shouldBe ("TODO")
        }

        // to test createApiKeyForServiceUser
        should("test createApiKeyForServiceUser") {
            // uncomment below to test createApiKeyForServiceUser
            //val createApiKeyForServiceUser : CreateApiKeyForServiceUser =  // CreateApiKeyForServiceUser | 
            //val result : Alerter = apiInstance.createApiKeyForServiceUser(createApiKeyForServiceUser)
            //result shouldBe ("TODO")
        }

        // to test createBuild
        should("test createBuild") {
            // uncomment below to test createBuild
            //val createBuild : CreateBuild =  // CreateBuild | 
            //val result : Build = apiInstance.createBuild(createBuild)
            //result shouldBe ("TODO")
        }

        // to test createBuilder
        should("test createBuilder") {
            // uncomment below to test createBuilder
            //val createBuilder : CreateBuilder =  // CreateBuilder | 
            //val result : Builder = apiInstance.createBuilder(createBuilder)
            //result shouldBe ("TODO")
        }

        // to test createDeployment
        should("test createDeployment") {
            // uncomment below to test createDeployment
            //val createDeployment : CreateDeployment =  // CreateDeployment | 
            //val result : Deployment = apiInstance.createDeployment(createDeployment)
            //result shouldBe ("TODO")
        }

        // to test createDeploymentFromContainer
        should("test createDeploymentFromContainer") {
            // uncomment below to test createDeploymentFromContainer
            //val createDeploymentFromContainer : CreateDeploymentFromContainer =  // CreateDeploymentFromContainer | 
            //val result : Deployment = apiInstance.createDeploymentFromContainer(createDeploymentFromContainer)
            //result shouldBe ("TODO")
        }

        // to test createDockerRegistryAccount
        should("test createDockerRegistryAccount") {
            // uncomment below to test createDockerRegistryAccount
            //val createDockerRegistryAccount : CreateDockerRegistryAccount =  // CreateDockerRegistryAccount | 
            //val result : DockerRegistryAccount = apiInstance.createDockerRegistryAccount(createDockerRegistryAccount)
            //result shouldBe ("TODO")
        }

        // to test createGitProviderAccount
        should("test createGitProviderAccount") {
            // uncomment below to test createGitProviderAccount
            //val createGitProviderAccount : CreateGitProviderAccount =  // CreateGitProviderAccount | 
            //val result : GitProviderAccount = apiInstance.createGitProviderAccount(createGitProviderAccount)
            //result shouldBe ("TODO")
        }

        // to test createLocalUser
        should("test createLocalUser") {
            // uncomment below to test createLocalUser
            //val createLocalUser : CreateLocalUser =  // CreateLocalUser | 
            //val result : User = apiInstance.createLocalUser(createLocalUser)
            //result shouldBe ("TODO")
        }

        // to test createNetwork
        should("test createNetwork") {
            // uncomment below to test createNetwork
            //val createNetwork : CreateNetwork =  // CreateNetwork | 
            //val result : Update = apiInstance.createNetwork(createNetwork)
            //result shouldBe ("TODO")
        }

        // to test createOnboardingKey
        should("test createOnboardingKey") {
            // uncomment below to test createOnboardingKey
            //val createOnboardingKey : CreateOnboardingKey =  // CreateOnboardingKey | 
            //val result : CreateOnboardingKeyResponse = apiInstance.createOnboardingKey(createOnboardingKey)
            //result shouldBe ("TODO")
        }

        // to test createProcedure
        should("test createProcedure") {
            // uncomment below to test createProcedure
            //val createProcedure : CreateProcedure =  // CreateProcedure | 
            //val result : Procedure = apiInstance.createProcedure(createProcedure)
            //result shouldBe ("TODO")
        }

        // to test createRepo
        should("test createRepo") {
            // uncomment below to test createRepo
            //val createRepo : CreateRepo =  // CreateRepo | 
            //val result : Repo = apiInstance.createRepo(createRepo)
            //result shouldBe ("TODO")
        }

        // to test createResourceSync
        should("test createResourceSync") {
            // uncomment below to test createResourceSync
            //val createResourceSync : CreateResourceSync =  // CreateResourceSync | 
            //val result : ResourceSync = apiInstance.createResourceSync(createResourceSync)
            //result shouldBe ("TODO")
        }

        // to test createServer
        should("test createServer") {
            // uncomment below to test createServer
            //val createServer : CreateServer =  // CreateServer | 
            //val result : Server = apiInstance.createServer(createServer)
            //result shouldBe ("TODO")
        }

        // to test createServiceUser
        should("test createServiceUser") {
            // uncomment below to test createServiceUser
            //val createServiceUser : CreateServiceUser =  // CreateServiceUser | 
            //val result : User = apiInstance.createServiceUser(createServiceUser)
            //result shouldBe ("TODO")
        }

        // to test createStack
        should("test createStack") {
            // uncomment below to test createStack
            //val createStack : CreateStack =  // CreateStack | 
            //val result : Stack = apiInstance.createStack(createStack)
            //result shouldBe ("TODO")
        }

        // to test createSwarm
        should("test createSwarm") {
            // uncomment below to test createSwarm
            //val createSwarm : CreateSwarm =  // CreateSwarm | 
            //val result : Swarm = apiInstance.createSwarm(createSwarm)
            //result shouldBe ("TODO")
        }

        // to test createTag
        should("test createTag") {
            // uncomment below to test createTag
            //val createTag : CreateTag =  // CreateTag | 
            //val result : Tag = apiInstance.createTag(createTag)
            //result shouldBe ("TODO")
        }

        // to test createTerminal
        should("test createTerminal") {
            // uncomment below to test createTerminal
            //val createTerminal : CreateTerminal =  // CreateTerminal | 
            //val result : kotlin.String = apiInstance.createTerminal(createTerminal)
            //result shouldBe ("TODO")
        }

        // to test createUserGroup
        should("test createUserGroup") {
            // uncomment below to test createUserGroup
            //val createUserGroup : CreateUserGroup =  // CreateUserGroup | 
            //val result : UserGroup = apiInstance.createUserGroup(createUserGroup)
            //result shouldBe ("TODO")
        }

        // to test createVariable
        should("test createVariable") {
            // uncomment below to test createVariable
            //val createVariable : CreateVariable =  // CreateVariable | 
            //val result : Variable = apiInstance.createVariable(createVariable)
            //result shouldBe ("TODO")
        }

        // to test deleteAction
        should("test deleteAction") {
            // uncomment below to test deleteAction
            //val deleteAction : DeleteAction =  // DeleteAction | 
            //val result : Action = apiInstance.deleteAction(deleteAction)
            //result shouldBe ("TODO")
        }

        // to test deleteAlerter
        should("test deleteAlerter") {
            // uncomment below to test deleteAlerter
            //val deleteAlerter : DeleteAlerter =  // DeleteAlerter | 
            //val result : Alerter = apiInstance.deleteAlerter(deleteAlerter)
            //result shouldBe ("TODO")
        }

        // to test deleteAllTerminals
        should("test deleteAllTerminals") {
            // uncomment below to test deleteAllTerminals
            //val deleteAllTerminals : DeleteAllTerminals =  // DeleteAllTerminals | 
            //val result : kotlin.String = apiInstance.deleteAllTerminals(deleteAllTerminals)
            //result shouldBe ("TODO")
        }

        // to test deleteApiKeyForServiceUser
        should("test deleteApiKeyForServiceUser") {
            // uncomment below to test deleteApiKeyForServiceUser
            //val deleteApiKeyForServiceUser : DeleteApiKeyForServiceUser =  // DeleteApiKeyForServiceUser | 
            //val result : Alerter = apiInstance.deleteApiKeyForServiceUser(deleteApiKeyForServiceUser)
            //result shouldBe ("TODO")
        }

        // to test deleteBuild
        should("test deleteBuild") {
            // uncomment below to test deleteBuild
            //val deleteBuild : DeleteBuild =  // DeleteBuild | 
            //val result : Build = apiInstance.deleteBuild(deleteBuild)
            //result shouldBe ("TODO")
        }

        // to test deleteBuilder
        should("test deleteBuilder") {
            // uncomment below to test deleteBuilder
            //val deleteBuilder : DeleteBuilder =  // DeleteBuilder | 
            //val result : Builder = apiInstance.deleteBuilder(deleteBuilder)
            //result shouldBe ("TODO")
        }

        // to test deleteDeployment
        should("test deleteDeployment") {
            // uncomment below to test deleteDeployment
            //val deleteDeployment : DeleteDeployment =  // DeleteDeployment | 
            //val result : Deployment = apiInstance.deleteDeployment(deleteDeployment)
            //result shouldBe ("TODO")
        }

        // to test deleteDockerRegistryAccount
        should("test deleteDockerRegistryAccount") {
            // uncomment below to test deleteDockerRegistryAccount
            //val deleteDockerRegistryAccount : DeleteDockerRegistryAccount =  // DeleteDockerRegistryAccount | 
            //val result : DockerRegistryAccount = apiInstance.deleteDockerRegistryAccount(deleteDockerRegistryAccount)
            //result shouldBe ("TODO")
        }

        // to test deleteGitProviderAccount
        should("test deleteGitProviderAccount") {
            // uncomment below to test deleteGitProviderAccount
            //val deleteGitProviderAccount : DeleteGitProviderAccount =  // DeleteGitProviderAccount | 
            //val result : GitProviderAccount = apiInstance.deleteGitProviderAccount(deleteGitProviderAccount)
            //result shouldBe ("TODO")
        }

        // to test deleteOnboardingKey
        should("test deleteOnboardingKey") {
            // uncomment below to test deleteOnboardingKey
            //val deleteOnboardingKey : DeleteOnboardingKey =  // DeleteOnboardingKey | 
            //val result : OnboardingKey = apiInstance.deleteOnboardingKey(deleteOnboardingKey)
            //result shouldBe ("TODO")
        }

        // to test deleteProcedure
        should("test deleteProcedure") {
            // uncomment below to test deleteProcedure
            //val deleteProcedure : DeleteProcedure =  // DeleteProcedure | 
            //val result : Procedure = apiInstance.deleteProcedure(deleteProcedure)
            //result shouldBe ("TODO")
        }

        // to test deleteRepo
        should("test deleteRepo") {
            // uncomment below to test deleteRepo
            //val deleteRepo : DeleteRepo =  // DeleteRepo | 
            //val result : Repo = apiInstance.deleteRepo(deleteRepo)
            //result shouldBe ("TODO")
        }

        // to test deleteResourceSync
        should("test deleteResourceSync") {
            // uncomment below to test deleteResourceSync
            //val deleteResourceSync : DeleteResourceSync =  // DeleteResourceSync | 
            //val result : ResourceSync = apiInstance.deleteResourceSync(deleteResourceSync)
            //result shouldBe ("TODO")
        }

        // to test deleteServer
        should("test deleteServer") {
            // uncomment below to test deleteServer
            //val deleteServer : DeleteServer =  // DeleteServer | 
            //val result : Server = apiInstance.deleteServer(deleteServer)
            //result shouldBe ("TODO")
        }

        // to test deleteStack
        should("test deleteStack") {
            // uncomment below to test deleteStack
            //val deleteStack : DeleteStack =  // DeleteStack | 
            //val result : Stack = apiInstance.deleteStack(deleteStack)
            //result shouldBe ("TODO")
        }

        // to test deleteSwarm
        should("test deleteSwarm") {
            // uncomment below to test deleteSwarm
            //val deleteSwarm : DeleteSwarm =  // DeleteSwarm | 
            //val result : Swarm = apiInstance.deleteSwarm(deleteSwarm)
            //result shouldBe ("TODO")
        }

        // to test deleteTag
        should("test deleteTag") {
            // uncomment below to test deleteTag
            //val deleteTag : DeleteTag =  // DeleteTag | 
            //val result : Tag = apiInstance.deleteTag(deleteTag)
            //result shouldBe ("TODO")
        }

        // to test deleteTerminal
        should("test deleteTerminal") {
            // uncomment below to test deleteTerminal
            //val deleteTerminal : DeleteTerminal =  // DeleteTerminal | 
            //val result : kotlin.String = apiInstance.deleteTerminal(deleteTerminal)
            //result shouldBe ("TODO")
        }

        // to test deleteUser
        should("test deleteUser") {
            // uncomment below to test deleteUser
            //val deleteUser : DeleteUser =  // DeleteUser | 
            //val result : User = apiInstance.deleteUser(deleteUser)
            //result shouldBe ("TODO")
        }

        // to test deleteUserGroup
        should("test deleteUserGroup") {
            // uncomment below to test deleteUserGroup
            //val deleteUserGroup : DeleteUserGroup =  // DeleteUserGroup | 
            //val result : UserGroup = apiInstance.deleteUserGroup(deleteUserGroup)
            //result shouldBe ("TODO")
        }

        // to test deleteVariable
        should("test deleteVariable") {
            // uncomment below to test deleteVariable
            //val deleteVariable : DeleteVariable =  // DeleteVariable | 
            //val result : Variable = apiInstance.deleteVariable(deleteVariable)
            //result shouldBe ("TODO")
        }

        // to test pushRecentlyViewed
        should("test pushRecentlyViewed") {
            // uncomment below to test pushRecentlyViewed
            //val pushRecentlyViewed : PushRecentlyViewed =  // PushRecentlyViewed | 
            //val result : kotlin.String = apiInstance.pushRecentlyViewed(pushRecentlyViewed)
            //result shouldBe ("TODO")
        }

        // to test refreshBuildCache
        should("test refreshBuildCache") {
            // uncomment below to test refreshBuildCache
            //val refreshBuildCache : RefreshBuildCache =  // RefreshBuildCache | 
            //val result : kotlin.String = apiInstance.refreshBuildCache(refreshBuildCache)
            //result shouldBe ("TODO")
        }

        // to test refreshRepoCache
        should("test refreshRepoCache") {
            // uncomment below to test refreshRepoCache
            //val refreshRepoCache : RefreshRepoCache =  // RefreshRepoCache | 
            //val result : kotlin.String = apiInstance.refreshRepoCache(refreshRepoCache)
            //result shouldBe ("TODO")
        }

        // to test refreshResourceSyncPending
        should("test refreshResourceSyncPending") {
            // uncomment below to test refreshResourceSyncPending
            //val refreshResourceSyncPending : RefreshResourceSyncPending =  // RefreshResourceSyncPending | 
            //val result : ResourceSync = apiInstance.refreshResourceSyncPending(refreshResourceSyncPending)
            //result shouldBe ("TODO")
        }

        // to test refreshStackCache
        should("test refreshStackCache") {
            // uncomment below to test refreshStackCache
            //val refreshStackCache : RefreshStackCache =  // RefreshStackCache | 
            //val result : kotlin.String = apiInstance.refreshStackCache(refreshStackCache)
            //result shouldBe ("TODO")
        }

        // to test removeUserFromUserGroup
        should("test removeUserFromUserGroup") {
            // uncomment below to test removeUserFromUserGroup
            //val removeUserFromUserGroup : RemoveUserFromUserGroup =  // RemoveUserFromUserGroup | 
            //val result : UserGroup = apiInstance.removeUserFromUserGroup(removeUserFromUserGroup)
            //result shouldBe ("TODO")
        }

        // to test renameAction
        should("test renameAction") {
            // uncomment below to test renameAction
            //val renameAction : RenameAction =  // RenameAction | 
            //val result : Update = apiInstance.renameAction(renameAction)
            //result shouldBe ("TODO")
        }

        // to test renameAlerter
        should("test renameAlerter") {
            // uncomment below to test renameAlerter
            //val renameAlerter : RenameAlerter =  // RenameAlerter | 
            //val result : Update = apiInstance.renameAlerter(renameAlerter)
            //result shouldBe ("TODO")
        }

        // to test renameBuild
        should("test renameBuild") {
            // uncomment below to test renameBuild
            //val renameBuild : RenameBuild =  // RenameBuild | 
            //val result : Update = apiInstance.renameBuild(renameBuild)
            //result shouldBe ("TODO")
        }

        // to test renameBuilder
        should("test renameBuilder") {
            // uncomment below to test renameBuilder
            //val renameBuilder : RenameBuilder =  // RenameBuilder | 
            //val result : Update = apiInstance.renameBuilder(renameBuilder)
            //result shouldBe ("TODO")
        }

        // to test renameDeployment
        should("test renameDeployment") {
            // uncomment below to test renameDeployment
            //val renameDeployment : RenameDeployment =  // RenameDeployment | 
            //val result : Update = apiInstance.renameDeployment(renameDeployment)
            //result shouldBe ("TODO")
        }

        // to test renameProcedure
        should("test renameProcedure") {
            // uncomment below to test renameProcedure
            //val renameProcedure : RenameProcedure =  // RenameProcedure | 
            //val result : Update = apiInstance.renameProcedure(renameProcedure)
            //result shouldBe ("TODO")
        }

        // to test renameRepo
        should("test renameRepo") {
            // uncomment below to test renameRepo
            //val renameRepo : RenameRepo =  // RenameRepo | 
            //val result : Update = apiInstance.renameRepo(renameRepo)
            //result shouldBe ("TODO")
        }

        // to test renameResourceSync
        should("test renameResourceSync") {
            // uncomment below to test renameResourceSync
            //val renameResourceSync : RenameResourceSync =  // RenameResourceSync | 
            //val result : Update = apiInstance.renameResourceSync(renameResourceSync)
            //result shouldBe ("TODO")
        }

        // to test renameServer
        should("test renameServer") {
            // uncomment below to test renameServer
            //val renameServer : RenameServer =  // RenameServer | 
            //val result : Update = apiInstance.renameServer(renameServer)
            //result shouldBe ("TODO")
        }

        // to test renameStack
        should("test renameStack") {
            // uncomment below to test renameStack
            //val renameStack : RenameStack =  // RenameStack | 
            //val result : Update = apiInstance.renameStack(renameStack)
            //result shouldBe ("TODO")
        }

        // to test renameSwarm
        should("test renameSwarm") {
            // uncomment below to test renameSwarm
            //val renameSwarm : RenameSwarm =  // RenameSwarm | 
            //val result : Update = apiInstance.renameSwarm(renameSwarm)
            //result shouldBe ("TODO")
        }

        // to test renameTag
        should("test renameTag") {
            // uncomment below to test renameTag
            //val renameTag : RenameTag =  // RenameTag | 
            //val result : Tag = apiInstance.renameTag(renameTag)
            //result shouldBe ("TODO")
        }

        // to test renameUserGroup
        should("test renameUserGroup") {
            // uncomment below to test renameUserGroup
            //val renameUserGroup : RenameUserGroup =  // RenameUserGroup | 
            //val result : UserGroup = apiInstance.renameUserGroup(renameUserGroup)
            //result shouldBe ("TODO")
        }

        // to test rotateServerKeys
        should("test rotateServerKeys") {
            // uncomment below to test rotateServerKeys
            //val rotateServerKeys : RotateServerKeys =  // RotateServerKeys | 
            //val result : Update = apiInstance.rotateServerKeys(rotateServerKeys)
            //result shouldBe ("TODO")
        }

        // to test setEveryoneUserGroup
        should("test setEveryoneUserGroup") {
            // uncomment below to test setEveryoneUserGroup
            //val setEveryoneUserGroup : SetEveryoneUserGroup =  // SetEveryoneUserGroup | 
            //val result : UserGroup = apiInstance.setEveryoneUserGroup(setEveryoneUserGroup)
            //result shouldBe ("TODO")
        }

        // to test setLastSeenUpdate
        should("test setLastSeenUpdate") {
            // uncomment below to test setLastSeenUpdate
            //val body : kotlin.String = Object // kotlin.String | 
            //val result : kotlin.String = apiInstance.setLastSeenUpdate(body)
            //result shouldBe ("TODO")
        }

        // to test setUsersInUserGroup
        should("test setUsersInUserGroup") {
            // uncomment below to test setUsersInUserGroup
            //val setUsersInUserGroup : SetUsersInUserGroup =  // SetUsersInUserGroup | 
            //val result : UserGroup = apiInstance.setUsersInUserGroup(setUsersInUserGroup)
            //result shouldBe ("TODO")
        }

        // to test updateAction
        should("test updateAction") {
            // uncomment below to test updateAction
            //val updateAction : UpdateAction =  // UpdateAction | 
            //val result : Action = apiInstance.updateAction(updateAction)
            //result shouldBe ("TODO")
        }

        // to test updateAlerter
        should("test updateAlerter") {
            // uncomment below to test updateAlerter
            //val updateAlerter : UpdateAlerter =  // UpdateAlerter | 
            //val result : Alerter = apiInstance.updateAlerter(updateAlerter)
            //result shouldBe ("TODO")
        }

        // to test updateBuild
        should("test updateBuild") {
            // uncomment below to test updateBuild
            //val updateBuild : UpdateBuild =  // UpdateBuild | 
            //val result : Build = apiInstance.updateBuild(updateBuild)
            //result shouldBe ("TODO")
        }

        // to test updateBuilder
        should("test updateBuilder") {
            // uncomment below to test updateBuilder
            //val updateBuilder : UpdateBuilder =  // UpdateBuilder | 
            //val result : Builder = apiInstance.updateBuilder(updateBuilder)
            //result shouldBe ("TODO")
        }

        // to test updateDeployment
        should("test updateDeployment") {
            // uncomment below to test updateDeployment
            //val updateDeployment : UpdateDeployment =  // UpdateDeployment | 
            //val result : Deployment = apiInstance.updateDeployment(updateDeployment)
            //result shouldBe ("TODO")
        }

        // to test updateDockerRegistryAccount
        should("test updateDockerRegistryAccount") {
            // uncomment below to test updateDockerRegistryAccount
            //val updateDockerRegistryAccount : UpdateDockerRegistryAccount =  // UpdateDockerRegistryAccount | 
            //val result : DockerRegistryAccount = apiInstance.updateDockerRegistryAccount(updateDockerRegistryAccount)
            //result shouldBe ("TODO")
        }

        // to test updateGitProviderAccount
        should("test updateGitProviderAccount") {
            // uncomment below to test updateGitProviderAccount
            //val updateGitProviderAccount : UpdateGitProviderAccount =  // UpdateGitProviderAccount | 
            //val result : GitProviderAccount = apiInstance.updateGitProviderAccount(updateGitProviderAccount)
            //result shouldBe ("TODO")
        }

        // to test updateOnboardingKey
        should("test updateOnboardingKey") {
            // uncomment below to test updateOnboardingKey
            //val updateOnboardingKey : UpdateOnboardingKey =  // UpdateOnboardingKey | 
            //val result : OnboardingKey = apiInstance.updateOnboardingKey(updateOnboardingKey)
            //result shouldBe ("TODO")
        }

        // to test updatePermissionOnResourceType
        should("test updatePermissionOnResourceType") {
            // uncomment below to test updatePermissionOnResourceType
            //val updatePermissionOnResourceType : UpdatePermissionOnResourceType =  // UpdatePermissionOnResourceType | 
            //val result : kotlin.String = apiInstance.updatePermissionOnResourceType(updatePermissionOnResourceType)
            //result shouldBe ("TODO")
        }

        // to test updatePermissionOnTarget
        should("test updatePermissionOnTarget") {
            // uncomment below to test updatePermissionOnTarget
            //val updatePermissionOnTarget : UpdatePermissionOnTarget =  // UpdatePermissionOnTarget | 
            //val result : kotlin.String = apiInstance.updatePermissionOnTarget(updatePermissionOnTarget)
            //result shouldBe ("TODO")
        }

        // to test updateProcedure
        should("test updateProcedure") {
            // uncomment below to test updateProcedure
            //val updateProcedure : UpdateProcedure =  // UpdateProcedure | 
            //val result : Procedure = apiInstance.updateProcedure(updateProcedure)
            //result shouldBe ("TODO")
        }

        // to test updateRepo
        should("test updateRepo") {
            // uncomment below to test updateRepo
            //val updateRepo : UpdateRepo =  // UpdateRepo | 
            //val result : Repo = apiInstance.updateRepo(updateRepo)
            //result shouldBe ("TODO")
        }

        // to test updateResourceMeta
        should("test updateResourceMeta") {
            // uncomment below to test updateResourceMeta
            //val updateResourceMeta : UpdateResourceMeta =  // UpdateResourceMeta | 
            //val result : kotlin.String = apiInstance.updateResourceMeta(updateResourceMeta)
            //result shouldBe ("TODO")
        }

        // to test updateResourceSync
        should("test updateResourceSync") {
            // uncomment below to test updateResourceSync
            //val updateResourceSync : UpdateResourceSync =  // UpdateResourceSync | 
            //val result : ResourceSync = apiInstance.updateResourceSync(updateResourceSync)
            //result shouldBe ("TODO")
        }

        // to test updateServer
        should("test updateServer") {
            // uncomment below to test updateServer
            //val updateServer : UpdateServer =  // UpdateServer | 
            //val result : Server = apiInstance.updateServer(updateServer)
            //result shouldBe ("TODO")
        }

        // to test updateServerPublicKey
        should("test updateServerPublicKey") {
            // uncomment below to test updateServerPublicKey
            //val updateServerPublicKey : UpdateServerPublicKey =  // UpdateServerPublicKey | 
            //val result : Update = apiInstance.updateServerPublicKey(updateServerPublicKey)
            //result shouldBe ("TODO")
        }

        // to test updateServiceUserDescription
        should("test updateServiceUserDescription") {
            // uncomment below to test updateServiceUserDescription
            //val updateServiceUserDescription : UpdateServiceUserDescription =  // UpdateServiceUserDescription | 
            //val result : User = apiInstance.updateServiceUserDescription(updateServiceUserDescription)
            //result shouldBe ("TODO")
        }

        // to test updateStack
        should("test updateStack") {
            // uncomment below to test updateStack
            //val updateStack : UpdateStack =  // UpdateStack | 
            //val result : Stack = apiInstance.updateStack(updateStack)
            //result shouldBe ("TODO")
        }

        // to test updateSwarm
        should("test updateSwarm") {
            // uncomment below to test updateSwarm
            //val updateSwarm : UpdateSwarm =  // UpdateSwarm | 
            //val result : Swarm = apiInstance.updateSwarm(updateSwarm)
            //result shouldBe ("TODO")
        }

        // to test updateTagColor
        should("test updateTagColor") {
            // uncomment below to test updateTagColor
            //val updateTagColor : UpdateTagColor =  // UpdateTagColor | 
            //val result : Tag = apiInstance.updateTagColor(updateTagColor)
            //result shouldBe ("TODO")
        }

        // to test updateUserAdmin
        should("test updateUserAdmin") {
            // uncomment below to test updateUserAdmin
            //val updateUserAdmin : UpdateUserAdmin =  // UpdateUserAdmin | 
            //val result : kotlin.String = apiInstance.updateUserAdmin(updateUserAdmin)
            //result shouldBe ("TODO")
        }

        // to test updateUserBasePermissions
        should("test updateUserBasePermissions") {
            // uncomment below to test updateUserBasePermissions
            //val updateUserBasePermissions : UpdateUserBasePermissions =  // UpdateUserBasePermissions | 
            //val result : kotlin.String = apiInstance.updateUserBasePermissions(updateUserBasePermissions)
            //result shouldBe ("TODO")
        }

        // to test updateVariableDescription
        should("test updateVariableDescription") {
            // uncomment below to test updateVariableDescription
            //val updateVariableDescription : UpdateVariableDescription =  // UpdateVariableDescription | 
            //val result : Variable = apiInstance.updateVariableDescription(updateVariableDescription)
            //result shouldBe ("TODO")
        }

        // to test updateVariableIsSecret
        should("test updateVariableIsSecret") {
            // uncomment below to test updateVariableIsSecret
            //val updateVariableIsSecret : UpdateVariableIsSecret =  // UpdateVariableIsSecret | 
            //val result : Variable = apiInstance.updateVariableIsSecret(updateVariableIsSecret)
            //result shouldBe ("TODO")
        }

        // to test updateVariableValue
        should("test updateVariableValue") {
            // uncomment below to test updateVariableValue
            //val updateVariableValue : UpdateVariableValue =  // UpdateVariableValue | 
            //val result : Variable = apiInstance.updateVariableValue(updateVariableValue)
            //result shouldBe ("TODO")
        }

        // to test writeBuildFileContents
        should("test writeBuildFileContents") {
            // uncomment below to test writeBuildFileContents
            //val writeBuildFileContents : WriteBuildFileContents =  // WriteBuildFileContents | 
            //val result : Update = apiInstance.writeBuildFileContents(writeBuildFileContents)
            //result shouldBe ("TODO")
        }

        // to test writeStackFileContents
        should("test writeStackFileContents") {
            // uncomment below to test writeStackFileContents
            //val writeStackFileContents : WriteStackFileContents =  // WriteStackFileContents | 
            //val result : Update = apiInstance.writeStackFileContents(writeStackFileContents)
            //result shouldBe ("TODO")
        }

        // to test writeSyncFileContents
        should("test writeSyncFileContents") {
            // uncomment below to test writeSyncFileContents
            //val writeSyncFileContents : WriteSyncFileContents =  // WriteSyncFileContents | 
            //val result : Update = apiInstance.writeSyncFileContents(writeSyncFileContents)
            //result shouldBe ("TODO")
        }

    }
}
