#Kotlin
kotlin.code.style=official
kotlin.daemon.jvmargs=-Xmx14g
kotlin.incremental.native=true

#Gradle
org.gradle.jvmargs=-Xmx14g -Dfile.encoding=UTF-8 -XX:MaxMetaspaceSize=3g
kotlin.mpp.enableCInteropCommonization=true
org.gradle.configuration-cache=true
org.gradle.caching=true
org.gradle.parallel=true



kotlin.mpp.androidSourceSetLayoutVersion=2
#Android
android.nonTransitiveRClass=true
android.useAndroidX=true
android.newDsl=false
android.builtInKotlin=false