/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ca.glong.komodo.core.openapi.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * A server has high memory usage.
 *
 * @param id The id of the server
 * @param name The name of the server
 * @param totalGb The total memory
 * @param usedGb The used memory
 * @param region The region of the server
 */
@Serializable@Serializable

data class AlertDataOneOf5Data (

    /* The id of the server */
    @SerialName(value = "id") @Required val id: kotlin.String,

    /* The name of the server */
    @SerialName(value = "name") @Required val name: kotlin.String,

    /* The total memory */
    @SerialName(value = "total_gb") @Required val totalGb: kotlin.Double,

    /* The used memory */
    @SerialName(value = "used_gb") @Required val usedGb: kotlin.Double,

    /* The region of the server */
    @SerialName(value = "region") val region: kotlin.String? = null

) {


}

