/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ca.glong.komodo.core.openapi.models

import ca.glong.komodo.core.openapi.models.AlertDataOneOf16Data

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * A build has failed
 *
 * @param `data` 
 * @param type 
 */
@Serializable@Serializable

data class AlertDataOneOf16 (

    @SerialName(value = "data") @Required val `data`: AlertDataOneOf16Data,

    @SerialName(value = "type") @Required val type: AlertDataOneOf16.Type

) {

    /**
     * 
     *
     * Values: BUILD_FAILED
     */
    @Serializable
    enum class Type(val value: kotlin.String) {
        @SerialName(value = "BuildFailed") BUILD_FAILED("BuildFailed");
    }

}

