/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ca.glong.komodo.core.openapi.models

import ca.glong.komodo.core.openapi.models.Version

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * A build has failed
 *
 * @param id The id of the build
 * @param name The name of the build
 * @param version The version that failed to build
 */
@Serializable@Serializable

data class AlertDataOneOf16Data (

    /* The id of the build */
    @SerialName(value = "id") @Required val id: kotlin.String,

    /* The name of the build */
    @SerialName(value = "name") @Required val name: kotlin.String,

    /* The version that failed to build */
    @SerialName(value = "version") @Required val version: Version

) {


}

