/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ca.glong.komodo.core.openapi.models

import ca.glong.komodo.core.openapi.models.AlertDataOneOf15Data

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * A resource sync has pending updates
 *
 * @param `data` 
 * @param type 
 */
@Serializable@Serializable

data class AlertDataOneOf15 (

    @SerialName(value = "data") @Required val `data`: AlertDataOneOf15Data,

    @SerialName(value = "type") @Required val type: AlertDataOneOf15.Type

) {

    /**
     * 
     *
     * Values: RESOURCE_SYNC_PENDING_UPDATES
     */
    @Serializable
    enum class Type(val value: kotlin.String) {
        @SerialName(value = "ResourceSyncPendingUpdates") RESOURCE_SYNC_PENDING_UPDATES("ResourceSyncPendingUpdates");
    }

}

