/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ca.glong.komodo.core.openapi.models

import ca.glong.komodo.core.openapi.models.StackState

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * A stack's state has changed unexpectedly.
 *
 * @param from The previous stack state
 * @param id The id of the stack
 * @param name The name of the stack
 * @param to The current stack state
 * @param serverId The server id of server that the stack is on
 * @param serverName The server name
 * @param swarmId The swarm id of swarm that the stack is on
 * @param swarmName The swarm name
 */
@Serializable@Serializable

data class AlertDataOneOf11Data (

    /* The previous stack state */
    @SerialName(value = "from") @Required val from: StackState,

    /* The id of the stack */
    @SerialName(value = "id") @Required val id: kotlin.String,

    /* The name of the stack */
    @SerialName(value = "name") @Required val name: kotlin.String,

    /* The current stack state */
    @SerialName(value = "to") @Required val to: StackState,

    /* The server id of server that the stack is on */
    @SerialName(value = "server_id") val serverId: kotlin.String? = null,

    /* The server name */
    @SerialName(value = "server_name") val serverName: kotlin.String? = null,

    /* The swarm id of swarm that the stack is on */
    @SerialName(value = "swarm_id") val swarmId: kotlin.String? = null,

    /* The swarm name */
    @SerialName(value = "swarm_name") val swarmName: kotlin.String? = null

) {


}

