/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ca.glong.komodo.core.openapi.models

import ca.glong.komodo.core.openapi.models.AlertDataOneOf3Data

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * A server could not be reached.
 *
 * @param `data` 
 * @param type 
 */
@Serializable@Serializable

data class AlertDataOneOf3 (

    @SerialName(value = "data") @Required val `data`: AlertDataOneOf3Data,

    @SerialName(value = "type") @Required val type: AlertDataOneOf3.Type

) {

    /**
     * 
     *
     * Values: SERVER_UNREACHABLE
     */
    @Serializable
    enum class Type(val value: kotlin.String) {
        @SerialName(value = "ServerUnreachable") SERVER_UNREACHABLE("ServerUnreachable");
    }

}

