/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ca.glong.komodo.core.openapi.models

import ca.glong.komodo.core.openapi.models.SlackAlerterEndpoint

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * Send alert to a Slack app
 *
 * @param params Send alert to a Slack app
 * @param type 
 */
@Serializable@Serializable

data class AlerterEndpointOneOf1 (

    /* Send alert to a Slack app */
    @SerialName(value = "params") @Required val params: SlackAlerterEndpoint,

    @SerialName(value = "type") @Required val type: AlerterEndpointOneOf1.Type

) {

    /**
     * 
     *
     * Values: SLACK
     */
    @Serializable
    enum class Type(val value: kotlin.String) {
        @SerialName(value = "Slack") SLACK("Slack");
    }

}

