/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ca.glong.komodo.core.openapi.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * A Stack was auto updated
 *
 * @param id The id of the stack
 * @param images One or more images that were updated
 * @param name The name of the stack
 * @param serverId The server id of server that the stack is on
 * @param serverName The server name
 * @param swarmId The swarm id of swarm that the stack is on
 * @param swarmName The swarm name
 */
@Serializable@Serializable

data class AlertDataOneOf13Data (

    /* The id of the stack */
    @SerialName(value = "id") @Required val id: kotlin.String,

    /* One or more images that were updated */
    @SerialName(value = "images") @Required val images: kotlin.collections.List<kotlin.String>,

    /* The name of the stack */
    @SerialName(value = "name") @Required val name: kotlin.String,

    /* The server id of server that the stack is on */
    @SerialName(value = "server_id") val serverId: kotlin.String? = null,

    /* The server name */
    @SerialName(value = "server_name") val serverName: kotlin.String? = null,

    /* The swarm id of swarm that the stack is on */
    @SerialName(value = "swarm_id") val swarmId: kotlin.String? = null,

    /* The swarm name */
    @SerialName(value = "swarm_name") val swarmName: kotlin.String? = null

) {


}

