/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ca.glong.komodo.core.openapi.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * An AWS builder failed to terminate.
 *
 * @param instanceId The id of the aws instance which failed to terminate
 * @param message A reason for the failure
 */
@Serializable@Serializable

data class AlertDataOneOf14Data (

    /* The id of the aws instance which failed to terminate */
    @SerialName(value = "instance_id") @Required val instanceId: kotlin.String,

    /* A reason for the failure */
    @SerialName(value = "message") @Required val message: kotlin.String

) {


}

