/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ca.glong.komodo.core.openapi.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * Clones multiple Repos in parallel that match pattern. Response: [BatchExecutionResponse].
 *
 * @param pattern Id or name or wildcard pattern or regex. Supports multiline and comma delineated combinations of the above.  Example: ```text # match all foo-* repos foo-* # add some more extra-repo-1, extra-repo-2 ```
 */
@Serializable@Serializable

data class BatchCloneRepo (

    /* Id or name or wildcard pattern or regex. Supports multiline and comma delineated combinations of the above.  Example: ```text # match all foo-* repos foo-* # add some more extra-repo-1, extra-repo-2 ``` */
    @SerialName(value = "pattern") @Required val pattern: kotlin.String

) {


}

