/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ca.glong.komodo.core.openapi.models

import ca.glong.komodo.core.openapi.models.ServerBuilderConfig

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * Use a connected server as a Builder.
 *
 * @param params Use a connected server as a Builder.
 * @param type 
 */
@Serializable@Serializable

data class BuilderConfigOneOf1 (

    /* Use a connected server as a Builder. */
    @SerialName(value = "params") @Required val params: ServerBuilderConfig,

    @SerialName(value = "type") @Required val type: BuilderConfigOneOf1.Type

) {

    /**
     * 
     *
     * Values: SERVER
     */
    @Serializable
    enum class Type(val value: kotlin.String) {
        @SerialName(value = "Server") SERVER("Server");
    }

}

