/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ca.glong.komodo.core.openapi.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * Item in [GetBuildMonthlyStatsResponse]
 *
 * @param count 
 * @param time 
 * @param ts 
 */
@Serializable@Serializable

data class BuildStatsDay (

    @SerialName(value = "count") @Required val count: kotlin.Double,

    @SerialName(value = "time") @Required val time: kotlin.Double,

    @SerialName(value = "ts") @Required val ts: kotlin.Double

) {


}

