/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ca.glong.komodo.core.openapi.models

import ca.glong.komodo.core.openapi.models.ImageRegistryConfig
import ca.glong.komodo.core.openapi.models.SystemCommand
import ca.glong.komodo.core.openapi.models.Version

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * The build configuration.
 *
 * @param autoIncrementVersion Whether to automatically increment the patch on every build. Default is `true`
 * @param branch The branch of the repo.
 * @param buildArgs Docker build arguments.  These values are visible in the final image by running `docker inspect`.
 * @param buildPath The path of the docker build context relative to the root of the repo. Default: \".\" (the root of the repo).
 * @param builderId Which builder is used to build the image.
 * @param commit Optionally set a specific commit hash.
 * @param dockerfile UI defined dockerfile contents. Supports variable / secret interpolation.
 * @param dockerfilePath The path of the dockerfile relative to the build path.
 * @param extraArgs Any extra docker cli arguments to be included in the build command
 * @param filesOnHost If this is checked, the build will source the files on the host. Use `build_path` and `dockerfile_path` to specify the path on the host. This is useful for those who wish to setup their files on the host, rather than defining the contents in UI or in a git repo.
 * @param gitAccount The git account used to access private repos. Passing empty string can only clone public repos.  Note. A token for the account must be available in the core config or the builder server's periphery config for the configured git provider.
 * @param gitHttps Whether to use https to clone the repo (versus http). Default: true  Note. Komodo does not currently support cloning repos via ssh.
 * @param gitProvider The git provider domain. Default: github.com
 * @param imageName An alternate name for the image pushed to the repository. If this is empty, it will use the build name.  Can be used in conjunction with `image_tag` to direct multiple builds with different configs to push to the same image registry, under different, independantly versioned tags.
 * @param imageRegistry Configuration for the registry/s to push the built image to. The first registry in this list will be used with attached Deployments.
 * @param imageTag An extra tag put after the build version, for the image pushed to the repository. Eg. in image tag of `aarch64` would push to moghtech/komodo-core:1.13.2-aarch64. If this is empty, the image tag will just be the build version.  Can be used in conjunction with `image_name` to direct multiple builds with different configs to push to the same image registry, under different, independantly versioned tags.
 * @param includeCommitTag Push commit hash `:a6v8h83` / `:a6v8h83-image_tag` tags.
 * @param includeLatestTag Push `:latest` / `:latest-image_tag` tags.
 * @param includeVersionTags Push build version semver `:1.19.5` + `1.19` / `:1.19.5-image_tag` tags.
 * @param labels Docker labels
 * @param linkedRepo Choose a Komodo Repo (Resource) to source the build files.
 * @param links Configure quick links that are displayed in the resource header
 * @param preBuild The optional command run after repo clone and before docker build.
 * @param repo The repo used as the source of the build.
 * @param secretArgs Secret arguments.  These values remain hidden in the final image by using docker secret mounts. See <https://docs.docker.com/build/building/secrets>.  The values can be used in RUN commands: ```sh RUN --mount=type=secret,id=SECRET_KEY \\   SECRET_KEY=$(cat /run/secrets/SECRET_KEY) ... ```
 * @param skipSecretInterp Whether to skip secret interpolation in the build_args.
 * @param useBuildx Whether to use buildx to build (eg `docker buildx build ...`)
 * @param version The current version of the build.
 * @param webhookEnabled Whether incoming webhooks actually trigger action.
 * @param webhookSecret Optionally provide an alternate webhook secret for this build. If its an empty string, use the default secret from the config.
 */
@Serializable@Serializable

data class BuildConfig (

    /* Whether to automatically increment the patch on every build. Default is `true` */
    @SerialName(value = "auto_increment_version") val autoIncrementVersion: kotlin.Boolean? = null,

    /* The branch of the repo. */
    @SerialName(value = "branch") val branch: kotlin.String? = null,

    /* Docker build arguments.  These values are visible in the final image by running `docker inspect`. */
    @SerialName(value = "build_args") val buildArgs: kotlin.String? = null,

    /* The path of the docker build context relative to the root of the repo. Default: \".\" (the root of the repo). */
    @SerialName(value = "build_path") val buildPath: kotlin.String? = null,

    /* Which builder is used to build the image. */
    @SerialName(value = "builder_id") val builderId: kotlin.String? = null,

    /* Optionally set a specific commit hash. */
    @SerialName(value = "commit") val commit: kotlin.String? = null,

    /* UI defined dockerfile contents. Supports variable / secret interpolation. */
    @SerialName(value = "dockerfile") val dockerfile: kotlin.String? = null,

    /* The path of the dockerfile relative to the build path. */
    @SerialName(value = "dockerfile_path") val dockerfilePath: kotlin.String? = null,

    /* Any extra docker cli arguments to be included in the build command */
    @SerialName(value = "extra_args") val extraArgs: kotlin.collections.List<kotlin.String>? = null,

    /* If this is checked, the build will source the files on the host. Use `build_path` and `dockerfile_path` to specify the path on the host. This is useful for those who wish to setup their files on the host, rather than defining the contents in UI or in a git repo. */
    @SerialName(value = "files_on_host") val filesOnHost: kotlin.Boolean? = null,

    /* The git account used to access private repos. Passing empty string can only clone public repos.  Note. A token for the account must be available in the core config or the builder server's periphery config for the configured git provider. */
    @SerialName(value = "git_account") val gitAccount: kotlin.String? = null,

    /* Whether to use https to clone the repo (versus http). Default: true  Note. Komodo does not currently support cloning repos via ssh. */
    @SerialName(value = "git_https") val gitHttps: kotlin.Boolean? = null,

    /* The git provider domain. Default: github.com */
    @SerialName(value = "git_provider") val gitProvider: kotlin.String? = null,

    /* An alternate name for the image pushed to the repository. If this is empty, it will use the build name.  Can be used in conjunction with `image_tag` to direct multiple builds with different configs to push to the same image registry, under different, independantly versioned tags. */
    @SerialName(value = "image_name") val imageName: kotlin.String? = null,

    /* Configuration for the registry/s to push the built image to. The first registry in this list will be used with attached Deployments. */
    @SerialName(value = "image_registry") val imageRegistry: kotlin.collections.List<ImageRegistryConfig>? = null,

    /* An extra tag put after the build version, for the image pushed to the repository. Eg. in image tag of `aarch64` would push to moghtech/komodo-core:1.13.2-aarch64. If this is empty, the image tag will just be the build version.  Can be used in conjunction with `image_name` to direct multiple builds with different configs to push to the same image registry, under different, independantly versioned tags. */
    @SerialName(value = "image_tag") val imageTag: kotlin.String? = null,

    /* Push commit hash `:a6v8h83` / `:a6v8h83-image_tag` tags. */
    @SerialName(value = "include_commit_tag") val includeCommitTag: kotlin.Boolean? = null,

    /* Push `:latest` / `:latest-image_tag` tags. */
    @SerialName(value = "include_latest_tag") val includeLatestTag: kotlin.Boolean? = null,

    /* Push build version semver `:1.19.5` + `1.19` / `:1.19.5-image_tag` tags. */
    @SerialName(value = "include_version_tags") val includeVersionTags: kotlin.Boolean? = null,

    /* Docker labels */
    @SerialName(value = "labels") val labels: kotlin.String? = null,

    /* Choose a Komodo Repo (Resource) to source the build files. */
    @SerialName(value = "linked_repo") val linkedRepo: kotlin.String? = null,

    /* Configure quick links that are displayed in the resource header */
    @SerialName(value = "links") val links: kotlin.collections.List<kotlin.String>? = null,

    /* The optional command run after repo clone and before docker build. */
    @SerialName(value = "pre_build") val preBuild: SystemCommand? = null,

    /* The repo used as the source of the build. */
    @SerialName(value = "repo") val repo: kotlin.String? = null,

    /* Secret arguments.  These values remain hidden in the final image by using docker secret mounts. See <https://docs.docker.com/build/building/secrets>.  The values can be used in RUN commands: ```sh RUN --mount=type=secret,id=SECRET_KEY \\   SECRET_KEY=$(cat /run/secrets/SECRET_KEY) ... ``` */
    @SerialName(value = "secret_args") val secretArgs: kotlin.String? = null,

    /* Whether to skip secret interpolation in the build_args. */
    @SerialName(value = "skip_secret_interp") val skipSecretInterp: kotlin.Boolean? = null,

    /* Whether to use buildx to build (eg `docker buildx build ...`) */
    @SerialName(value = "use_buildx") val useBuildx: kotlin.Boolean? = null,

    /* The current version of the build. */
    @SerialName(value = "version") val version: Version? = null,

    /* Whether incoming webhooks actually trigger action. */
    @SerialName(value = "webhook_enabled") val webhookEnabled: kotlin.Boolean? = null,

    /* Optionally provide an alternate webhook secret for this build. If its an empty string, use the default secret from the config. */
    @SerialName(value = "webhook_secret") val webhookSecret: kotlin.String? = null

) {


}

