/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ca.glong.komodo.core.openapi.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * Clones the target repo. Response: [Update].  Note. Repo must have server attached at `server_id`.  1. Clones the repo on the target server using `git clone https://{$token?}@github.com/${repo} -b ${branch}`. The token will only be used if a github account is specified, and must be declared in the periphery configuration on the target server. 2. If `on_clone` and `on_pull` are specified, they will be executed. `on_clone` will be executed before `on_pull`.
 *
 * @param repo Id or name
 */
@Serializable@Serializable

data class CloneRepo (

    /* Id or name */
    @SerialName(value = "repo") @Required val repo: kotlin.String

) {


}

