/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ca.glong.komodo.core.openapi.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * **Admin only.** Close the Alert at the given id. Response: [NoData]
 *
 * @param id The id of the Alert to close.
 */
@Serializable@Serializable

data class CloseAlert (

    /* The id of the Alert to close. */
    @SerialName(value = "id") @Required val id: kotlin.String

) {


}

