/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ca.glong.komodo.core.openapi.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * One cluster volume secret entry. Defines a key-value pair that is passed to the plugin.
 *
 * @param key Key is the name of the key of the key-value pair passed to the plugin.
 * @param secret Secret is the swarm Secret object from which to read data. This can be a Secret name or ID. The Secret data is retrieved by swarm and used as the value of the key-value pair passed to the plugin.
 */
@Serializable@Serializable

data class ClusterVolumeSpecAccessModeSecrets (

    /* Key is the name of the key of the key-value pair passed to the plugin. */
    @SerialName(value = "Key") val key: kotlin.String? = null,

    /* Secret is the swarm Secret object from which to read data. This can be a Secret name or ID. The Secret data is retrieved by swarm and used as the value of the key-value pair passed to the plugin. */
    @SerialName(value = "Secret") val secret: kotlin.String? = null

) {


}

