/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ca.glong.komodo.core.openapi.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * Response for [ConfirmTotpEnrollment].
 *
 * @param recoveryCodes 
 */
@Serializable@Serializable

data class ConfirmTotpEnrollmentResponse (

    @SerialName(value = "recovery_codes") @Required val recoveryCodes: kotlin.collections.List<kotlin.String>

) {


}

