/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ca.glong.komodo.core.openapi.models

import ca.glong.komodo.core.openapi.models.HealthConfig

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * Configuration for a container that is portable between hosts.  When used as `ContainerConfig` field in an image, `ContainerConfig` is an optional field containing the configuration of the container that was last committed when creating the image.  Previous versions of Docker builder used this field to store build cache, and it is not in active use anymore.
 *
 * @param argsEscaped Command is already escaped (Windows only)
 * @param attachStderr Whether to attach to `stderr`.
 * @param attachStdin Whether to attach to `stdin`.
 * @param attachStdout Whether to attach to `stdout`.
 * @param cmd Command to run specified as a string or an array of strings.
 * @param domainname The domain name to use for the container.
 * @param entrypoint The entry point for the container as a string or an array of strings.  If the array consists of exactly one empty string (`[\\\"\\\"]`) then the entry point is reset to system default (i.e., the entry point used by docker when there is no `ENTRYPOINT` instruction in the `Dockerfile`).
 * @param env A list of environment variables to set inside the container in the form `[\\\"VAR=value\\\", ...]`. A variable without `=` is removed from the environment, rather than to have an empty value.
 * @param exposedPorts An object mapping ports to an empty object in the form:  `{\\\"<port>/<tcp|udp|sctp>\\\": {}}`
 * @param healthcheck 
 * @param hostname The hostname to use for the container, as a valid RFC 1123 hostname.
 * @param image The name (or reference) of the image to use when creating the container, or which was used when the container was created.
 * @param labels User-defined key/value metadata.
 * @param networkDisabled Disable networking for the container.
 * @param onBuild `ONBUILD` metadata that were defined in the image's `Dockerfile`.
 * @param openStdin Open `stdin`
 * @param shell Shell for when `RUN`, `CMD`, and `ENTRYPOINT` uses a shell.
 * @param stdinOnce Close `stdin` after one attached client disconnects
 * @param stopSignal Signal to stop a container as a string or unsigned integer.
 * @param stopTimeout Timeout to stop a container in seconds.
 * @param tty Attach standard streams to a TTY, including `stdin` if it is not closed.
 * @param user The user that commands are run as inside the container.
 * @param volumes An object mapping mount point paths inside the container to empty objects.
 * @param workingDir The working directory for commands to run in.
 */
@Serializable@Serializable

data class ContainerConfig (

    /* Command is already escaped (Windows only) */
    @SerialName(value = "ArgsEscaped") val argsEscaped: kotlin.Boolean? = null,

    /* Whether to attach to `stderr`. */
    @SerialName(value = "AttachStderr") val attachStderr: kotlin.Boolean? = null,

    /* Whether to attach to `stdin`. */
    @SerialName(value = "AttachStdin") val attachStdin: kotlin.Boolean? = null,

    /* Whether to attach to `stdout`. */
    @SerialName(value = "AttachStdout") val attachStdout: kotlin.Boolean? = null,

    /* Command to run specified as a string or an array of strings. */
    @SerialName(value = "Cmd") val cmd: kotlin.collections.List<kotlin.String>? = null,

    /* The domain name to use for the container. */
    @SerialName(value = "Domainname") val domainname: kotlin.String? = null,

    /* The entry point for the container as a string or an array of strings.  If the array consists of exactly one empty string (`[\\\"\\\"]`) then the entry point is reset to system default (i.e., the entry point used by docker when there is no `ENTRYPOINT` instruction in the `Dockerfile`). */
    @SerialName(value = "Entrypoint") val entrypoint: kotlin.collections.List<kotlin.String>? = null,

    /* A list of environment variables to set inside the container in the form `[\\\"VAR=value\\\", ...]`. A variable without `=` is removed from the environment, rather than to have an empty value. */
    @SerialName(value = "Env") val env: kotlin.collections.List<kotlin.String>? = null,

    /* An object mapping ports to an empty object in the form:  `{\\\"<port>/<tcp|udp|sctp>\\\": {}}` */
    @SerialName(value = "ExposedPorts") val exposedPorts: kotlin.collections.List<kotlin.String>? = null,

    @SerialName(value = "Healthcheck") val healthcheck: HealthConfig? = null,

    /* The hostname to use for the container, as a valid RFC 1123 hostname. */
    @SerialName(value = "Hostname") val hostname: kotlin.String? = null,

    /* The name (or reference) of the image to use when creating the container, or which was used when the container was created. */
    @SerialName(value = "Image") val image: kotlin.String? = null,

    /* User-defined key/value metadata. */
    @SerialName(value = "Labels") val labels: kotlin.collections.Map<kotlin.String, kotlin.String>? = null,

    /* Disable networking for the container. */
    @SerialName(value = "NetworkDisabled") val networkDisabled: kotlin.Boolean? = null,

    /* `ONBUILD` metadata that were defined in the image's `Dockerfile`. */
    @SerialName(value = "OnBuild") val onBuild: kotlin.collections.List<kotlin.String>? = null,

    /* Open `stdin` */
    @SerialName(value = "OpenStdin") val openStdin: kotlin.Boolean? = null,

    /* Shell for when `RUN`, `CMD`, and `ENTRYPOINT` uses a shell. */
    @SerialName(value = "Shell") val shell: kotlin.collections.List<kotlin.String>? = null,

    /* Close `stdin` after one attached client disconnects */
    @SerialName(value = "StdinOnce") val stdinOnce: kotlin.Boolean? = null,

    /* Signal to stop a container as a string or unsigned integer. */
    @SerialName(value = "StopSignal") val stopSignal: kotlin.String? = null,

    /* Timeout to stop a container in seconds. */
    @SerialName(value = "StopTimeout") val stopTimeout: kotlin.Long? = null,

    /* Attach standard streams to a TTY, including `stdin` if it is not closed. */
    @SerialName(value = "Tty") val tty: kotlin.Boolean? = null,

    /* The user that commands are run as inside the container. */
    @SerialName(value = "User") val user: kotlin.String? = null,

    /* An object mapping mount point paths inside the container to empty objects. */
    @SerialName(value = "Volumes") val volumes: kotlin.collections.List<kotlin.String>? = null,

    /* The working directory for commands to run in. */
    @SerialName(value = "WorkingDir") val workingDir: kotlin.String? = null

) {


}

