/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ca.glong.komodo.core.openapi.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * Creates a new builder with given `name` and the configuration of the builder at the given `id`. Response: [Builder]
 *
 * @param id The id of the builder to copy.
 * @param name The name of the new builder.
 */
@Serializable@Serializable

data class CopyBuilder (

    /* The id of the builder to copy. */
    @SerialName(value = "id") @Required val id: kotlin.String,

    /* The name of the new builder. */
    @SerialName(value = "name") @Required val name: kotlin.String

) {


}

