/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ca.glong.komodo.core.openapi.models

import ca.glong.komodo.core.openapi.models.ContainerTerminalMode
import ca.glong.komodo.core.openapi.models.TerminalRecreateMode
import ca.glong.komodo.core.openapi.models.TerminalTarget

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * Create a Terminal. Requires minimum Read + Terminal permission on the target Resource. Response: [NoData]
 *
 * @param name A name for the Terminal session.
 * @param target The target to create terminal for
 * @param command The shell command (eg `bash`) to init the shell.  Default:  - Server: Configured on each Periphery  - ContainerExec: `sh`  - Attach: unused
 * @param mode For container terminals, choose 'exec' or 'attach'.  Default  - Server: ignored  - Container / Stack / Deployment: `exec`
 * @param recreate Default: `Never`
 */
@Serializable@Serializable

data class CreateTerminal (

    /* A name for the Terminal session. */
    @SerialName(value = "name") @Required val name: kotlin.String,

    /* The target to create terminal for */
    @SerialName(value = "target") @Required val target: TerminalTarget,

    /* The shell command (eg `bash`) to init the shell.  Default:  - Server: Configured on each Periphery  - ContainerExec: `sh`  - Attach: unused */
    @SerialName(value = "command") val command: kotlin.String? = null,

    /* For container terminals, choose 'exec' or 'attach'.  Default  - Server: ignored  - Container / Stack / Deployment: `exec` */
    @SerialName(value = "mode") val mode: ContainerTerminalMode? = null,

    /* Default: `Never` */
    @SerialName(value = "recreate") val recreate: TerminalRecreateMode? = null

) {


}

