/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ca.glong.komodo.core.openapi.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * Create a docker network on the server. Response: [Update]  `docker network create {name}`
 *
 * @param name The name of the network to create.
 * @param server Server Id or name
 */
@Serializable@Serializable

data class CreateNetwork (

    /* The name of the network to create. */
    @SerialName(value = "name") @Required val name: kotlin.String,

    /* Server Id or name */
    @SerialName(value = "server") @Required val server: kotlin.String

) {


}

