/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ca.glong.komodo.core.openapi.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * Create an API key for the calling user. Response: [NoData].
 *
 * @param name The name for the api key.
 * @param expires A unix timestamp in millseconds specifying api key expire time. Default is 0, which means no expiry.
 */
@Serializable@Serializable

data class CreateApiKey (

    /* The name for the api key. */
    @SerialName(value = "name") @Required val name: kotlin.String,

    /* A unix timestamp in millseconds specifying api key expire time. Default is 0, which means no expiry. */
    @SerialName(value = "expires") val expires: kotlin.Long? = null

) {


}

