/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ca.glong.komodo.core.openapi.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * Create a repo. Response: [Repo].
 *
 * @param name The name given to newly created repo.
 * @param config Optional partial config to initialize the repo with.
 */
@Serializable@Serializable

data class CreateRepo (

    /* The name given to newly created repo. */
    @SerialName(value = "name") @Required val name: kotlin.String,

    /* Optional partial config to initialize the repo with. */
    @SerialName(value = "config") val config: kotlin.collections.Map<kotlin.String, kotlin.Any>? = null

) {


}

