/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ca.glong.komodo.core.openapi.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * **Admin only.** Create a local user. Response: [User].  Note. Not to be confused with /auth/SignUpLocalUser. This method requires admin user credentials, and can bypass disabled user registration.
 *
 * @param password A password for the local user.
 * @param username The username for the local user.
 */
@Serializable@Serializable

data class CreateLocalUser (

    /* A password for the local user. */
    @SerialName(value = "password") @Required val password: kotlin.String,

    /* The username for the local user. */
    @SerialName(value = "username") @Required val username: kotlin.String

) {


}

