/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ca.glong.komodo.core.openapi.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * `docker config create [OPTIONS] CONFIG file|-`  https://docs.docker.com/reference/cli/docker/config/create/
 *
 * @param `data` The data to store in the secret
 * @param name The name of the secret to create
 * @param swarm Name or id
 * @param driver Optional custom secret driver
 * @param labels Docker labels to give the secret
 * @param templateDriver Optional custom template driver
 */
@Serializable@Serializable

data class CreateSwarmSecret (

    /* The data to store in the secret */
    @SerialName(value = "data") @Required val `data`: kotlin.String,

    /* The name of the secret to create */
    @SerialName(value = "name") @Required val name: kotlin.String,

    /* Name or id */
    @SerialName(value = "swarm") @Required val swarm: kotlin.String,

    /* Optional custom secret driver */
    @SerialName(value = "driver") val driver: kotlin.String? = null,

    /* Docker labels to give the secret */
    @SerialName(value = "labels") val labels: kotlin.collections.List<kotlin.String>? = null,

    /* Optional custom template driver */
    @SerialName(value = "template_driver") val templateDriver: kotlin.String? = null

) {


}

