/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ca.glong.komodo.core.openapi.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * Deletes the stack at the given id, and returns the deleted stack. Response: [Stack]
 *
 * @param id The id or name of the stack to delete.
 */
@Serializable@Serializable

data class DeleteStack (

    /* The id or name of the stack to delete. */
    @SerialName(value = "id") @Required val id: kotlin.String

) {


}

