/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ca.glong.komodo.core.openapi.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * **Admin only.** Delete a variable. Response: [Variable].
 *
 * @param name 
 */
@Serializable@Serializable

data class DeleteVariable (

    @SerialName(value = "name") @Required val name: kotlin.String

) {


}

