/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ca.glong.komodo.core.openapi.models

import ca.glong.komodo.core.openapi.models.Version

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * Deploy a Komodo Build.
 *
 * @param buildId The id of the Build
 * @param version Use a custom / older version of the image produced by the build. if version is 0.0.0, this means `latest` image.
 */
@Serializable@Serializable

data class DeploymentImageOneOf1Params (

    /* The id of the Build */
    @SerialName(value = "build_id") val buildId: kotlin.String? = null,

    /* Use a custom / older version of the image produced by the build. if version is 0.0.0, this means `latest` image. */
    @SerialName(value = "version") val version: Version? = null

) {


}

