/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ca.glong.komodo.core.openapi.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * A device mapping between the host and container
 *
 * @param cgroupPermissions 
 * @param pathInContainer 
 * @param pathOnHost 
 */
@Serializable@Serializable

data class DeviceMapping (

    @SerialName(value = "CgroupPermissions") val cgroupPermissions: kotlin.String? = null,

    @SerialName(value = "PathInContainer") val pathInContainer: kotlin.String? = null,

    @SerialName(value = "PathOnHost") val pathOnHost: kotlin.String? = null

) {


}

