/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ca.glong.komodo.core.openapi.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * A request for devices to be sent to device drivers
 *
 * @param capabilities A list of capabilities; an OR list of AND lists of capabilities.
 * @param count 
 * @param deviceIDs 
 * @param driver 
 * @param options Driver-specific options, specified as a key/value pairs. These options are passed directly to the driver.
 */
@Serializable@Serializable

data class DeviceRequest (

    /* A list of capabilities; an OR list of AND lists of capabilities. */
    @SerialName(value = "Capabilities") val capabilities: kotlin.collections.List<kotlin.collections.List<kotlin.String>>? = null,

    @SerialName(value = "Count") val count: kotlin.Long? = null,

    @SerialName(value = "DeviceIDs") val deviceIDs: kotlin.collections.List<kotlin.String>? = null,

    @SerialName(value = "Driver") val driver: kotlin.String? = null,

    /* Driver-specific options, specified as a key/value pairs. These options are passed directly to the driver. */
    @SerialName(value = "Options") val options: kotlin.collections.Map<kotlin.String, kotlin.String>? = null

) {


}

