/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ca.glong.komodo.core.openapi.models

import ca.glong.komodo.core.openapi.models.DiffDataOneOfData

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * Resource will be created
 *
 * @param `data` 
 * @param type 
 */
@Serializable@Serializable

data class DiffDataOneOf (

    @SerialName(value = "data") @Required val `data`: DiffDataOneOfData,

    @SerialName(value = "type") @Required val type: DiffDataOneOf.Type

) {

    /**
     * 
     *
     * Values: CREATE
     */
    @Serializable
    enum class Type(val value: kotlin.String) {
        @SerialName(value = "Create") CREATE("Create");
    }

}

