/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ca.glong.komodo.core.openapi.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param current The current TOML of the resource to delete
 */
@Serializable@Serializable

data class DiffDataOneOf2Data (

    /* The current TOML of the resource to delete */
    @SerialName(value = "current") @Required val current: kotlin.String

) {


}

