/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ca.glong.komodo.core.openapi.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * Configuration to access private image repositories on various registries.
 *
 * @param id The Mongo ID of the docker registry account. This field is de/serialized from/to JSON as `{ \"_id\": { \"$oid\": \"...\" }, ...(rest of DockerRegistryAccount) }`
 * @param domain The domain of the provider.  For docker registry, this can include 'http://...', however this is not recommended and won't work unless \"insecure registries\" are enabled on your hosts. See <https://docs.docker.com/reference/cli/dockerd/#insecure-registries>.
 * @param token The token in plain text on the db. If the database / host can be accessed this is insecure.
 * @param username The account username
 */
@Serializable@Serializable

data class DockerRegistryAccount (

    /* The Mongo ID of the docker registry account. This field is de/serialized from/to JSON as `{ \"_id\": { \"$oid\": \"...\" }, ...(rest of DockerRegistryAccount) }` */
    @SerialName(value = "_id") val id: kotlin.String? = null,

    /* The domain of the provider.  For docker registry, this can include 'http://...', however this is not recommended and won't work unless \"insecure registries\" are enabled on your hosts. See <https://docs.docker.com/reference/cli/dockerd/#insecure-registries>. */
    @SerialName(value = "domain") val domain: kotlin.String? = null,

    /* The token in plain text on the db. If the database / host can be accessed this is insecure. */
    @SerialName(value = "token") val token: kotlin.String? = null,

    /* The account username */
    @SerialName(value = "username") val username: kotlin.String? = null

) {


}

