/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ca.glong.komodo.core.openapi.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * Driver represents a driver (network, logging, secrets).
 *
 * @param name Name of the driver.
 * @param options Key/value map of driver-specific options.
 */
@Serializable@Serializable

data class Driver (

    /* Name of the driver. */
    @SerialName(value = "Name") @Required val name: kotlin.String,

    /* Key/value map of driver-specific options. */
    @SerialName(value = "Options") val options: kotlin.collections.Map<kotlin.String, kotlin.String>? = null

) {


}

