/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ca.glong.komodo.core.openapi.models

import ca.glong.komodo.core.openapi.models.EndpointPortConfigProtocolEnum
import ca.glong.komodo.core.openapi.models.EndpointPortConfigPublishModeEnum

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param name 
 * @param protocol 
 * @param publishMode The mode in which port is published.  <p><br /></p>  - \\\"ingress\\\" makes the target port accessible on every node,   regardless of whether there is a task for the service running on   that node or not. - \\\"host\\\" bypasses the routing mesh and publish the port directly on   the swarm node where that service is running.
 * @param publishedPort The port on the swarm hosts.
 * @param targetPort The port inside the container.
 */
@Serializable@Serializable

data class EndpointPortConfig (

    @SerialName(value = "Name") val name: kotlin.String? = null,

    @SerialName(value = "Protocol") val protocol: EndpointPortConfigProtocolEnum? = null,

    /* The mode in which port is published.  <p><br /></p>  - \\\"ingress\\\" makes the target port accessible on every node,   regardless of whether there is a task for the service running on   that node or not. - \\\"host\\\" bypasses the routing mesh and publish the port directly on   the swarm node where that service is running. */
    @SerialName(value = "PublishMode") val publishMode: EndpointPortConfigPublishModeEnum? = null,

    /* The port on the swarm hosts. */
    @SerialName(value = "PublishedPort") val publishedPort: kotlin.Long? = null,

    /* The port inside the container. */
    @SerialName(value = "TargetPort") val targetPort: kotlin.Long? = null

) {


}

