/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ca.glong.komodo.core.openapi.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * EndpointIPAMConfig represents an endpoint's IPAM configuration.
 *
 * @param ipv4Address 
 * @param ipv6Address 
 * @param linkLocalIPs 
 */
@Serializable@Serializable

data class EndpointIpamConfig (

    @SerialName(value = "IPv4Address") val ipv4Address: kotlin.String? = null,

    @SerialName(value = "IPv6Address") val ipv6Address: kotlin.String? = null,

    @SerialName(value = "LinkLocalIPs") val linkLocalIPs: kotlin.collections.List<kotlin.String>? = null

) {


}

