/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ca.glong.komodo.core.openapi.models

import ca.glong.komodo.core.openapi.models.RunSync

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * Execute a Resource Sync. (alias: `sync`)
 *
 * @param params Execute a Resource Sync. (alias: `sync`)
 * @param type 
 */
@Serializable@Serializable

data class ExecutionOneOf39 (

    /* Execute a Resource Sync. (alias: `sync`) */
    @SerialName(value = "params") @Required val params: RunSync,

    @SerialName(value = "type") @Required val type: ExecutionOneOf39.Type

) {

    /**
     * 
     *
     * Values: RUN_SYNC
     */
    @Serializable
    enum class Type(val value: kotlin.String) {
        @SerialName(value = "RunSync") RUN_SYNC("RunSync");
    }

}

