/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ca.glong.komodo.core.openapi.models

import ca.glong.komodo.core.openapi.models.RunBuild

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * Run the target build. (alias: `build`, `bd`)
 *
 * @param params Run the target build. (alias: `build`, `bd`)
 * @param type 
 */
@Serializable@Serializable

data class ExecutionOneOf25 (

    /* Run the target build. (alias: `build`, `bd`) */
    @SerialName(value = "params") @Required val params: RunBuild,

    @SerialName(value = "type") @Required val type: ExecutionOneOf25.Type

) {

    /**
     * 
     *
     * Values: RUN_BUILD
     */
    @Serializable
    enum class Type(val value: kotlin.String) {
        @SerialName(value = "RunBuild") RUN_BUILD("RunBuild");
    }

}

