/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ca.glong.komodo.core.openapi.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param params **Admin only.** Clears all repos from the Core repo cache. Response: [Update]
 * @param type 
 */
@Serializable@Serializable

data class ExecutionOneOf73 (

    /* **Admin only.** Clears all repos from the Core repo cache. Response: [Update] */
    @SerialName(value = "params") @Required val params: kotlin.String,

    @SerialName(value = "type") @Required val type: ExecutionOneOf73.Type

) {

    /**
     * 
     *
     * Values: CLEAR_REPO_CACHE
     */
    @Serializable
    enum class Type(val value: kotlin.String) {
        @SerialName(value = "ClearRepoCache") CLEAR_REPO_CACHE("ClearRepoCache");
    }

}

