/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ca.glong.komodo.core.openapi.models

import ca.glong.komodo.core.openapi.models.SendAlert

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param params 
 * @param type 
 */
@Serializable@Serializable

data class ExecutionOneOf42 (

    @SerialName(value = "params") @Required val params: SendAlert,

    @SerialName(value = "type") @Required val type: ExecutionOneOf42.Type

) {

    /**
     * 
     *
     * Values: SEND_ALERT
     */
    @Serializable
    enum class Type(val value: kotlin.String) {
        @SerialName(value = "SendAlert") SEND_ALERT("SendAlert");
    }

}

