/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ca.glong.komodo.core.openapi.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * Get a specific action. Response: [Action].
 *
 * @param action Id or name
 */
@Serializable@Serializable

data class GetAction (

    /* Id or name */
    @SerialName(value = "action") @Required val action: kotlin.String

) {


}

