/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ca.glong.komodo.core.openapi.models

import ca.glong.komodo.core.openapi.models.BuildStatsDay

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * Response for [GetBuildMonthlyStats].
 *
 * @param days 
 * @param totalCount 
 * @param totalTime 
 */
@Serializable@Serializable

data class GetBuildMonthlyStatsResponse (

    @SerialName(value = "days") @Required val days: kotlin.collections.List<BuildStatsDay>,

    @SerialName(value = "total_count") @Required val totalCount: kotlin.Double,

    @SerialName(value = "total_time") @Required val totalTime: kotlin.Double

) {


}

