/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ca.glong.komodo.core.openapi.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * Response for [GetBuildsSummary].
 *
 * @param building The number of builds currently building.
 * @param failed The number of builds with Failed state.
 * @param ok The number of builds with Ok state.
 * @param total The total number of builds in Komodo.
 * @param unknown The number of builds with unknown state.
 */
@Serializable@Serializable

data class GetBuildsSummaryResponse (

    /* The number of builds currently building. */
    @SerialName(value = "building") @Required val building: kotlin.Int,

    /* The number of builds with Failed state. */
    @SerialName(value = "failed") @Required val failed: kotlin.Int,

    /* The number of builds with Ok state. */
    @SerialName(value = "ok") @Required val ok: kotlin.Int,

    /* The total number of builds in Komodo. */
    @SerialName(value = "total") @Required val total: kotlin.Int,

    /* The number of builds with unknown state. */
    @SerialName(value = "unknown") @Required val unknown: kotlin.Int

) {


}

