/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ca.glong.komodo.core.openapi.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * Get a specific builder by id or name. Response: [Builder].
 *
 * @param builder Id or name
 */
@Serializable@Serializable

data class GetBuilder (

    /* Id or name */
    @SerialName(value = "builder") @Required val builder: kotlin.String

) {


}

