/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ca.glong.komodo.core.openapi.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * Response for [GetBuildersSummary].
 *
 * @param total The total number of builders.
 */
@Serializable@Serializable

data class GetBuildersSummaryResponse (

    /* The total number of builders. */
    @SerialName(value = "total") @Required val total: kotlin.Int

) {


}

