/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ca.glong.komodo.core.openapi.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * Response for [GetDeploymentsSummary].
 *
 * @param notDeployed The number of Deployments with NotDeployed state
 * @param running The number of Deployments with Running state
 * @param stopped The number of Deployments with Stopped or Paused state
 * @param total The total number of Deployments
 * @param unhealthy The number of Deployments with Restarting or Dead or Created (other) state
 * @param unknown The number of Deployments with Unknown state
 */
@Serializable@Serializable

data class GetDeploymentsSummaryResponse (

    /* The number of Deployments with NotDeployed state */
    @SerialName(value = "not_deployed") @Required val notDeployed: kotlin.Long,

    /* The number of Deployments with Running state */
    @SerialName(value = "running") @Required val running: kotlin.Long,

    /* The number of Deployments with Stopped or Paused state */
    @SerialName(value = "stopped") @Required val stopped: kotlin.Long,

    /* The total number of Deployments */
    @SerialName(value = "total") @Required val total: kotlin.Long,

    /* The number of Deployments with Restarting or Dead or Created (other) state */
    @SerialName(value = "unhealthy") @Required val unhealthy: kotlin.Long,

    /* The number of Deployments with Unknown state */
    @SerialName(value = "unknown") @Required val unknown: kotlin.Long

) {


}

