/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ca.glong.komodo.core.openapi.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * Get a specific git provider account. Response: [GetGitProviderAccountResponse].
 *
 * @param id 
 */
@Serializable@Serializable

data class GetGitProviderAccount (

    @SerialName(value = "id") @Required val id: kotlin.String

) {


}

