/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ca.glong.komodo.core.openapi.models

import ca.glong.komodo.core.openapi.models.SystemStatsRecord

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * Response to [GetHistoricalServerStats].
 *
 * @param stats The timeseries page of data.
 * @param nextPage If there is a next page of data, pass this to `page` to get it.
 */
@Serializable@Serializable

data class GetHistoricalServerStatsResponse (

    /* The timeseries page of data. */
    @SerialName(value = "stats") @Required val stats: kotlin.collections.List<SystemStatsRecord>,

    /* If there is a next page of data, pass this to `page` to get it. */
    @SerialName(value = "next_page") val nextPage: kotlin.Int? = null

) {


}

