/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ca.glong.komodo.core.openapi.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * Response for [GetResourceSyncsSummary]
 *
 * @param failed The number of syncs with failed state.
 * @param ok The number of syncs with Ok state.
 * @param pending The number of syncs with pending updates
 * @param syncing The number of syncs currently syncing.
 * @param total The total number of syncs
 * @param unknown The number of syncs with unknown state.
 */
@Serializable@Serializable

data class GetResourceSyncsSummaryResponse (

    /* The number of syncs with failed state. */
    @SerialName(value = "failed") @Required val failed: kotlin.Int,

    /* The number of syncs with Ok state. */
    @SerialName(value = "ok") @Required val ok: kotlin.Int,

    /* The number of syncs with pending updates */
    @SerialName(value = "pending") @Required val pending: kotlin.Int,

    /* The number of syncs currently syncing. */
    @SerialName(value = "syncing") @Required val syncing: kotlin.Int,

    /* The total number of syncs */
    @SerialName(value = "total") @Required val total: kotlin.Int,

    /* The number of syncs with unknown state. */
    @SerialName(value = "unknown") @Required val unknown: kotlin.Int

) {


}

