/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ca.glong.komodo.core.openapi.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * Response for [GetReposSummary]
 *
 * @param building The number of repos currently building.
 * @param cloning The number of repos currently cloning.
 * @param failed The number of repos with failed state.
 * @param ok The number of repos with Ok state.
 * @param pulling The number of repos currently pulling.
 * @param total The total number of repos
 * @param unknown The number of repos with unknown state.
 */
@Serializable@Serializable

data class GetReposSummaryResponse (

    /* The number of repos currently building. */
    @SerialName(value = "building") @Required val building: kotlin.Int,

    /* The number of repos currently cloning. */
    @SerialName(value = "cloning") @Required val cloning: kotlin.Int,

    /* The number of repos with failed state. */
    @SerialName(value = "failed") @Required val failed: kotlin.Int,

    /* The number of repos with Ok state. */
    @SerialName(value = "ok") @Required val ok: kotlin.Int,

    /* The number of repos currently pulling. */
    @SerialName(value = "pulling") @Required val pulling: kotlin.Int,

    /* The total number of repos */
    @SerialName(value = "total") @Required val total: kotlin.Int,

    /* The number of repos with unknown state. */
    @SerialName(value = "unknown") @Required val unknown: kotlin.Int

) {


}

