/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ca.glong.komodo.core.openapi.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * Response for [GetServersSummary].
 *
 * @param disabled The number of disabled servers.
 * @param healthy The number of healthy (`status: OK`) servers.
 * @param total The total number of servers.
 * @param unhealthy The number of unhealthy servers.
 * @param warning The number of servers with warnings (e.g., version mismatch).
 */
@Serializable@Serializable

data class GetServersSummaryResponse (

    /* The number of disabled servers. */
    @SerialName(value = "disabled") @Required val disabled: kotlin.Long,

    /* The number of healthy (`status: OK`) servers. */
    @SerialName(value = "healthy") @Required val healthy: kotlin.Long,

    /* The total number of servers. */
    @SerialName(value = "total") @Required val total: kotlin.Long,

    /* The number of unhealthy servers. */
    @SerialName(value = "unhealthy") @Required val unhealthy: kotlin.Long,

    /* The number of servers with warnings (e.g., version mismatch). */
    @SerialName(value = "warning") @Required val warning: kotlin.Long

) {


}

