/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ca.glong.komodo.core.openapi.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * Get the state of the target server. Response: [GetServerStateResponse].
 *
 * @param server Id or name
 */
@Serializable@Serializable

data class GetServerState (

    /* Id or name */
    @SerialName(value = "server") @Required val server: kotlin.String

) {


}

