/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ca.glong.komodo.core.openapi.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * Response for [GetStacksSummary]
 *
 * @param down The number of stacks with Down state.
 * @param running The number of stacks with Running state.
 * @param stopped The number of stacks with Stopped or Paused state.
 * @param total The total number of stacks
 * @param unhealthy The number of stacks with Unhealthy or Restarting or Dead or Created or Removing state.
 * @param unknown The number of stacks with Unknown state.
 */
@Serializable@Serializable

data class GetStacksSummaryResponse (

    /* The number of stacks with Down state. */
    @SerialName(value = "down") @Required val down: kotlin.Int,

    /* The number of stacks with Running state. */
    @SerialName(value = "running") @Required val running: kotlin.Int,

    /* The number of stacks with Stopped or Paused state. */
    @SerialName(value = "stopped") @Required val stopped: kotlin.Int,

    /* The total number of stacks */
    @SerialName(value = "total") @Required val total: kotlin.Int,

    /* The number of stacks with Unhealthy or Restarting or Dead or Created or Removing state. */
    @SerialName(value = "unhealthy") @Required val unhealthy: kotlin.Int,

    /* The number of stacks with Unknown state. */
    @SerialName(value = "unknown") @Required val unknown: kotlin.Int

) {


}

