/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ca.glong.komodo.core.openapi.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * Get a stack's logs. Filter down included services. Response: [GetStackLogResponse].  Note. This call will hit the underlying server directly for most up to date log.
 *
 * @param services Filter the logs to only ones from specific services. If empty, will include logs from all services.
 * @param stack Id or name
 * @param tail The number of lines of the log tail to include. Default: 100. Max: 5000.
 * @param timestamps Enable `--timestamps`
 */
@Serializable@Serializable

data class GetStackLog (

    /* Filter the logs to only ones from specific services. If empty, will include logs from all services. */
    @SerialName(value = "services") @Required val services: kotlin.collections.List<kotlin.String>,

    /* Id or name */
    @SerialName(value = "stack") @Required val stack: kotlin.String,

    /* The number of lines of the log tail to include. Default: 100. Max: 5000. */
    @SerialName(value = "tail") val tail: kotlin.Long? = null,

    /* Enable `--timestamps` */
    @SerialName(value = "timestamps") val timestamps: kotlin.Boolean? = null

) {


}

