/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ca.glong.komodo.core.openapi.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * Get current action state for the stack. Response: [StackActionState].
 *
 * @param stack Id or name
 */
@Serializable@Serializable

data class GetStackActionState (

    /* Id or name */
    @SerialName(value = "stack") @Required val stack: kotlin.String

) {


}

