/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ca.glong.komodo.core.openapi.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * Get a specific user group by name or id. Response: [UserGroup].
 *
 * @param userGroup Name or Id
 */
@Serializable@Serializable

data class GetUserGroup (

    /* Name or Id */
    @SerialName(value = "user_group") @Required val userGroup: kotlin.String

) {


}

