/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ca.glong.komodo.core.openapi.models

import ca.glong.komodo.core.openapi.models.ProviderAccount

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param accounts The accounts on the git provider. Required.
 * @param domain The git provider domain. Default: `github.com`.
 * @param https Whether to use https. Default: true.
 */
@Serializable@Serializable

data class GitProvider (

    /* The accounts on the git provider. Required. */
    @SerialName(value = "accounts") @Required val accounts: kotlin.collections.List<ProviderAccount>,

    /* The git provider domain. Default: `github.com`. */
    @SerialName(value = "domain") val domain: kotlin.String? = null,

    /* Whether to use https. Default: true. */
    @SerialName(value = "https") val https: kotlin.Boolean? = null

) {


}

