/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ca.glong.komodo.core.openapi.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * **Admin only.** Trigger a global poll for image updates on Stacks and Deployments with `poll_for_updates` or `auto_update` enabled. Response: [Update]. Alias: `auto-update`.  1. Run CheckStackForUpdate / CheckDeploymentForUpdate any Stacks / Deployments with `poll_for_updates` or `auto_update` enabled.    This will pick up any available updates. 2. Redeploy Stacks / Deployments that have updates found and 'auto_update' enabled.      - Skip this using 'skip_auto_update', preferring to only alert even for 'auto_update' resources.
 *
 * @param skipAutoUpdate Normally resources with 'auto_update' will be redeployed immediately if updates are found. With this enabled, convert this into an UpdateAvailable alert.
 */
@Serializable@Serializable

data class GlobalAutoUpdate (

    /* Normally resources with 'auto_update' will be redeployed immediately if updates are found. With this enabled, convert this into an UpdateAvailable alert. */
    @SerialName(value = "skip_auto_update") val skipAutoUpdate: kotlin.Boolean? = null

) {


}

