/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ca.glong.komodo.core.openapi.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * Information about the image's RootFS, including the layer IDs.
 *
 * @param layers 
 * @param type 
 */
@Serializable@Serializable

data class ImageInspectRootFs (

    @SerialName(value = "Layers") val layers: kotlin.collections.List<kotlin.String>? = null,

    @SerialName(value = "Type") val type: kotlin.String? = null

) {


}

