/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ca.glong.komodo.core.openapi.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * Inspect a swarm service associated with a Stack. Response: [SwarmService].
 *
 * @param service The service name to inspect
 * @param stack Id or name
 */
@Serializable@Serializable

data class InspectStackSwarmService (

    /* The service name to inspect */
    @SerialName(value = "service") @Required val service: kotlin.String,

    /* Id or name */
    @SerialName(value = "stack") @Required val stack: kotlin.String

) {


}

