/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ca.glong.komodo.core.openapi.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * Inspect the swarm service associated with the Deployment. Response: [SwarmService].
 *
 * @param deployment Id or name
 */
@Serializable@Serializable

data class InspectDeploymentSwarmService (

    /* Id or name */
    @SerialName(value = "deployment") @Required val deployment: kotlin.String

) {


}

