/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ca.glong.komodo.core.openapi.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param `data` 
 * @param type 
 */
@Serializable@Serializable

data class JwtOrTwoFactorOneOf1 (

    @SerialName(value = "data") @Required val `data`: kotlin.collections.Map<kotlin.String, kotlin.Any>,

    @SerialName(value = "type") @Required val type: JwtOrTwoFactorOneOf1.Type

) {

    /**
     * 
     *
     * Values: PASSKEY
     */
    @Serializable
    enum class Type(val value: kotlin.String) {
        @SerialName(value = "Passkey") PASSKEY("Passkey");
    }

}

