/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ca.glong.komodo.core.openapi.models

import ca.glong.komodo.core.openapi.models.ResourceQuery

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * List builders matching structured query. Response: [ListFullBuildersResponse].
 *
 * @param query 
 */
@Serializable@Serializable

data class ListFullBuilders (

    @SerialName(value = "query") val query: ResourceQuery? = null

) {


}

