/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ca.glong.komodo.core.openapi.models

import ca.glong.komodo.core.openapi.models.TagQueryBehavior

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * List configured schedules. Response: [ListSchedulesResponse].
 *
 * @param tagBehavior 'All' or 'Any'
 * @param tags Pass Vec of tag ids or tag names
 */
@Serializable@Serializable

data class ListSchedules (

    /* 'All' or 'Any' */
    @SerialName(value = "tag_behavior") val tagBehavior: TagQueryBehavior? = null,

    /* Pass Vec of tag ids or tag names */
    @SerialName(value = "tags") val tags: kotlin.collections.List<kotlin.String>? = null

) {


}

