/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ca.glong.komodo.core.openapi.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * List git provider accounts matching optional query. Response: [ListGitProviderAccountsResponse].
 *
 * @param domain Optionally filter by accounts with a specific domain.
 * @param username Optionally filter by accounts with a specific username.
 */
@Serializable@Serializable

data class ListGitProviderAccounts (

    /* Optionally filter by accounts with a specific domain. */
    @SerialName(value = "domain") val domain: kotlin.String? = null,

    /* Optionally filter by accounts with a specific username. */
    @SerialName(value = "username") val username: kotlin.String? = null

) {


}

