/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ca.glong.komodo.core.openapi.models

import ca.glong.komodo.core.openapi.models.ResourceQuery

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * List stacks matching optional query. Response: [ListStacksResponse].
 *
 * @param query optional structured query to filter stacks.
 */
@Serializable@Serializable

data class ListStacks (

    /* optional structured query to filter stacks. */
    @SerialName(value = "query") val query: ResourceQuery? = null

) {


}

