/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ca.glong.komodo.core.openapi.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * Get image history from the server. Response: [ListDockerImageHistoryResponse].
 *
 * @param image The image name
 * @param server Id or name
 */
@Serializable@Serializable

data class ListDockerImageHistory (

    /* The image name */
    @SerialName(value = "image") @Required val image: kotlin.String,

    /* Id or name */
    @SerialName(value = "server") @Required val server: kotlin.String

) {


}

