/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ca.glong.komodo.core.openapi.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * List nodes part of the target Swarm. Response: [ListSwarmNodesResponse].
 *
 * @param swarm Id or name
 */
@Serializable@Serializable

data class ListSwarmNodes (

    /* Id or name */
    @SerialName(value = "swarm") @Required val swarm: kotlin.String

) {


}

