/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ca.glong.komodo.core.openapi.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * List all docker containers on the target servers. Response: [ListDockerContainersResponse].
 *
 * @param containers Filter by container name.
 * @param servers Filter by server id or name.
 */
@Serializable@Serializable

data class ListAllDockerContainers (

    /* Filter by container name. */
    @SerialName(value = "containers") val containers: kotlin.collections.List<kotlin.String>? = null,

    /* Filter by server id or name. */
    @SerialName(value = "servers") val servers: kotlin.collections.List<kotlin.String>? = null

) {


}

