/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ca.glong.komodo.core.openapi.models

import ca.glong.komodo.core.openapi.models.MountBindOptions
import ca.glong.komodo.core.openapi.models.MountTmpfsOptions
import ca.glong.komodo.core.openapi.models.MountTypeEnum
import ca.glong.komodo.core.openapi.models.MountVolumeOptions

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param bindOptions 
 * @param consistency The consistency requirement for the mount: `default`, `consistent`, `cached`, or `delegated`.
 * @param readOnly Whether the mount should be read-only.
 * @param source Mount source (e.g. a volume name, a host path).
 * @param target Container path.
 * @param tmpfsOptions 
 * @param type The mount type. Available types:   - `bind` Mounts a file or directory from the host into the container. Must exist prior to creating the container.   - `volume` Creates a volume with the given name and options (or uses a pre-existing volume with the same name and options). These are **not** removed when the container is removed.   - `tmpfs` Create a tmpfs with the given options. The mount source cannot be specified for tmpfs. - `npipe` Mounts a named pipe from the host into the container. Must exist prior to creating the container.   - `cluster` a Swarm cluster volume
 * @param volumeOptions 
 */
@Serializable@Serializable

data class Mount (

    @SerialName(value = "BindOptions") val bindOptions: MountBindOptions? = null,

    /* The consistency requirement for the mount: `default`, `consistent`, `cached`, or `delegated`. */
    @SerialName(value = "Consistency") val consistency: kotlin.String? = null,

    /* Whether the mount should be read-only. */
    @SerialName(value = "ReadOnly") val readOnly: kotlin.Boolean? = null,

    /* Mount source (e.g. a volume name, a host path). */
    @SerialName(value = "Source") val source: kotlin.String? = null,

    /* Container path. */
    @SerialName(value = "Target") val target: kotlin.String? = null,

    @SerialName(value = "TmpfsOptions") val tmpfsOptions: MountTmpfsOptions? = null,

    /* The mount type. Available types:   - `bind` Mounts a file or directory from the host into the container. Must exist prior to creating the container.   - `volume` Creates a volume with the given name and options (or uses a pre-existing volume with the same name and options). These are **not** removed when the container is removed.   - `tmpfs` Create a tmpfs with the given options. The mount source cannot be specified for tmpfs. - `npipe` Mounts a named pipe from the host into the container. Must exist prior to creating the container.   - `cluster` a Swarm cluster volume */
    @SerialName(value = "Type") val type: MountTypeEnum? = null,

    @SerialName(value = "VolumeOptions") val volumeOptions: MountVolumeOptions? = null

) {


}

