/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ca.glong.komodo.core.openapi.models

import ca.glong.komodo.core.openapi.models.MountBindOptionsPropagationEnum

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * Optional configuration for the `bind` type.
 *
 * @param createMountpoint Create mount point on host if missing
 * @param nonRecursive Disable recursive bind mount.
 * @param propagation A propagation mode with the value `[r]private`, `[r]shared`, or `[r]slave`.
 * @param readOnlyForceRecursive Raise an error if the mount cannot be made recursively read-only.
 * @param readOnlyNonRecursive Make the mount non-recursively read-only, but still leave the mount recursive (unless NonRecursive is set to `true` in conjunction).  Addded in v1.44, before that version all read-only mounts were non-recursive by default. To match the previous behaviour this will default to `true` for clients on versions prior to v1.44.
 */
@Serializable@Serializable

data class MountBindOptions (

    /* Create mount point on host if missing */
    @SerialName(value = "CreateMountpoint") val createMountpoint: kotlin.Boolean? = null,

    /* Disable recursive bind mount. */
    @SerialName(value = "NonRecursive") val nonRecursive: kotlin.Boolean? = null,

    /* A propagation mode with the value `[r]private`, `[r]shared`, or `[r]slave`. */
    @SerialName(value = "Propagation") val propagation: MountBindOptionsPropagationEnum? = null,

    /* Raise an error if the mount cannot be made recursively read-only. */
    @SerialName(value = "ReadOnlyForceRecursive") val readOnlyForceRecursive: kotlin.Boolean? = null,

    /* Make the mount non-recursively read-only, but still leave the mount recursive (unless NonRecursive is set to `true` in conjunction).  Addded in v1.44, before that version all read-only mounts were non-recursive by default. To match the previous behaviour this will default to `true` for clients on versions prior to v1.44. */
    @SerialName(value = "ReadOnlyNonRecursive") val readOnlyNonRecursive: kotlin.Boolean? = null

) {


}

