/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ca.glong.komodo.core.openapi.models

import ca.glong.komodo.core.openapi.models.OciPlatform

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * A descriptor struct containing digest, media type, and size, as defined in the [OCI Content Descriptors Specification](https://github.com/opencontainers/image-spec/blob/v1.0.1/descriptor.md).
 *
 * @param annotations Arbitrary metadata relating to the targeted content.
 * @param artifactType ArtifactType is the IANA media type of this artifact.
 * @param `data` Data is an embedding of the targeted content. This is encoded as a base64 string when marshalled to JSON (automatically, by encoding/json). If present, Data can be used directly to avoid fetching the targeted content.
 * @param digest The digest of the targeted content.
 * @param mediaType The media type of the object this schema refers to.
 * @param platform 
 * @param propertySize The size in bytes of the blob.
 * @param urls List of URLs from which this object MAY be downloaded.
 */
@Serializable@Serializable

data class OciDescriptor (

    /* Arbitrary metadata relating to the targeted content. */
    @SerialName(value = "annotations") val annotations: kotlin.collections.Map<kotlin.String, kotlin.String>? = null,

    /* ArtifactType is the IANA media type of this artifact. */
    @SerialName(value = "artifactType") val artifactType: kotlin.String? = null,

    /* Data is an embedding of the targeted content. This is encoded as a base64 string when marshalled to JSON (automatically, by encoding/json). If present, Data can be used directly to avoid fetching the targeted content. */
    @SerialName(value = "data") val `data`: kotlin.String? = null,

    /* The digest of the targeted content. */
    @SerialName(value = "digest") val digest: kotlin.String? = null,

    /* The media type of the object this schema refers to. */
    @SerialName(value = "mediaType") val mediaType: kotlin.String? = null,

    @SerialName(value = "platform") val platform: OciPlatform? = null,

    /* The size in bytes of the blob. */
    @SerialName(value = "size") val propertySize: kotlin.Long? = null,

    /* List of URLs from which this object MAY be downloaded. */
    @SerialName(value = "urls") val urls: kotlin.collections.List<kotlin.String>? = null

) {


}

