/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ca.glong.komodo.core.openapi.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * Describes the platform which the image in the manifest runs on, as defined in the [OCI Image Index Specification](https://github.com/opencontainers/image-spec/blob/v1.0.1/image-index.md).
 *
 * @param architecture The CPU architecture, for example `amd64` or `ppc64`.
 * @param os The operating system, for example `linux` or `windows`.
 * @param osFeatures Optional field specifying an array of strings, each listing a required OS feature (for example on Windows `win32k`).
 * @param osVersion Optional field specifying the operating system version, for example on Windows `10.0.19041.1165`.
 * @param variant Optional field specifying a variant of the CPU, for example `v7` to specify ARMv7 when architecture is `arm`.
 */
@Serializable@Serializable

data class OciPlatform (

    /* The CPU architecture, for example `amd64` or `ppc64`. */
    @SerialName(value = "architecture") val architecture: kotlin.String? = null,

    /* The operating system, for example `linux` or `windows`. */
    @SerialName(value = "os") val os: kotlin.String? = null,

    /* Optional field specifying an array of strings, each listing a required OS feature (for example on Windows `win32k`). */
    @SerialName(value = "os_features") val osFeatures: kotlin.collections.List<kotlin.String>? = null,

    /* Optional field specifying the operating system version, for example on Windows `10.0.19041.1165`. */
    @SerialName(value = "os_version") val osVersion: kotlin.String? = null,

    /* Optional field specifying a variant of the CPU, for example `v7` to specify ARMv7 when architecture is `arm`. */
    @SerialName(value = "variant") val variant: kotlin.String? = null

) {


}

