/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ca.glong.komodo.core.openapi.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * Pauses the container on the target server. Response: [Update]  1. Runs `docker pause ${container_name}`.
 *
 * @param container The container name
 * @param server Name or id
 */
@Serializable@Serializable

data class PauseContainer (

    /* The container name */
    @SerialName(value = "container") @Required val container: kotlin.String,

    /* Name or id */
    @SerialName(value = "server") @Required val server: kotlin.String

) {


}

