/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ca.glong.komodo.core.openapi.models

import ca.glong.komodo.core.openapi.models.PermissionLevel
import ca.glong.komodo.core.openapi.models.SpecificPermission

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param level 
 * @param specific 
 */
@Serializable@Serializable

data class PermissionLevelAndSpecifics (

    @SerialName(value = "level") @Required val level: PermissionLevel,

    @SerialName(value = "specific") @Required val specific: kotlin.collections.List<@Contextual SpecificPermission>

) {


}

