/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ca.glong.komodo.core.openapi.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * Describes a permission the user has to accept upon installing the plugin.
 *
 * @param description 
 * @param name 
 * @param `value` 
 */
@Serializable@Serializable

data class PluginPrivilege (

    @SerialName(value = "Description") val description: kotlin.String? = null,

    @SerialName(value = "Name") val name: kotlin.String? = null,

    @SerialName(value = "Value") val `value`: kotlin.collections.List<kotlin.String>? = null

) {


}

