/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ca.glong.komodo.core.openapi.models

import ca.glong.komodo.core.openapi.models.ProcedureStage
import ca.glong.komodo.core.openapi.models.ScheduleFormat

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * Config for the [Procedure]
 *
 * @param failureAlert Whether to send alerts when this procedure fails.
 * @param schedule Optionally provide a schedule for the procedure to run on.  There are 2 ways to specify a schedule:  1. Regular CRON expression:  (second, minute, hour, day, month, day-of-week) ```text 0 0 0 1,15 * ? ```  2. \"English\" expression via [english-to-cron](https://crates.io/crates/english-to-cron):  ```text at midnight on the 1st and 15th of the month ```
 * @param scheduleAlert Whether to send alerts when the schedule was run.
 * @param scheduleEnabled Whether schedule is enabled if one is provided. Can be used to temporarily disable the schedule.
 * @param scheduleFormat Choose whether to specify schedule as regular CRON, or using the english to CRON parser.
 * @param scheduleTimezone Optional. A TZ Identifier. If not provided, will use Core local timezone. https://en.wikipedia.org/wiki/List_of_tz_database_time_zones.
 * @param stages The stages to be run by the procedure.
 * @param webhookEnabled Whether incoming webhooks actually trigger action.
 * @param webhookSecret Optionally provide an alternate webhook secret for this procedure. If its an empty string, use the default secret from the config.
 */
@Serializable@Serializable

data class ProcedureConfig (

    /* Whether to send alerts when this procedure fails. */
    @SerialName(value = "failure_alert") val failureAlert: kotlin.Boolean? = null,

    /* Optionally provide a schedule for the procedure to run on.  There are 2 ways to specify a schedule:  1. Regular CRON expression:  (second, minute, hour, day, month, day-of-week) ```text 0 0 0 1,15 * ? ```  2. \"English\" expression via [english-to-cron](https://crates.io/crates/english-to-cron):  ```text at midnight on the 1st and 15th of the month ``` */
    @SerialName(value = "schedule") val schedule: kotlin.String? = null,

    /* Whether to send alerts when the schedule was run. */
    @SerialName(value = "schedule_alert") val scheduleAlert: kotlin.Boolean? = null,

    /* Whether schedule is enabled if one is provided. Can be used to temporarily disable the schedule. */
    @SerialName(value = "schedule_enabled") val scheduleEnabled: kotlin.Boolean? = null,

    /* Choose whether to specify schedule as regular CRON, or using the english to CRON parser. */
    @SerialName(value = "schedule_format") val scheduleFormat: ScheduleFormat? = null,

    /* Optional. A TZ Identifier. If not provided, will use Core local timezone. https://en.wikipedia.org/wiki/List_of_tz_database_time_zones. */
    @SerialName(value = "schedule_timezone") val scheduleTimezone: kotlin.String? = null,

    /* The stages to be run by the procedure. */
    @SerialName(value = "stages") val stages: kotlin.collections.List<ProcedureStage>? = null,

    /* Whether incoming webhooks actually trigger action. */
    @SerialName(value = "webhook_enabled") val webhookEnabled: kotlin.Boolean? = null,

    /* Optionally provide an alternate webhook secret for this procedure. If its an empty string, use the default secret from the config. */
    @SerialName(value = "webhook_secret") val webhookSecret: kotlin.String? = null

) {


}

