/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ca.glong.komodo.core.openapi.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * Pulls images for the target stack. `docker compose pull`. Response: [Update]
 *
 * @param stack Id or name
 * @param services Filter to only pull specific services. If empty, will pull all services.
 */
@Serializable@Serializable

data class PullStack (

    /* Id or name */
    @SerialName(value = "stack") @Required val stack: kotlin.String,

    /* Filter to only pull specific services. If empty, will pull all services. */
    @SerialName(value = "services") val services: kotlin.collections.List<kotlin.String>? = null

) {


}

