/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ca.glong.komodo.core.openapi.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * Trigger a refresh of the cached latest hash and message.
 *
 * @param build Id or name
 */
@Serializable@Serializable

data class RefreshBuildCache (

    /* Id or name */
    @SerialName(value = "build") @Required val build: kotlin.String

) {


}

