/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ca.glong.komodo.core.openapi.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * **Admin only.** Rename a user group. Response: [UserGroup]
 *
 * @param id The id of the UserGroup
 * @param name The new name for the UserGroup
 */
@Serializable@Serializable

data class RenameUserGroup (

    /* The id of the UserGroup */
    @SerialName(value = "id") @Required val id: kotlin.String,

    /* The new name for the UserGroup */
    @SerialName(value = "name") @Required val name: kotlin.String

) {


}

