/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ca.glong.komodo.core.openapi.models

import ca.glong.komodo.core.openapi.models.SystemCommand

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param branch The repo branch.
 * @param builderId Attach a builder to 'build' the repo.
 * @param commit Optionally set a specific commit hash.
 * @param envFilePath The name of the written environment file before `docker compose up`. Relative to the repo root. Default: .env
 * @param environment The environment variables passed to the compose file. They will be written to path defined in env_file_path, which is given relative to the run directory.  If it is empty, no file will be written.
 * @param gitAccount The git account used to access private repos. Passing empty string can only clone public repos.  Note. A token for the account must be available in the core config or the builder server's periphery config for the configured git provider.
 * @param gitHttps Whether to use https to clone the repo (versus http). Default: true  Note. Komodo does not currently support cloning repos via ssh.
 * @param gitProvider The git provider domain. Default: github.com
 * @param links Configure quick links that are displayed in the resource header
 * @param onClone Command to be run after the repo is cloned. The path is relative to the root of the repo.
 * @param onPull Command to be run after the repo is pulled. The path is relative to the root of the repo.
 * @param path Explicitly specify the folder to clone the repo in. - If absolute (has leading '/')   - Used directly as the path - If relative   - Taken relative to Periphery `repo_dir` (ie `${root_directory}/repos`)
 * @param repo The github repo to clone.
 * @param serverId The server to clone the repo on.
 * @param skipSecretInterp Whether to skip secret interpolation into the repo environment variable file.
 * @param webhookEnabled Whether incoming webhooks actually trigger action.
 * @param webhookSecret Optionally provide an alternate webhook secret for this repo. If its an empty string, use the default secret from the config.
 */
@Serializable@Serializable

data class RepoConfig (

    /* The repo branch. */
    @SerialName(value = "branch") val branch: kotlin.String? = null,

    /* Attach a builder to 'build' the repo. */
    @SerialName(value = "builder_id") val builderId: kotlin.String? = null,

    /* Optionally set a specific commit hash. */
    @SerialName(value = "commit") val commit: kotlin.String? = null,

    /* The name of the written environment file before `docker compose up`. Relative to the repo root. Default: .env */
    @SerialName(value = "env_file_path") val envFilePath: kotlin.String? = null,

    /* The environment variables passed to the compose file. They will be written to path defined in env_file_path, which is given relative to the run directory.  If it is empty, no file will be written. */
    @SerialName(value = "environment") val environment: kotlin.String? = null,

    /* The git account used to access private repos. Passing empty string can only clone public repos.  Note. A token for the account must be available in the core config or the builder server's periphery config for the configured git provider. */
    @SerialName(value = "git_account") val gitAccount: kotlin.String? = null,

    /* Whether to use https to clone the repo (versus http). Default: true  Note. Komodo does not currently support cloning repos via ssh. */
    @SerialName(value = "git_https") val gitHttps: kotlin.Boolean? = null,

    /* The git provider domain. Default: github.com */
    @SerialName(value = "git_provider") val gitProvider: kotlin.String? = null,

    /* Configure quick links that are displayed in the resource header */
    @SerialName(value = "links") val links: kotlin.collections.List<kotlin.String>? = null,

    /* Command to be run after the repo is cloned. The path is relative to the root of the repo. */
    @SerialName(value = "on_clone") val onClone: SystemCommand? = null,

    /* Command to be run after the repo is pulled. The path is relative to the root of the repo. */
    @SerialName(value = "on_pull") val onPull: SystemCommand? = null,

    /* Explicitly specify the folder to clone the repo in. - If absolute (has leading '/')   - Used directly as the path - If relative   - Taken relative to Periphery `repo_dir` (ie `${root_directory}/repos`) */
    @SerialName(value = "path") val path: kotlin.String? = null,

    /* The github repo to clone. */
    @SerialName(value = "repo") val repo: kotlin.String? = null,

    /* The server to clone the repo on. */
    @SerialName(value = "server_id") val serverId: kotlin.String? = null,

    /* Whether to skip secret interpolation into the repo environment variable file. */
    @SerialName(value = "skip_secret_interp") val skipSecretInterp: kotlin.Boolean? = null,

    /* Whether incoming webhooks actually trigger action. */
    @SerialName(value = "webhook_enabled") val webhookEnabled: kotlin.Boolean? = null,

    /* Optionally provide an alternate webhook secret for this repo. If its an empty string, use the default secret from the config. */
    @SerialName(value = "webhook_secret") val webhookSecret: kotlin.String? = null

) {


}

