/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ca.glong.komodo.core.openapi.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param building Whether Repo currently building using the attached Builder.
 * @param cloning Whether Repo currently cloning on the attached Server
 * @param pulling Whether Repo currently pulling on the attached Server
 * @param renaming Whether Repo currently renaming.
 */
@Serializable@Serializable

data class RepoActionState (

    /* Whether Repo currently building using the attached Builder. */
    @SerialName(value = "building") @Required val building: kotlin.Boolean,

    /* Whether Repo currently cloning on the attached Server */
    @SerialName(value = "cloning") @Required val cloning: kotlin.Boolean,

    /* Whether Repo currently pulling on the attached Server */
    @SerialName(value = "pulling") @Required val pulling: kotlin.Boolean,

    /* Whether Repo currently renaming. */
    @SerialName(value = "renaming") @Required val renaming: kotlin.Boolean

) {


}

