/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ca.glong.komodo.core.openapi.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * Runs the target Procedure. Response: [Update]
 *
 * @param procedure Id or name
 */
@Serializable@Serializable

data class RunProcedure (

    /* Id or name */
    @SerialName(value = "procedure") @Required val procedure: kotlin.String

) {


}

