/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ca.glong.komodo.core.openapi.models

import ca.glong.komodo.core.openapi.models.ResourceTargetVariant

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * Runs the target resource sync. Response: [Update]
 *
 * @param sync Id or name
 * @param resourceType Only execute sync on a specific resource type. Combine with `resource_id` to specify resource.
 * @param resources Only execute sync on a specific resources. Combine with `resource_type` to specify resources. Supports name or id.
 */
@Serializable@Serializable

data class RunSync (

    /* Id or name */
    @SerialName(value = "sync") @Required val sync: kotlin.String,

    /* Only execute sync on a specific resource type. Combine with `resource_id` to specify resource. */
    @SerialName(value = "resource_type") val resourceType: ResourceTargetVariant? = null,

    /* Only execute sync on a specific resources. Combine with `resource_type` to specify resources. Supports name or id. */
    @SerialName(value = "resources") val resources: kotlin.collections.List<kotlin.String>? = null

) {


}

