/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ca.glong.komodo.core.openapi.models

import ca.glong.komodo.core.openapi.models.SearchCombinator

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * Search the swarm service log's tail using `grep`. All lines go to stdout. Response: [SearchSwarmServiceLogResponse].  Note. This call will hit the underlying server directly for most up to date log.
 *
 * @param service Select the swarm service to get logs for.
 * @param swarm Id or name
 * @param terms The terms to search for.
 * @param combinator When searching for multiple terms, can use `AND` or `OR` combinator.  - `AND`: Only include lines with **all** terms present in that line. - `OR`: Include lines that have one or more matches in the terms.
 * @param details Enable `--details`
 * @param invert Invert the results, ie return all lines that DON'T match the terms / combinator.
 * @param noResolve Enable `--no-resolve`
 * @param noTaskIds Enable `--no-task-ids`
 * @param timestamps Enable `--timestamps`
 */
@Serializable@Serializable

data class SearchSwarmServiceLog (

    /* Select the swarm service to get logs for. */
    @SerialName(value = "service") @Required val service: kotlin.String,

    /* Id or name */
    @SerialName(value = "swarm") @Required val swarm: kotlin.String,

    /* The terms to search for. */
    @SerialName(value = "terms") @Required val terms: kotlin.collections.List<kotlin.String>,

    /* When searching for multiple terms, can use `AND` or `OR` combinator.  - `AND`: Only include lines with **all** terms present in that line. - `OR`: Include lines that have one or more matches in the terms. */
    @SerialName(value = "combinator") val combinator: SearchCombinator? = null,

    /* Enable `--details` */
    @SerialName(value = "details") val details: kotlin.Boolean? = null,

    /* Invert the results, ie return all lines that DON'T match the terms / combinator. */
    @SerialName(value = "invert") val invert: kotlin.Boolean? = null,

    /* Enable `--no-resolve` */
    @SerialName(value = "no_resolve") val noResolve: kotlin.Boolean? = null,

    /* Enable `--no-task-ids` */
    @SerialName(value = "no_task_ids") val noTaskIds: kotlin.Boolean? = null,

    /* Enable `--timestamps` */
    @SerialName(value = "timestamps") val timestamps: kotlin.Boolean? = null

) {


}

