/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ca.glong.komodo.core.openapi.models

import ca.glong.komodo.core.openapi.models.EndpointPortConfig
import ca.glong.komodo.core.openapi.models.EndpointSpec
import ca.glong.komodo.core.openapi.models.ServiceEndpointVirtualIps

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param ports 
 * @param spec 
 * @param virtualIPs 
 */
@Serializable@Serializable

data class ServiceEndpoint (

    @SerialName(value = "Ports") val ports: kotlin.collections.List<EndpointPortConfig>? = null,

    @SerialName(value = "Spec") val spec: EndpointSpec? = null,

    @SerialName(value = "VirtualIPs") val virtualIPs: kotlin.collections.List<ServiceEndpointVirtualIps>? = null

) {


}

