/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ca.glong.komodo.core.openapi.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * **Admin only.** Set `everyone` property of User Group. Response: [UserGroup]
 *
 * @param everyone Whether this user group applies to everyone.
 * @param userGroup Id or name.
 */
@Serializable@Serializable

data class SetEveryoneUserGroup (

    /* Whether this user group applies to everyone. */
    @SerialName(value = "everyone") @Required val everyone: kotlin.Boolean,

    /* Id or name. */
    @SerialName(value = "user_group") @Required val userGroup: kotlin.String

) {


}

