/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ca.glong.komodo.core.openapi.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * **Admin only.** Completely override the users in the group. Response: [UserGroup]
 *
 * @param userGroup Id or name.
 * @param users The user ids or usernames to hard set as the group's users.
 */
@Serializable@Serializable

data class SetUsersInUserGroup (

    /* Id or name. */
    @SerialName(value = "user_group") @Required val userGroup: kotlin.String,

    /* The user ids or usernames to hard set as the group's users. */
    @SerialName(value = "users") @Required val users: kotlin.collections.List<kotlin.String>

) {


}

