/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ca.glong.komodo.core.openapi.models

import ca.glong.komodo.core.openapi.models.FileContents
import ca.glong.komodo.core.openapi.models.StackRemoteFileContents
import ca.glong.komodo.core.openapi.models.StackServiceNames

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param deployedConfig The output of `docker compose config`. This is updated whenever Komodo successfully deploys the stack.
 * @param deployedContents The deployed compose / additional file contents. This is updated whenever Komodo successfully deploys the stack.
 * @param deployedHash Deployed short commit hash, or null. Only for repo based stacks.
 * @param deployedMessage Deployed commit message, or null. Only for repo based stacks
 * @param deployedProjectName The deployed project name. This is updated whenever Komodo successfully deploys the stack. If it is present, Komodo will use it for actions over other options, to ensure control is maintained after changing the project name (there is no rename compose project api).
 * @param deployedServices The deployed service names. This is updated whenever it is empty, or deployed contents is updated.
 * @param latestHash Latest commit hash, or null
 * @param latestMessage Latest commit message, or null
 * @param latestServices The latest service names. This is updated whenever the stack cache refreshes, using the latest file contents (either db defined or remote).
 * @param missingFiles If any of the expected compose / additional files are missing in the repo, they will be stored here.
 * @param remoteContents The remote compose / additional file contents, whether on host or in repo. This is updated whenever Komodo refreshes the stack cache. It will be empty if the file is defined directly in the stack config.
 * @param remoteErrors If there was an error in getting the remote contents, it will be here.
 */
@Serializable@Serializable

data class StackInfo (

    /* The output of `docker compose config`. This is updated whenever Komodo successfully deploys the stack. */
    @SerialName(value = "deployed_config") val deployedConfig: kotlin.String? = null,

    /* The deployed compose / additional file contents. This is updated whenever Komodo successfully deploys the stack. */
    @SerialName(value = "deployed_contents") val deployedContents: kotlin.collections.List<FileContents>? = null,

    /* Deployed short commit hash, or null. Only for repo based stacks. */
    @SerialName(value = "deployed_hash") val deployedHash: kotlin.String? = null,

    /* Deployed commit message, or null. Only for repo based stacks */
    @SerialName(value = "deployed_message") val deployedMessage: kotlin.String? = null,

    /* The deployed project name. This is updated whenever Komodo successfully deploys the stack. If it is present, Komodo will use it for actions over other options, to ensure control is maintained after changing the project name (there is no rename compose project api). */
    @SerialName(value = "deployed_project_name") val deployedProjectName: kotlin.String? = null,

    /* The deployed service names. This is updated whenever it is empty, or deployed contents is updated. */
    @SerialName(value = "deployed_services") val deployedServices: kotlin.collections.List<StackServiceNames>? = null,

    /* Latest commit hash, or null */
    @SerialName(value = "latest_hash") val latestHash: kotlin.String? = null,

    /* Latest commit message, or null */
    @SerialName(value = "latest_message") val latestMessage: kotlin.String? = null,

    /* The latest service names. This is updated whenever the stack cache refreshes, using the latest file contents (either db defined or remote). */
    @SerialName(value = "latest_services") val latestServices: kotlin.collections.List<StackServiceNames>? = null,

    /* If any of the expected compose / additional files are missing in the repo, they will be stored here. */
    @SerialName(value = "missing_files") val missingFiles: kotlin.collections.List<kotlin.String>? = null,

    /* The remote compose / additional file contents, whether on host or in repo. This is updated whenever Komodo refreshes the stack cache. It will be empty if the file is defined directly in the stack config. */
    @SerialName(value = "remote_contents") val remoteContents: kotlin.collections.List<StackRemoteFileContents>? = null,

    /* If there was an error in getting the remote contents, it will be here. */
    @SerialName(value = "remote_errors") val remoteErrors: kotlin.collections.List<FileContents>? = null

) {


}

