/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ca.glong.komodo.core.openapi.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param containerName Will either be the declared container_name in the compose file, or a pattern to match auto named containers.  Auto named containers are composed of three parts:  1. The name of the compose project (top level name field of compose file).    This defaults to the name of the parent folder of the compose file.    Komodo will always set it to be the name of the stack, but imported stacks    will have a different name. 2. The service name 3. The replica number  Example: stacko-mongo-1.  This stores only 1. and 2., ie stacko-mongo. Containers will be matched via regex like `^container_name-?[0-9]*$``  Note. Setting container_name is not supported by Swarm, so will always be 1. and 2. in Swarm mode.
 * @param serviceName The name of the service
 * @param image The services image.
 * @param imageDigest Store the associated image digest. This includes both the image name / tag, and the specific digest hash.
 */
@Serializable@Serializable

data class StackServiceNames (

    /* Will either be the declared container_name in the compose file, or a pattern to match auto named containers.  Auto named containers are composed of three parts:  1. The name of the compose project (top level name field of compose file).    This defaults to the name of the parent folder of the compose file.    Komodo will always set it to be the name of the stack, but imported stacks    will have a different name. 2. The service name 3. The replica number  Example: stacko-mongo-1.  This stores only 1. and 2., ie stacko-mongo. Containers will be matched via regex like `^container_name-?[0-9]*$``  Note. Setting container_name is not supported by Swarm, so will always be 1. and 2. in Swarm mode. */
    @SerialName(value = "container_name") @Required val containerName: kotlin.String,

    /* The name of the service */
    @SerialName(value = "service_name") @Required val serviceName: kotlin.String,

    /* The services image. */
    @SerialName(value = "image") val image: kotlin.String? = null,

    /* Store the associated image digest. This includes both the image name / tag, and the specific digest hash. */
    @SerialName(value = "image_digest") val imageDigest: kotlin.String? = null

) {


}

