/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ca.glong.komodo.core.openapi.models

import ca.glong.komodo.core.openapi.models.ConfigSpec
import ca.glong.komodo.core.openapi.models.ObjectVersion

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * Swarm config details.  This would be just \"SwarmConfig\", but that would conflict with the Swarm (Komodo resource) Config type, which is also SwarmConfig.
 *
 * @param createdAt 
 * @param ID 
 * @param spec 
 * @param updatedAt 
 * @param version 
 */
@Serializable@Serializable

data class SwarmConfigDetails (

    @SerialName(value = "CreatedAt") val createdAt: kotlin.String? = null,

    @SerialName(value = "ID") val ID: kotlin.String? = null,

    @SerialName(value = "Spec") val spec: ConfigSpec? = null,

    @SerialName(value = "UpdatedAt") val updatedAt: kotlin.String? = null,

    @SerialName(value = "Version") val version: ObjectVersion? = null

) {


}

