/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ca.glong.komodo.core.openapi.models

import ca.glong.komodo.core.openapi.models.SwarmSpecTaskDefaultsLogDriver

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * Defaults for creating tasks in this cluster.
 *
 * @param logDriver 
 */
@Serializable@Serializable

data class SwarmSpecTaskDefaults (

    @SerialName(value = "LogDriver") val logDriver: SwarmSpecTaskDefaultsLogDriver? = null

) {


}

