/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ca.glong.komodo.core.openapi.models

import ca.glong.komodo.core.openapi.models.SwarmSpecCaConfigExternalCasProtocolEnum

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param caCert The root CA certificate (in PEM format) this external CA uses to issue TLS certificates (assumed to be to the current swarm root CA certificate if not provided).
 * @param options An object with key/value pairs that are interpreted as protocol-specific options for the external CA driver.
 * @param protocol Protocol for communication with the external CA (currently only `cfssl` is supported).
 * @param URL URL where certificate signing requests should be sent.
 */
@Serializable@Serializable

data class SwarmSpecCaConfigExternalCas (

    /* The root CA certificate (in PEM format) this external CA uses to issue TLS certificates (assumed to be to the current swarm root CA certificate if not provided). */
    @SerialName(value = "CACert") val caCert: kotlin.String? = null,

    /* An object with key/value pairs that are interpreted as protocol-specific options for the external CA driver. */
    @SerialName(value = "Options") val options: kotlin.collections.Map<kotlin.String, kotlin.String>? = null,

    /* Protocol for communication with the external CA (currently only `cfssl` is supported). */
    @SerialName(value = "Protocol") val protocol: SwarmSpecCaConfigExternalCasProtocolEnum? = null,

    /* URL where certificate signing requests should be sent. */
    @SerialName(value = "URL") val URL: kotlin.String? = null

) {


}

