/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ca.glong.komodo.core.openapi.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * Parameters related to encryption-at-rest.
 *
 * @param autoLockManagers If set, generate a key and use it to lock data stored on the managers.
 */
@Serializable@Serializable

data class SwarmSpecEncryptionConfig (

    /* If set, generate a key and use it to lock data stored on the managers. */
    @SerialName(value = "AutoLockManagers") val autoLockManagers: kotlin.Boolean? = null

) {


}

