/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ca.glong.komodo.core.openapi.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param contents The contents of the file
 * @param path The path of the file / error path relative to the resource path.
 * @param resourcePath The base resource path.
 */
@Serializable@Serializable

data class SyncFileContents (

    /* The contents of the file */
    @SerialName(value = "contents") @Required val contents: kotlin.String,

    /* The path of the file / error path relative to the resource path. */
    @SerialName(value = "path") @Required val path: kotlin.String,

    /* The base resource path. */
    @SerialName(value = "resource_path") val resourcePath: kotlin.String? = null

) {


}

