/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ca.glong.komodo.core.openapi.models

import ca.glong.komodo.core.openapi.models.SingleDiskUsage
import ca.glong.komodo.core.openapi.models.SystemLoadAverage
import ca.glong.komodo.core.openapi.models.Timelength

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * Realtime system stats data.
 *
 * @param cpuPerc Cpu usage percentage
 * @param disks Breakdown of individual disks, ie their usages, sizes, and mount points
 * @param memTotalGb Total memory in GB
 * @param memUsedGb Used memory in GB. 'Total' - 'Available' (not free) memory.
 * @param pollingRate The rate the system stats are being polled from the system
 * @param refreshListTs Unix timestamp in milliseconds when disk list was last refreshed
 * @param refreshTs Unix timestamp in milliseconds when stats were last polled
 * @param loadAverage Load average (1m, 5m, 15m)
 * @param memFreeGb [1.15.9+] Free memory in GB. This is really the 'Free' memory, not the 'Available' memory. It may be different than mem_total_gb - mem_used_gb.
 * @param networkEgressBytes Network egress usage in MB
 * @param networkIngressBytes Network ingress usage in MB
 */
@Serializable@Serializable

data class SystemStats (

    /* Cpu usage percentage */
    @SerialName(value = "cpu_perc") @Required val cpuPerc: kotlin.Float,

    /* Breakdown of individual disks, ie their usages, sizes, and mount points */
    @SerialName(value = "disks") @Required val disks: kotlin.collections.List<SingleDiskUsage>,

    /* Total memory in GB */
    @SerialName(value = "mem_total_gb") @Required val memTotalGb: kotlin.Double,

    /* Used memory in GB. 'Total' - 'Available' (not free) memory. */
    @SerialName(value = "mem_used_gb") @Required val memUsedGb: kotlin.Double,

    /* The rate the system stats are being polled from the system */
    @SerialName(value = "polling_rate") @Required val pollingRate: Timelength,

    /* Unix timestamp in milliseconds when disk list was last refreshed */
    @SerialName(value = "refresh_list_ts") @Required val refreshListTs: kotlin.Long,

    /* Unix timestamp in milliseconds when stats were last polled */
    @SerialName(value = "refresh_ts") @Required val refreshTs: kotlin.Long,

    /* Load average (1m, 5m, 15m) */
    @SerialName(value = "load_average") val loadAverage: SystemLoadAverage? = null,

    /* [1.15.9+] Free memory in GB. This is really the 'Free' memory, not the 'Available' memory. It may be different than mem_total_gb - mem_used_gb. */
    @SerialName(value = "mem_free_gb") val memFreeGb: kotlin.Double? = null,

    /* Network egress usage in MB */
    @SerialName(value = "network_egress_bytes") val networkEgressBytes: kotlin.Double? = null,

    /* Network ingress usage in MB */
    @SerialName(value = "network_ingress_bytes") val networkIngressBytes: kotlin.Double? = null

) {


}

