/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ca.glong.komodo.core.openapi.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param command 
 * @param path 
 */
@Serializable@Serializable

data class SystemCommand (

    @SerialName(value = "command") val command: kotlin.String? = null,

    @SerialName(value = "path") val path: kotlin.String? = null

) {


}

