/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ca.glong.komodo.core.openapi.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * SELinux labels of the container
 *
 * @param disable Disable SELinux
 * @param level SELinux level label
 * @param role SELinux role label
 * @param type SELinux type label
 * @param user SELinux user label
 */
@Serializable@Serializable

data class TaskSpecContainerSpecPrivilegesSeLinuxContext (

    /* Disable SELinux */
    @SerialName(value = "Disable") val disable: kotlin.Boolean? = null,

    /* SELinux level label */
    @SerialName(value = "Level") val level: kotlin.String? = null,

    /* SELinux role label */
    @SerialName(value = "Role") val role: kotlin.String? = null,

    /* SELinux type label */
    @SerialName(value = "Type") val type: kotlin.String? = null,

    /* SELinux user label */
    @SerialName(value = "User") val user: kotlin.String? = null

) {


}

