/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ca.glong.komodo.core.openapi.models

import ca.glong.komodo.core.openapi.models.TaskSpecContainerSpecPrivilegesAppArmorModeEnum

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * Options for configuring AppArmor on the container
 *
 * @param mode 
 */
@Serializable@Serializable

data class TaskSpecContainerSpecPrivilegesAppArmor (

    @SerialName(value = "Mode") val mode: TaskSpecContainerSpecPrivilegesAppArmorModeEnum? = null

) {


}

