/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ca.glong.komodo.core.openapi.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * Specifies the log driver to use for tasks created from this spec. If not present, the default one for the swarm will be used, finally falling back to the engine default if not specified.
 *
 * @param name 
 * @param options 
 */
@Serializable@Serializable

data class TaskSpecLogDriver (

    @SerialName(value = "Name") val name: kotlin.String? = null,

    @SerialName(value = "Options") val options: kotlin.collections.Map<kotlin.String, kotlin.String>? = null

) {


}

