/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ca.glong.komodo.core.openapi.models

import ca.glong.komodo.core.openapi.models.TaskSpecContainerSpecFile

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param configID ConfigID represents the ID of the specific config that we're referencing.
 * @param configName ConfigName is the name of the config that this references, but this is just provided for lookup/display purposes. The config in the reference will be identified by its ID.
 * @param file 
 */
@Serializable@Serializable

data class TaskSpecContainerSpecConfigs (

    /* ConfigID represents the ID of the specific config that we're referencing. */
    @SerialName(value = "ConfigID") val configID: kotlin.String? = null,

    /* ConfigName is the name of the config that this references, but this is just provided for lookup/display purposes. The config in the reference will be identified by its ID. */
    @SerialName(value = "ConfigName") val configName: kotlin.String? = null,

    @SerialName(value = "File") val file: TaskSpecContainerSpecFile? = null

) {


}

