/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ca.glong.komodo.core.openapi.models


import kotlinx.serialization.*

/**
 * 
 *
 * Values: EMPTY,NONE,ON_FAILURE,ANY
 */
@Serializable@Serializable
enum class TaskSpecRestartPolicyConditionEnum(val value: kotlin.String) {

    @SerialName(value = "EMPTY")
    EMPTY("EMPTY"),

    @SerialName(value = "none")
    NONE("none"),

    @SerialName(value = "on-failure")
    ON_FAILURE("on-failure"),

    @SerialName(value = "any")
    ANY("any");

    /**
     * Override [toString()] to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): kotlin.String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is TaskSpecRestartPolicyConditionEnum) "$data" else null

        /**
         * Returns a valid [TaskSpecRestartPolicyConditionEnum] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): TaskSpecRestartPolicyConditionEnum? = data?.let {
          val normalizedData = "$it".lowercase()
          values().firstOrNull { value ->
            it == value || normalizedData == "$value".lowercase()
          }
        }
    }
}


