/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ca.glong.komodo.core.openapi.models


import kotlinx.serialization.*

/**
 * 
 *
 * Values: NEW,ALLOCATED,PENDING,ASSIGNED,ACCEPTED,PREPARING,READY,STARTING,RUNNING,COMPLETE,SHUTDOWN,FAILED,REJECTED,REMOVE,ORPHANED
 */
@Serializable@Serializable
enum class TaskState(val value: kotlin.String) {

    @SerialName(value = "new")
    NEW("new"),

    @SerialName(value = "allocated")
    ALLOCATED("allocated"),

    @SerialName(value = "pending")
    PENDING("pending"),

    @SerialName(value = "assigned")
    ASSIGNED("assigned"),

    @SerialName(value = "accepted")
    ACCEPTED("accepted"),

    @SerialName(value = "preparing")
    PREPARING("preparing"),

    @SerialName(value = "ready")
    READY("ready"),

    @SerialName(value = "starting")
    STARTING("starting"),

    @SerialName(value = "running")
    RUNNING("running"),

    @SerialName(value = "complete")
    COMPLETE("complete"),

    @SerialName(value = "shutdown")
    SHUTDOWN("shutdown"),

    @SerialName(value = "failed")
    FAILED("failed"),

    @SerialName(value = "rejected")
    REJECTED("rejected"),

    @SerialName(value = "remove")
    REMOVE("remove"),

    @SerialName(value = "orphaned")
    ORPHANED("orphaned");

    /**
     * Override [toString()] to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): kotlin.String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is TaskState) "$data" else null

        /**
         * Returns a valid [TaskState] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): TaskState? = data?.let {
          val normalizedData = "$it".lowercase()
          values().firstOrNull { value ->
            it == value || normalizedData == "$value".lowercase()
          }
        }
    }
}


