/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ca.glong.komodo.core.openapi.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param container 
 * @param server 
 */
@Serializable@Serializable

data class TerminalTargetOneOf1Params (

    @SerialName(value = "container") @Required val container: kotlin.String,

    @SerialName(value = "server") @Required val server: kotlin.String

) {


}

