/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ca.glong.komodo.core.openapi.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param stack 
 * @param service 
 */
@Serializable@Serializable

data class TerminalTargetOneOf2Params (

    @SerialName(value = "stack") @Required val stack: kotlin.String,

    @SerialName(value = "service") val service: kotlin.String? = null

) {


}

