/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ca.glong.komodo.core.openapi.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * **Admin only.** Update a docker registry account. Response: [DockerRegistryAccount].
 *
 * @param account The partial docker registry account.
 * @param id The id of the docker registry to update
 */
@Serializable@Serializable

data class UpdateDockerRegistryAccount (

    /* The partial docker registry account. */
    @SerialName(value = "account") @Required val account: kotlin.collections.Map<kotlin.String, kotlin.Any>,

    /* The id of the docker registry to update */
    @SerialName(value = "id") @Required val id: kotlin.String

) {


}

