/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ca.glong.komodo.core.openapi.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * **Admin only.** Update a user's \"base\" permissions, eg. \"enabled\". Response: [NoData].
 *
 * @param userId The target user.
 * @param createBuilds If specified, will update user's ability to create builds.
 * @param createServers If specified, will update user's ability to create servers.
 * @param enabled If specified, will update users enabled state.
 */
@Serializable@Serializable

data class UpdateUserBasePermissions (

    /* The target user. */
    @SerialName(value = "user_id") @Required val userId: kotlin.String,

    /* If specified, will update user's ability to create builds. */
    @SerialName(value = "create_builds") val createBuilds: kotlin.Boolean? = null,

    /* If specified, will update user's ability to create servers. */
    @SerialName(value = "create_servers") val createServers: kotlin.Boolean? = null,

    /* If specified, will update users enabled state. */
    @SerialName(value = "enabled") val enabled: kotlin.Boolean? = null

) {


}

