/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ca.glong.komodo.core.openapi.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * Updates the Server with an explicit Public Key. Response: [Update]
 *
 * @param publicKey Spki base64 public key
 * @param server Server Id or name
 */
@Serializable@Serializable

data class UpdateServerPublicKey (

    /* Spki base64 public key */
    @SerialName(value = "public_key") @Required val publicKey: kotlin.String,

    /* Server Id or name */
    @SerialName(value = "server") @Required val server: kotlin.String

) {


}

