/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ca.glong.komodo.core.openapi.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * Non-human managed user, can have it's own permissions / api keys
 *
 * @param description 
 */
@Serializable@Serializable

data class UserConfigOneOf4Data (

    @SerialName(value = "description") @Required val description: kotlin.String

) {


}

