/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ca.glong.komodo.core.openapi.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * User that logs in via Google Oauth
 *
 * @param avatar 
 * @param googleId 
 */
@Serializable@Serializable

data class UserConfigOneOf1Data (

    @SerialName(value = "avatar") @Required val avatar: kotlin.String,

    @SerialName(value = "google_id") @Required val googleId: kotlin.String

) {


}

