/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ca.glong.komodo.core.openapi.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param major 
 * @param minor 
 * @param patch 
 */
@Serializable@Serializable

data class Version (

    @SerialName(value = "major") @Required val major: kotlin.Int,

    @SerialName(value = "minor") @Required val minor: kotlin.Int,

    @SerialName(value = "patch") @Required val patch: kotlin.Int

) {


}

