/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ca.glong.komodo.core.openapi.models


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * Usage details about the volume. This information is used by the `GET /system/df` endpoint, and omitted in other endpoints.
 *
 * @param refCount The number of containers referencing this volume. This field is set to `-1` if the reference-count is not available.
 * @param propertySize Amount of disk space used by the volume (in bytes). This information is only available for volumes created with the `\\\"local\\\"` volume driver. For volumes created with other volume drivers, this field is set to `-1` (\\\"not available\\\")
 */
@Serializable@Serializable

data class VolumeUsageData (

    /* The number of containers referencing this volume. This field is set to `-1` if the reference-count is not available. */
    @SerialName(value = "RefCount") @Required val refCount: kotlin.Long,

    /* Amount of disk space used by the volume (in bytes). This information is only available for volumes created with the `\\\"local\\\"` volume driver. For volumes created with other volume drivers, this field is set to `-1` (\\\"not available\\\") */
    @SerialName(value = "Size") @Required val propertySize: kotlin.Long

) {


}

